-- ============================================================================
-- 006 — Notifications
-- Target: MariaDB 10.11.x / InnoDB
-- ============================================================================
--
-- In-app only. There is no email/SMS provider integrated (and none of their credentials are
-- available to configure one), so this is deliberately scoped to what Mirwal can actually
-- deliver today: a real, persistent notification a signed-in user sees when they visit the
-- app, generated by real events (an order placed, a status change, a return filed or
-- resolved) — never a fabricated count or a static list.
-- ============================================================================

CREATE TABLE notifications (
  id          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id   CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  user_id     BIGINT UNSIGNED NOT NULL,

  -- A stable machine-readable event name (order_placed, order_status_changed,
  -- return_requested, return_resolved, item_cancelled, ...), not a display string, so the
  -- frontend can pick an icon per type without parsing `title`.
  type        VARCHAR(50)  CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  title       VARCHAR(150) NOT NULL,
  body        VARCHAR(500) NOT NULL DEFAULT '',
  -- Where clicking the notification should take the user, e.g. /order-success/<id>. Nullable:
  -- not every notification needs a destination.
  link        VARCHAR(255) NULL DEFAULT NULL,

  read_at     DATETIME(3) NULL DEFAULT NULL,
  created_at  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

  PRIMARY KEY (id),
  UNIQUE KEY uq_notifications_public_id (public_id),
  KEY ix_notifications_user_created (user_id, created_at),
  KEY ix_notifications_user_unread (user_id, read_at),

  CONSTRAINT fk_notifications_user
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC
  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
