import { useState } from 'react'
import SellerLayout from '../SellerLayout'
import './add-product.css'
import { navigateTo } from '../../navigation'
import Icon from '../../components/Icon'

const steps = ['Basic Info', 'Media', 'Product Details', 'AI Intelligence', 'Compatibility', 'Variants', 'Pricing & Stock', 'Shipping', 'Preview']
const fields = { basic: [['Product Name *', 'title', 'Wireless Bluetooth Headphones'], ['Short Description *', 'shortDescription', 'High-quality wireless headphones with deep bass and noise cancellation.'], ['Full Description *', 'description', 'Experience premium sound with crystal-clear audio, deep bass and comfortable all-day wear.']], details: [['Product Type *', 'productType', 'Physical Product'], ['Category *', 'category', 'Electronics > Audio > Headphones'], ['Brand', 'brand', 'SoundPro'], ['SKU', 'sku', 'MW-HP-001'], ['MPN / Model Number', 'mpn', 'SP-H100'], ['Barcode / GTIN', 'barcode', '089345678901'], ['Product Condition', 'condition', 'New']] }
const initialData = { title: '', shortDescription: '', description: '', productType: '', category: '', brand: '', sku: '', mpn: '', barcode: '', condition: '', bestFor: '', benefits: '', useCases: '', idealCustomer: '', notIdealFor: '', compatible: '', worksWith: '', boughtTogether: '', notWorksWith: '', alternatives: '', regularPrice: '', salePrice: '', costPrice: '', tax: '', stock: '', warehouse: '', threshold: '', weight: '', dimensions: '', shippingClass: '', shippingRequired: true }

const Input = ({ label, name, value, onChange, area = false, placeholder = '' }) => <label className="product-field"><span>{label}</span>{area ? <textarea name={name} value={value} onChange={onChange} placeholder={placeholder} /> : <input name={name} value={value} onChange={onChange} placeholder={placeholder} />}</label>
const Chips = ({ items }) => <div className="chip-list">{items.map((item) => <span key={item}>{item}<Icon name="xmark" /></span>)}<button type="button"><Icon name="plus" /> Add Tag</button></div>

const AddProduct = ({ editMode = false }) => {
  const [step, setStep] = useState(0)
  const [data, setData] = useState(initialData)
  const update = (event) => setData((current) => ({ ...current, [event.target.name]: event.target.value }))
  const next = () => setStep((current) => Math.min(8, current + 1))
  const previous = () => setStep((current) => Math.max(0, current - 1))
  const saveDraft = () => setData((current) => ({ ...current, status: 'draft' }))
  const renderBasic = () => <div className="step-grid"><section className="form-section"><h2>Basic Information</h2><Input label="Product Name *" name="title" value={data.title} onChange={update} placeholder="Enter product name" /><Input label="Short Description *" name="shortDescription" value={data.shortDescription} onChange={update} area placeholder="Brief product description" /><Input label="Full Description *" name="description" value={data.description} onChange={update} area placeholder="Write a detailed description..." /></section><section className="form-section"><h2>Product Fields</h2>{fields.details.map(([label, name, placeholder]) => <Input key={name} label={label} name={name} value={data[name]} onChange={update} placeholder={placeholder} />)}<label className="product-field"><span>Tags</span><Chips items={['wireless', 'headphones', 'noise-cancellation']} /></label></section></div>
  const renderMedia = () => <section className="form-section"><h2>Media</h2><p className="section-help">Add high-quality images and videos of your product.</p><div className="media-grid"><div className="upload-card primary"><Icon name="image" /><strong>Main Image *</strong><small>Recommended 1000 × 1000px</small><button type="button">Upload Image</button></div>{['Additional Images *', 'Product Video', '360° View'].map((label) => <div className="upload-card" key={label}><Icon name="cloud-arrow-up" /><strong>{label}</strong><small>JPG, PNG up to 2MB</small><button type="button">Upload Media</button></div>)}</div></section>
  const renderDetails = () => <section className="form-section"><h2>Product Details</h2><label className="product-field"><span>Attribute Set / Category</span><select><option>Audio & Headphones</option><option>Electronics</option></select></label><div className="attribute-table">{[['Driver Size', '40mm'], ['Frequency Response', '20Hz - 20kHz'], ['Impedance', '32 Ohm'], ['Sensitivity', '108dB'], ['Connectivity', 'Bluetooth 5.3'], ['Battery Life', 'Up to 40 hours'], ['Charging Time', '2 hours'], ['Noise Cancellation', 'Active Noise Cancellation'], ['Microphone', 'Built-in Microphone'], ['Weight', '250g']].map(([label, value]) => <div key={label}><span>{label}</span><input defaultValue={value} /><select><option>Enabled</option><option>Optional</option></select></div>)}</div><button type="button" className="outline-action"><Icon name="plus" /> Add Custom Attribute</button></section>
  const renderAi = () => <div className="step-grid"><section className="form-section"><h2>AI Intelligence</h2><p className="section-help">Help Mirwal AI understand and recommend your product better.</p><Input label="Best For" name="bestFor" value={data.bestFor} onChange={update} placeholder="Students, Professionals, Gamers" /><Input label="Key Benefits" name="benefits" value={data.benefits} onChange={update} area placeholder="Deep bass and crystal clear sound\nDurable noise cancellation\nLong battery life" /><Input label="Primary Use Cases" name="useCases" value={data.useCases} onChange={update} placeholder="Music, Calls, Gaming, Travel" /><Input label="Ideal Customer" name="idealCustomer" value={data.idealCustomer} onChange={update} area placeholder="People who want high-quality wireless headphones" /><Input label="Not Ideal For" name="notIdealFor" value={data.notIdealFor} onChange={update} placeholder="Users seeking very low-cost headphones" /></section><section className="form-section ai-discovery"><h2><Icon name="wand-magic-sparkles" /> Search & Discovery</h2><p>Include natural language customers may use to discover this product.</p><Input label="AI Search Keywords" name="keywords" value={data.keywords || ''} onChange={update} placeholder="premium audio, wireless music, travel headphones" /><Input label="Product Understanding" name="understanding" value={data.understanding || ''} onChange={update} area placeholder="What makes this product different?" /></section></div>
  const renderCompatibility = () => <div className="step-grid"><section className="form-section"><h2>Compatibility & Relationships</h2><Input label="Compatible With" name="compatible" value={data.compatible} onChange={update} placeholder="Smartphones, Laptops, Tablets, PCs, Gaming Consoles" /><Input label="Works With" name="worksWith" value={data.worksWith} onChange={update} placeholder="Android, iOS, Windows, macOS" /><Input label="Doesn't Work With" name="notWorksWith" value={data.notWorksWith} onChange={update} placeholder="Older devices without Bluetooth" /></section><section className="form-section"><h2>Related Products</h2><Input label="Frequently Bought Together" name="boughtTogether" value={data.boughtTogether} onChange={update} placeholder="Cable, Charger, Headphone case" /><Input label="Alternative Products" name="alternatives" value={data.alternatives} onChange={update} area placeholder="Similar headphones and products" /></section></div>
  const renderVariants = () => <section className="form-section"><h2>Variants</h2><p className="section-help">Offer different options for this product.</p><div className="variant-options"><span>Variant Options</span><Chips items={['Color', 'Size']} /><button type="button" className="outline-action"><Icon name="plus" /> Add Option</button></div><div className="variant-table"><div className="variant-head">{['Variant', 'SKU', 'Image', 'Price', 'Sale Price', 'Stock', 'Weight'].map((head) => <b key={head}>{head}</b>)}</div>{['Black / Standard', 'White / Standard', 'Blue / Standard'].map((variant, index) => <div className="variant-row" key={variant}><span>{variant}</span><input defaultValue={`MW-HP-00${index + 1}`} /><button type="button"><Icon name="image" /></button><input defaultValue={index ? '2499' : '2199'} /><input placeholder="2,499" /><input defaultValue="30" /><input defaultValue="250g" /></div>)}</div><button type="button" className="outline-action"><Icon name="plus" /> Add Variant</button></section>
  const renderPricing = () => <div className="step-grid"><section className="form-section"><h2>Pricing & Stock</h2><Input label="Regular Price (PKR) *" name="regularPrice" value={data.regularPrice} onChange={update} placeholder="2,499" /><Input label="Sale Price (PKR)" name="salePrice" value={data.salePrice} onChange={update} placeholder="2,199" /><Input label="Cost Price (PKR)" name="costPrice" value={data.costPrice} onChange={update} placeholder="1,500" /><Input label="Tax" name="tax" value={data.tax} onChange={update} placeholder="Select tax rate" /></section><section className="form-section"><h2>Inventory</h2><Input label="SKU" name="sku" value={data.sku} onChange={update} placeholder="MW-HP-001" /><Input label="Stock Quantity" name="stock" value={data.stock} onChange={update} placeholder="50" /><Input label="Warehouse" name="warehouse" value={data.warehouse} onChange={update} placeholder="Main Warehouse" /><Input label="Low Stock Threshold" name="threshold" value={data.threshold} onChange={update} placeholder="10" /></section></div>
  const renderShipping = () => <div className="step-grid"><section className="form-section"><h2>Shipping</h2><label className="toggle-field"><span>Shipping required</span><input type="checkbox" checked={data.shippingRequired} onChange={(event) => setData((current) => ({ ...current, shippingRequired: event.target.checked }))} /></label><Input label="Weight" name="weight" value={data.weight} onChange={update} placeholder="250 g" /><Input label="Dimensions (L × W × H)" name="dimensions" value={data.dimensions} onChange={update} placeholder="20 × 18 × 8 cm" /><Input label="Package Size" name="packageSize" value={data.packageSize || ''} onChange={update} placeholder="Small" /></section><section className="form-section"><h2>Delivery Configuration</h2><Input label="Shipping Class" name="shippingClass" value={data.shippingClass} onChange={update} placeholder="Standard" /><Input label="Delivery Information" name="delivery" value={data.delivery || ''} onChange={update} area placeholder="Delivered within 3-5 business days" /><Input label="Shipping Locations" name="locations" value={data.locations || ''} onChange={update} placeholder="Pakistan, Nationwide" /></section></div>
  const renderPreview = () => <section className="form-section preview-card"><h2>Product Preview</h2><div className="preview-product"><div className="preview-image"><Icon name="headphones" /></div><div><h3>{data.title || 'Wireless Bluetooth Headphones'}</h3><p>{data.brand || 'SoundPro'} · {data.category || 'Electronics'}</p><Stars /><strong>Rs. {data.salePrice || '2,199'} <del>Rs. {data.regularPrice || '2,499'}</del></strong><p>{data.description || 'Premium wireless headphones with deep bass, noise cancellation and long battery life.'}</p></div></div><div className="preview-details"><b>Product Details</b><span>Stock: {data.stock || '50'}</span><span>Weight: {data.weight || '250g'}</span><span>Shipping: {data.shippingClass || 'Standard'}</span></div></section>
  const content = [renderBasic, renderMedia, renderDetails, renderAi, renderCompatibility, renderVariants, renderPricing, renderShipping, renderPreview][step]()
  return <SellerLayout activeItem="add-product" breadcrumbs={[{ label: 'Dashboard', onClick: () => navigateTo('/seller') }, { label: 'Products', onClick: () => navigateTo('/seller/products') }, { label: editMode ? 'Edit Product' : 'Add New Product' }]}>
    <div className="add-product-content"><div className="product-builder-header"><div><h1>{editMode ? 'Edit Product' : 'Add New Product'}</h1><p>Create a new product and add all details to help Mirwal AI understand it better.</p></div><div className="builder-actions"><button type="button" onClick={saveDraft}><Icon name="floppy-disk" /> Save as Draft</button><button type="button" className="primary-action" onClick={next}>Next: {steps[Math.min(step + 1, 8)]} <Icon name="arrow-right" /></button></div></div><nav className="step-progress" aria-label="Product creation steps">{steps.map((label, index) => <button type="button" key={label} className={`${index === step ? 'active' : ''} ${index < step ? 'complete' : ''}`} onClick={() => index <= step && setStep(index)}><span>{index < step ? <Icon name="check" /> : index + 1}</span>{label}</button>)}</nav><div className="builder-layout"><main><div className="step-heading"><span>Step {step + 1} of 9</span><h2>{steps[step]}</h2></div>{content}<div className="builder-footer"><button type="button" onClick={previous} disabled={step === 0}><Icon name="arrow-left" /> Previous</button>{step === 8 ? <button type="button" className="primary-action" onClick={() => navigateTo('/seller/products')}><Icon name="check" /> Publish Product</button> : <button type="button" className="primary-action" onClick={next}>Next: {steps[step + 1]} <Icon name="arrow-right" /></button>}</div></main><aside className="readiness-panel"><h3><Icon name="wand-magic-sparkles" /> AI Readiness Tip</h3><p>Completing all the required fields improves your AI readiness score.</p><div className="readiness-circle"><strong>{22 + step * 9}%</strong><small>Fair</small></div><ul>{steps.map((label, index) => <li className={index <= step ? 'done' : ''} key={label}><Icon name={index <= step ? 'check' : 'circle'} /> {label}</li>)}</ul></aside></div></div>
  </SellerLayout>
}
const Stars = () => <span className="preview-stars"><Icon name="star" /><Icon name="star" /><Icon name="star" /><Icon name="star" /><Icon name="star" /></span>
export default AddProduct
