import { useState } from 'react'
import SellerLayout from '../SellerLayout'
import './finance.css'
import './finance-extra.css'
import { navigateTo } from '../../navigation'
import Icon from '../../components/Icon'

const transactions = [['TRX2454875', 'May 24, 2025 10:30 AM', 'Order #MW1254876', 'Sale', 'Rs. 2,199.00'], ['TRX2454874', 'May 24, 2025 09:15 AM', 'Refund for #MW1254862', 'Refund', 'Rs. -1,299.00'], ['TRX2454873', 'May 23, 2025 08:45 AM', 'Commission', 'Commission', 'Rs. -279.00'], ['TRX2454872', 'May 23, 2025 02:10 PM', 'Payout to Bank', 'Payout', 'Rs. -35,000.00']]
const withdrawals = [['WTH-0056', 'May 21, 2025', 'Rs. 25,000.00', 'Bank Transfer', 'Completed'], ['WTH-0055', 'May 14, 2025', 'Rs. 18,000.00', 'Bank Transfer', 'Completed'], ['WTH-0054', 'May 07, 2025', 'Rs. 32,500.00', 'Bank Transfer', 'Completed'], ['WTH-0053', 'Apr 30, 2025', 'Rs. 15,000.00', 'Bank Transfer', 'Failed']]
const invoices = [['INV-2025-05', 'May 2025 Statement', 'May 31, 2025', 'Rs. 32,450.00'], ['INV-2025-04', 'April 2025 Statement', 'Apr 30, 2025', 'Rs. 28,750.00'], ['INV-2025-03', 'March 2025 Statement', 'Mar 31, 2025', 'Rs. 30,200.00']]

const Card = ({ label, value, note, icon, index }) => <article className={`finance-card finance-card-${index}`}><span>{label}</span><strong>{value}</strong><small>{note}</small><i><Icon name={icon} /></i></article>
const FinanceTable = ({ title, children, action = 'Download Statement' }) => <section className="finance-panel finance-table-panel"><div className="finance-panel-header"><h2>{title}</h2><button type="button"><Icon name="download" /> {action}</button></div>{children}</section>
const FinancePage = ({ type = 'overview' }) => {
  const [amount, setAmount] = useState('')
  const [message, setMessage] = useState('')
  const isWithdrawals = type === 'withdrawals'
  const isSettings = type === 'settings'
  const title = isWithdrawals ? 'Withdraw Funds' : isSettings ? 'Payment Settings' : 'Finance Overview'
  const subtitle = isWithdrawals ? 'Manage withdrawals, history and financial statements.' : isSettings ? 'Manage your payout methods, business details and security preferences.' : 'Track your earnings, payouts and account balance.'
  const requestWithdrawal = (event) => { event.preventDefault(); setMessage(amount ? `Withdrawal request for Rs. ${amount} submitted.` : 'Enter an amount to request a withdrawal.'); if (amount) setAmount('') }
  return <SellerLayout activeItem={isWithdrawals ? 'withdrawals' : isSettings ? 'payment-methods' : 'overview'} breadcrumbs={[{ label: 'Dashboard', onClick: () => navigateTo('/seller') }, { label: title }]}><div className="finance-container"><div className="finance-header"><div><h1>{title}</h1><p>{subtitle}</p></div><div><button type="button" className="finance-secondary"><Icon name="calendar" /> May 18, 2025 - May 24, 2025</button><button type="button" className="finance-secondary"><Icon name="upload" /> Export</button></div></div>{isSettings ? <SettingsContent /> : isWithdrawals ? <WithdrawalsContent amount={amount} setAmount={setAmount} message={message} requestWithdrawal={requestWithdrawal} /> : <OverviewContent />}</div></SellerLayout>
}
const OverviewContent = () => <><div className="finance-cards"><Card label="Available Balance" value="Rs. 52,430.00" note="Available for withdrawal" icon="wallet" index={0} /><Card label="Pending Balance" value="Rs. 18,790.00" note="On the way to payout" icon="hourglass-half" index={1} /><Card label="Total Earnings" value="Rs. 324,250.00" note="All time earnings" icon="coins" index={2} /><Card label="Total Withdrawn" value="Rs. 271,820.00" note="All time withdrawn" icon="money-bill-transfer" index={3} /></div><div className="finance-overview-grid"><section className="finance-panel earnings-chart"><h2>Earnings Overview</h2><div className="chart-visual"><svg viewBox="0 0 600 170" preserveAspectRatio="none"><polyline points="10,130 90,80 160,105 230,55 310,95 390,65 460,125 535,70 590,90" /></svg></div><div className="chart-labels"><span>Apr 25</span><span>Apr 30</span><span>May 05</span><span>May 10</span><span>May 15</span><span>May 20</span></div></section><section className="finance-panel balance-breakdown"><h2>Balance Breakdown</h2>{[['Available for Payout', 'Rs. 52,430.00', 'green'], ['Pending', 'Rs. 18,790.00', 'orange'], ['Processing', 'Rs. 6,320.00', 'blue'], ['Withdrawn', 'Rs. 271,820.00', 'purple']].map(([label, value, tone]) => <p key={label}><i className={tone} />{label}<strong>{value}</strong></p>)}</section><section className="finance-panel next-payout"><h2>Next Payout</h2><strong>Rs. 52,430.00</strong><small>Expected on May 28, 2025</small><button type="button" onClick={() => navigateTo('/seller/finance/withdrawals')}>View Withdrawals</button></section></div><FinanceTable title="Recent Transactions"><div className="finance-table-scroll"><table className="finance-table"><thead><tr><th>Transaction ID</th><th>Date & Time</th><th>Description</th><th>Type</th><th>Amount</th><th>Status</th></tr></thead><tbody>{transactions.map((row) => <tr key={row[0]}>{row.map((cell, index) => <td key={`${row[0]}-${index}`}>{index === 5 ? <em className="completed">{cell}</em> : cell}</td>)}<td><button type="button" aria-label="View transaction"><Icon name="eye" /></button></td></tr>)}</tbody></table></div></FinanceTable></>
const WithdrawalsContent = ({ amount, setAmount, message, requestWithdrawal }) => <><div className="finance-cards"><Card label="Available Balance" value="Rs. 52,430.00" note="Ready to withdraw" icon="wallet" index={0} /><Card label="Withdrawn This Month" value="Rs. 0.00" note="May 2025" icon="money-bill-transfer" index={1} /><Card label="Total Withdrawn" value="Rs. 271,820.00" note="All time" icon="chart-line" index={2} /></div><div className="withdrawal-grid"><section className="finance-panel withdrawal-form"><h2>Request Withdrawal</h2><p>Available balance: <strong>Rs. 52,430.00</strong></p><form onSubmit={requestWithdrawal}><label>Amount to Withdraw (PKR)<input type="number" min="1" max="52430" placeholder="Enter amount" value={amount} onChange={(event) => setAmount(event.target.value)} /></label><label>Withdrawal Method<select><option>Meezan Bank **** 6789</option><option>JazzCash **** 1234</option></select></label><button type="submit" className="finance-primary"><Icon name="money-bill-transfer" /> Request Withdrawal</button>{message && <small className="finance-message">{message}</small>}</form></section><section className="finance-panel"><h2>Withdrawal Schedule</h2><p className="schedule-value">Weekly</p><p className="muted">Next payout: May 28, 2025</p><p className="muted">Processing time: 2-3 business days</p><button type="button" className="finance-link">Change Schedule</button></section></div><FinanceTable title="Withdrawal History" action="Export History"><div className="finance-table-scroll"><table className="finance-table"><thead><tr><th>Withdrawal ID</th><th>Date</th><th>Amount</th><th>Method</th><th>Status</th><th>Action</th></tr></thead><tbody>{withdrawals.map((row) => <tr key={row[0]}>{row.map((cell, index) => <td key={`${row[0]}-${index}`}>{index === 4 ? <em className={cell === 'Failed' ? 'failed' : 'completed'}>{cell}</em> : cell}</td>)}<td><button type="button" aria-label="Download withdrawal"><Icon name="download" /></button></td></tr>)}</tbody></table></div></FinanceTable><FinanceTable title="Invoices & Statements"><div className="finance-table-scroll"><table className="finance-table"><thead><tr><th>Invoice ID</th><th>Description</th><th>Date</th><th>Amount</th><th>Action</th></tr></thead><tbody>{invoices.map((row) => <tr key={row[0]}>{row.map((cell, index) => <td key={`${row[0]}-${index}`}>{cell}</td>)}<td><button type="button" aria-label="Download invoice"><Icon name="download" /></button></td></tr>)}</tbody></table></div></FinanceTable></>
const SettingsContent = () => <><div className="settings-layout"><section className="finance-panel settings-card"><div className="settings-heading"><span className="settings-icon purple"><Icon name="building-columns" /></span><div><h2>Primary Payout Method</h2><p>Your earnings will be sent to this account.</p></div><em className="verified-badge">Primary</em></div><div className="bank-details"><strong>Meezan Bank</strong><span>Account holder: Awais Store</span><span>Account number: **** **** 6789</span><span>IBAN: PK36 MEZN 0000 1234 5678</span></div><button type="button" className="finance-link"><Icon name="pen" /> Edit Payout Method</button></section><section className="finance-panel settings-card"><h2>Payout Schedule</h2><label className="settings-field">Payout Frequency<select><option>Weekly</option><option>Monthly</option></select></label><label className="settings-field">Minimum Payout Amount<input value="Rs. 1,000" readOnly /></label><button type="button" className="finance-primary">Save Schedule</button></section></div><div className="settings-layout"><section className="finance-panel settings-card"><h2>Tax & Business Information</h2><label className="settings-field">Business Name<input value="Mirwal Store" readOnly /></label><label className="settings-field">Tax Registration Number<input value="NTN-1234567" readOnly /></label><button type="button" className="finance-link"><Icon name="pen" /> Edit Information</button></section><section className="finance-panel settings-card"><h2><Icon name="shield-halved" /> Security</h2><p className="settings-row"><span>Two-factor authentication</span><b>Enabled</b></p><p className="settings-row"><span>Email verification</span><b>Verified</b></p><button type="button" className="finance-link">Change Password</button></section></div><section className="finance-panel settings-card"><h2>Invoices & Statements</h2><p className="muted">Manage the email delivery and format of your financial documents.</p><div className="settings-row"><span>Email statements automatically</span><input type="checkbox" defaultChecked /></div><div className="settings-row"><span>Statement format</span><select><option>PDF</option><option>CSV</option></select></div></section></>
export default FinancePage
