import SellerLayout from '../SellerLayout'
import './returns-refunds.css'
import { navigateTo } from '../../navigation'
import Icon from '../../components/Icon'


const RequestDetails = ({ type = 'returns', requestId }) => {
  const displayRequestId = `#${requestId.replace(/^#/, '')}`
  const cancellation = type === 'cancellations'
  const request = cancellation
    ? { id: displayRequestId, order: '#MW1254868', customer: 'Ahmed Khan', email: 'ahmed.khan@example.com', product: 'Premium Running Shoes', reason: 'Ordered by mistake', amount: 'Rs. 3,199', status: 'Pending', icon: 'shoe-prints' }
    : { id: displayRequestId, order: '#MW1254876', customer: 'Ali Raza', email: 'ali.raza@example.com', product: 'Wireless Bluetooth Headphones', reason: 'Noise cancellation not working', amount: 'Rs. 2,199', status: 'Pending Review', icon: 'headphones' }
  return <SellerLayout activeItem={cancellation ? 'cancelled' : 'returns'} breadcrumbs={[{ label: 'Dashboard', onClick: () => navigateTo('/seller') }, { label: cancellation ? 'Cancellations' : 'Returns & Refunds', onClick: () => navigateTo(cancellation ? '/seller/orders/cancelled' : '/seller/orders/returns') }, { label: 'Details' }]}>
    <div className="request-details-page"><div className="request-details-header"><div><button type="button" className="back-link" onClick={() => navigateTo(cancellation ? '/seller/orders/cancelled' : '/seller/orders/returns')}><Icon name="arrow-left" /> Back to {cancellation ? 'Cancellations' : 'Returns & Refunds'}</button><h1>{cancellation ? 'Order Cancellation Details' : 'Return / Refund Details'}</h1><p>Request ID: {request.id} <em className={`request-status ${request.status.toLowerCase().replaceAll(' ', '-')}`}>{request.status}</em></p></div><button type="button" className="returns-export"><Icon name="print" /> Print</button></div><div className="request-detail-grid"><section className="detail-card"><h2>Order Information</h2><dl><dt>Request ID</dt><dd>{request.id}</dd><dt>Order ID</dt><dd>{request.order}</dd><dt>Request Date</dt><dd>May 24, 2025, 10:30 AM</dd><dt>Request Reason</dt><dd>{request.reason}</dd></dl></section><section className="detail-card"><h2>Product Information</h2><div className="detail-product"><span><Icon name={request.icon} /></span><div><strong>{request.product}</strong><small>SKU: MW-HP-001</small><p>Quantity: 1</p><p>{request.amount}</p></div></div></section><section className="detail-card"><h2>Request Summary</h2><dl><dt>Customer</dt><dd>{request.customer}</dd><dt>Email</dt><dd>{request.email}</dd><dt>Reason</dt><dd>{request.reason}</dd><dt>Refund Amount</dt><dd>{request.amount}</dd></dl></section><section className="detail-card detail-status"><h2>Request Status</h2><p><Icon name="circle-check" /> Request received</p><p className="current"><Icon name="clock" /> Under review</p><p><Icon name="circle-check" /> Approved</p><p><Icon name="circle" /> {cancellation ? 'Order Cancelled' : 'Product Received'}</p></section><section className="detail-card detail-wide"><h2>{cancellation ? 'Cancellation Information' : 'Refund Information'}</h2><p>{cancellation ? 'The customer requested cancellation before fulfillment. Review the request and take the appropriate action.' : 'Review the customer request and product condition before processing the refund.'}</p></section><section className="detail-card detail-wide"><h2>Next Action</h2><p>Please review the request and take action.</p><div className="detail-actions"><button type="button" className="approve">Approve Request</button><button type="button" className="reject">Reject Request</button></div></section></div></div>
  </SellerLayout>
}
export default RequestDetails
