import SellerLayout from '../SellerLayout'
import { sellerStats, dashboardOrders, topProducts } from '../../data/sellerMockData'
import Icon from '../../components/Icon'
import './dashboard.css'

const metrics = [['Total Sales', `Rs. ${sellerStats.totalSales.toLocaleString()}`, '+18.6%', 'bag-shopping'], ['Total Orders', '324', '+12.4%', 'clipboard-list'], ['Total Visitors', '12,540', '+9.8%', 'users'], ['Conversion Rate', '2.58%', '+0.6%', 'chart-line'], ['Store Rating', '4.8/5', '256 reviews', 'star']]

export default function SellerDashboard() {
  return <SellerLayout activeItem="dashboard" breadcrumbs={[{ label: 'Dashboard' }]}><div className="dashboard-container"><div className="dashboard-title-row"><div><h1>Dashboard</h1><p>Welcome back! Here's what's happening with your store today.</p></div><button type="button" className="dashboard-date"><Icon name="calendar" /> May 18 - May 24, 2025 <Icon name="chevron-down" /></button></div><div className="dashboard-metrics">{metrics.map(([label, value, change, icon]) => <article className="dashboard-metric" key={label}><div className="dashboard-metric-top"><span>{label}</span><i><Icon name={icon} /></i></div><strong>{value}</strong><small className="positive">{change} vs last 7 days</small></article>)}</div><div className="dashboard-columns"><section className="dashboard-panel sales-panel"><div className="dashboard-panel-heading"><h2>Sales Overview</h2><button type="button">Last 7 Days <Icon name="chevron-down" /></button></div><div className="chart-legend"><span className="sales-dot" /> Sales (Rs.) <span className="orders-dot" /> Orders</div><div className="sales-chart"><div className="chart-lines"><svg viewBox="0 0 700 150" preserveAspectRatio="none" aria-label="Sales and orders over the last seven days"><polyline className="sales-line" points="15,112 126,78 237,103 348,38 459,71 570,116 685,58" /><polyline className="orders-line" points="15,135 126,96 237,124 348,80 459,108 570,87 685,103" /></svg><div className="chart-labels">{['18 May', '19 May', '20 May', '21 May', '22 May', '23 May', '24 May'].map((day) => <span key={day}>{day}</span>)}</div></div></div></section><section className="dashboard-panel recent-panel"><div className="dashboard-panel-heading"><h2>Recent Orders</h2><button type="button">View all orders <Icon name="arrow-right" /></button></div>{dashboardOrders.map((order) => <div className="dashboard-order" key={order.id}><span className="order-avatar"><Icon name="headphones" /></span><div><b>Order {order.id}</b><small>May 24, 2025 · {order.time}</small></div><em className={order.status.toLowerCase()}>{order.status}</em><strong>Rs. {order.amount.toLocaleString()}</strong></div>)}</section></div><div className="dashboard-bottom"><section className="dashboard-panel top-products"><div className="dashboard-panel-heading"><h2>Top Selling Products</h2></div>{topProducts.map((product, index) => <div className="top-product" key={product.id}><b>{index + 1}</b><span className="product-avatar"><Icon name="headphones" /></span><div><strong>{product.name}</strong><small>Rs. {product.revenue.toLocaleString()}</small></div><small>Sold {product.sold}</small></div>)}</section></div></div></SellerLayout>
}
