import { useMemo, useState } from 'react'
import SellerLayout from '../SellerLayout'
import { navigateTo } from '../../navigation'
import './seller-notifications.css'

const seed = [{ id: 1, title: 'New order received', message: 'Order #MW1254876 needs your attention.', type: 'Orders', time: '10 minutes ago', unread: true }, { id: 2, title: 'Product approved', message: 'Wireless Headphones is now live.', type: 'Products', time: '1 hour ago', unread: true }, { id: 3, title: 'Payout processed', message: 'Your latest payout has been processed.', type: 'Payments', time: 'Yesterday', unread: false }, { id: 4, title: 'Promotion is ending soon', message: 'Your Summer Sale ends in two days.', type: 'Marketing', time: 'Yesterday', unread: false }]
const iconFor = (type) => type === 'Orders' ? 'box' : type === 'Products' ? 'cube' : type === 'Payments' ? 'wallet' : type === 'Marketing' ? 'bullhorn' : 'bell'

export default function SellerNotifications() {
  const [items, setItems] = useState(seed)
  const [filter, setFilter] = useState('All')
  const visible = useMemo(() => items.filter((item) => filter === 'All' || filter === 'Unread' && item.unread || item.type === filter), [items, filter])
  return <SellerLayout activeItem="notifications" breadcrumbs={[{ label: 'Dashboard', onClick: () => navigateTo('/seller') }, { label: 'Notifications' }]}><div className="seller-notifications-page"><div className="seller-notifications-header"><div><h1>Notifications</h1><p>Stay up to date with activity in your seller account.</p></div><button type="button" className="seller-primary-btn" onClick={() => setItems((current) => current.map((item) => ({ ...item, unread: false })))}>Mark all as read</button></div><div className="seller-notification-tabs">{['All', 'Unread', 'Orders', 'Products', 'Payments', 'Marketing', 'System'].map((tab) => <button type="button" className={filter === tab ? 'active' : ''} key={tab} onClick={() => setFilter(tab)}>{tab}</button>)}</div><section className="seller-notification-list">{visible.length ? visible.map((item) => <article className={`seller-notification-row ${item.unread ? 'unread' : ''}`} key={item.id}><span className="seller-notification-icon"><i className={`fa-solid fa-${iconFor(item.type)}`} /></span><div><strong>{item.title}</strong><p>{item.message}</p><small>{item.type} · {item.time}</small></div><div className="seller-notification-actions"><button type="button" onClick={() => setItems((current) => current.map((notification) => notification.id === item.id ? { ...notification, unread: !notification.unread } : notification))}>{item.unread ? 'Mark as read' : 'Mark unread'}</button><button type="button" aria-label={`Delete ${item.title}`} onClick={() => setItems((current) => current.filter((notification) => notification.id !== item.id))}><i className="fa-solid fa-trash" /></button></div></article>) : <div className="seller-notifications-empty"><i className="fa-regular fa-bell-slash" /><h2>No notifications</h2><p>You're all caught up.</p></div>}</section></div></SellerLayout>
}
