import { navigateTo } from '@mirwal/shared/navigation'
import './about-us.css'
import aboutBanner from './assets/images/about-banner.webp'
import aboutVideoThumbnail from './assets/images/about-video-thumbnail.webp'

const FaIcon = ({ name }) => <i className={`fa-solid fa-${name}`} aria-hidden="true" />

const values = [['bullseye', 'Our Mission', 'To make shopping simple, smart and reliable for everyone.'], ['eye', 'Our Vision', 'To become Pakistan’s most trusted smart shopping platform.'], ['gem', 'Our Values', 'Trust  •  Quality  •  Customer First']]
const benefits = [['cart-shopping', 'Wide Range', 'Thousands of products across top categories'], ['scale-balanced', 'Compare & Choose', 'Make informed decisions'], ['shield-halved', 'Secure Shopping', 'Your data and payments are safe'], ['truck-fast', 'Fast Delivery', 'Get your orders quickly'], ['headset', '24/7 Support', "We're always here for you"], ['heart', 'Customer Happiness', 'Your satisfaction is our success']]
const team = []
const milestones = [['2022', 'The Beginning', 'Mirwal was founded with a clear vision.'], ['2023', 'Growing Trust', 'More customers, more choices.'], ['2024', 'Smarter Shopping', 'AI-powered recommendations.'], ['2025', 'A Better Tomorrow', 'Expanding range and service for you.']]

export default function AboutUsPage() {
  return <main className="about-page">
    <section className="about-hero container"><div className="about-hero-copy"><span className="about-kicker">About Mirwal</span><h1>Smarter Shopping,<br /><em>Happier Living.</em></h1><p>Mirwal connects you with the right products, trusted brands and smart choices — making everyday life simpler.</p></div><img className="about-hero-image" src={aboutBanner} alt="Mirwal home and lifestyle products" /></section>
    <section className="about-story container"><div className="story-image"><img src={aboutVideoThumbnail} alt="Customers shopping together on a laptop" /><button type="button" aria-label="Play our story video"><FaIcon name="play" /></button></div><div className="story-copy"><span className="about-kicker">Our Story</span><h2>A Marketplace Built for You</h2><p>Mirwal started with a simple idea — to make online shopping and product discovery smarter, easier and more trustworthy. We bring together top products, trusted brands and smart buying insights so you can find the right solution without wasting time.</p><div className="story-pills"><span><FaIcon name="scale-balanced" /> Smart Choices</span><span><FaIcon name="shield-halved" /> Trusted Brands</span><span><FaIcon name="truck" /> Better Living</span></div></div></section>
    <section className="about-values container">{values.map(([icon, title, copy]) => <article key={title}><span className="about-icon"><FaIcon name={icon} /></span><div><h3>{title}</h3><p>{copy}</p></div></article>)}</section>
    <section className="about-benefits container"><div className="benefits-copy"><h2>Why Choose <em>Mirwal?</em></h2><p>We don’t just show products — we help you find the right one.</p>{['Smart Product Recommendations', 'Honest Reviews & Comparisons', 'Quality You Can Trust', 'A Better Shopping Experience'].map((item) => <span key={item}><FaIcon name="check" /> {item}</span>)}<button type="button" onClick={() => navigateTo('/explore')}>Explore Our Products <FaIcon name="arrow-right" /></button></div><div className="about-benefit-grid">{benefits.map(([icon, title, copy]) => <article key={title}><span className="about-icon"><FaIcon name={icon} /></span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
    <section className="about-stats container"><div><FaIcon name="cart-shopping" /><strong>500K+<small>Happy Customers</small></strong></div><div><FaIcon name="box" /><strong>2M+<small>Products Listed</small></strong></div><div><FaIcon name="store" /><strong>2,000+<small>Trusted Stores</small></strong></div><div><FaIcon name="star" /><strong>98%<small>Customer Satisfaction</small></strong></div></section>
    <section className="about-team-journey container">{team.length > 0 && <div className="team-block"><h2>Meet Our Team</h2><p>Passionate people building a smarter shopping experience.</p><div className="team-grid">{team.map(([image, name, role]) => <article key={name}><img className="team-avatar" src={image} alt={name} /><b>{name}</b><small>{role}</small></article>)}</div></div>}<div className="journey-block"><h2>Our Journey</h2><div>{milestones.map(([year, title, copy]) => <article key={year}><b>{year}</b><span><strong>{title}</strong><small>{copy}</small></span></article>)}</div></div></section>
    <section className="about-testimonial container"><FaIcon name="quote-left" /><div><p>“Mirwal makes online shopping so easy and reliable. I always find the right product with smart recommendations.”</p><b>— Ahmed Khan, Lahore</b></div><span><FaIcon name="chevron-left" /><FaIcon name="chevron-right" /></span></section>
    <section className="about-cta container"><div><h2>Ready to Shop Smarter?</h2><p>Discover better products. Compare. Choose. Enjoy.</p></div><button type="button" onClick={() => navigateTo('/explore')}>Start Shopping Now <FaIcon name="arrow-right" /></button></section>
  </main>
}