import { useEffect, useState } from 'react'
import Header from './components/Header'
import Footer from './components/Footer'
import './content-page.css'

const Icon = ({ name }) => <i className={`fa-solid fa-${name}`} aria-hidden="true" />
const content = {
  contact: { title: 'Contact Mirwal', intro: 'Have a question about shopping, an order or a seller? Our support team is ready to help.', icon: 'headset', sections: [['Email support', 'Send order and account questions to support@mirwal.com. We aim to reply within one business day.'], ['Marketplace support', 'For product or seller questions, include the product link or order ID so we can route your request correctly.'], ['Support hours', 'Support is available every day from 9 AM to 9 PM Pakistan Standard Time.']] },
  faq: { title: 'Frequently asked questions', intro: 'Clear answers to common questions about shopping on Mirwal.', icon: 'circle-question', sections: [['How do I find a product?', 'Search by product, brand or category, then refine the results by price, rating and other available details.'], ['How can I compare products?', 'Use the Compare control on product cards or product pages. You can review up to four products side by side.'], ['How do I track an order?', 'Open Track Orders from your account and enter the order ID from your confirmation.'], ['How do returns work?', 'Return eligibility depends on the product and seller terms. Review the return information on the product page before ordering.'], ['How do I contact a seller?', 'Open the product or seller page and use the available seller or support contact path.']] },
  shipping: { title: 'Shipping information', intro: 'Delivery options and timing depend on the seller, product and delivery location.', icon: 'truck', sections: [['Delivery options', 'Available delivery methods and charges are shown during checkout when shipping services are connected.'], ['Delivery locations', 'Mirwal is designed for shopping across Pakistan. Coverage and timing can vary by seller and city.'], ['Delivery updates', 'Use your order ID to check the latest status once an order has been created.'], ['Before you order', 'Check the product page for seller-specific delivery estimates, exclusions and requirements.']] },
  returns: { title: 'Returns and refunds', intro: 'Understand the steps to request a return and follow its progress.', icon: 'rotate-left', sections: [['Eligibility', 'Return eligibility, time limits and product condition requirements are defined by the seller and shown with the product information.'], ['Starting a return', 'Keep your order ID, product packaging and supporting details ready when contacting support.'], ['Refunds', 'Refund timing depends on the payment method and the outcome of the return review. Mirwal does not claim a refund until the relevant service confirms it.']] },
  privacy: { title: 'Privacy policy', intro: 'This page explains the principles Mirwal uses to protect account and shopping information.', icon: 'shield-halved', legal: true, sections: [['Information we use', 'We use information needed to provide accounts, shopping, order support and marketplace operations.'], ['Your choices', 'You can review account preferences and contact support about questions concerning your information.'], ['Data protection', 'Payment credentials should be handled by the connected payment provider. Do not share sensitive credentials with support.']] },
  terms: { title: 'Terms and conditions', intro: 'These terms describe the basic rules for using the Mirwal marketplace.', icon: 'file-contract', legal: true, sections: [['Marketplace role', 'Mirwal provides a marketplace experience. Product details, fulfilment and seller obligations may depend on the relevant seller and service.'], ['Using the service', 'Provide accurate account and delivery information, respect other users and use the marketplace lawfully.'], ['Changes', 'Terms may be updated as the marketplace and its services evolve. The latest published version applies to future use.']] },
}
export default function ContentPage({ page = 'faq' }) {
  const data = content[page] || content.faq
  const [open, setOpen] = useState(0)
  useEffect(() => { document.title = `${data.title} | Mirwal`; let meta = document.querySelector('meta[name="description"]'); if (!meta) { meta = document.createElement('meta'); meta.name = 'description'; document.head.appendChild(meta) }; meta.setAttribute('content', data.intro); if (data.legal) { let robots = document.querySelector('meta[name="robots"]'); if (!robots) { robots = document.createElement('meta'); robots.name = 'robots'; document.head.appendChild(robots) }; robots.setAttribute('content', 'noindex,follow') } }, [data])
  return <><Header /><main className="content-page"><div className="content-page-container"><nav aria-label="Breadcrumb"><a href="/">Home</a><Icon name="chevron-right" /><span aria-current="page">{data.title}</span></nav><header className="content-page-header"><span><Icon name={data.icon} /></span><div><h1>{data.title}</h1><p>{data.intro}</p></div></header><section className="content-page-body" aria-label={data.title}>{data.sections.map(([title, copy], index) => <article key={title}><button type="button" aria-expanded={open === index} onClick={() => setOpen(open === index ? -1 : index)}><strong>{title}</strong><Icon name="chevron-down" /></button>{open === index && <p>{copy}</p>}</article>)}</section>{page === 'contact' && <section className="content-page-contact"><Icon name="envelope" /><div><h2>Need help with an order?</h2><p>Include your order ID and product details when you email support.</p></div><a href="mailto:support@mirwal.com">Email support</a></section>}<div className="content-page-links"><a href="/help-center">Help Center</a><a href="/guides">Shopping guides</a><a href="/explore">Explore products</a></div></div></main><Footer /></>
}
