import { useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { EmptyState } from '@mirwal/shared/PageStates'
import SEOHead from './components/SEOHead'
import { termsLastUpdated, termsNotice, termsSections } from './data/termsContent'
import './trust-pages.css'

const Icon = ({ name }) => <i className={`fa-solid fa-${name}`} aria-hidden="true" />
const commonFaqs = [['What should I check before ordering?', 'Review the product details, seller information, price, delivery terms and return information shown for the item.'], ['How can I report a problem?', 'Use the reporting form on this site and include only the product, seller or order reference needed to investigate.'], ['How does AI Shopping help?', 'You can describe a need in plain language, refine the requirements, and compare relevant catalogue options when the AI service is connected.']]
const pageData = {
  contact: { title: 'Contact & Support', intro: 'Choose the right support path for a shopping, order, seller or account question.', icon: 'headset', highlights: [['01', 'Shopping help', 'Include the product or category context needed to understand your question.'], ['02', 'Order help', 'Keep your verified order reference available for support.'], ['03', 'Safety concerns', 'Use the reporting flow for suspicious sellers, listings or activity.']], sections: [['Contact configuration', 'Support email, phone, WhatsApp, hours and ticket delivery are configurable and should be populated from the production support system. The frontend does not claim an active channel that is not configured.'], ['Before contacting support', 'Do not include passwords, payment credentials or one-time codes. Share only the minimum information needed to investigate.']] },
  faq: { title: 'Frequently Asked Questions', intro: 'Clear, configurable answers to common questions about shopping on Mirwal.', icon: 'circle-question', sections: [['Shopping', 'Search by product, brand or category, then use available filters and comparison tools to evaluate options.'], ['Orders and payments', 'Order creation, payment confirmation and tracking depend on connected backend services. The site should show success only after those services respond.'], ['Returns and delivery', 'Eligibility, timelines and delivery estimates depend on the applicable seller and configured marketplace policies.']] },
  privacy: { title: 'Privacy Policy', intro: 'A structured place for Mirwal’s final privacy policy and data-use details.', icon: 'shield-halved', legal: true, sections: [['Information collected', 'The final policy should describe only the account, shopping, support and technical information actually processed by Mirwal.'], ['How information is used', 'Describe the purposes and retention rules configured for the production application.'], ['Your choices', 'Add the final access, correction, deletion and contact procedures once the legal policy is approved.']] },
  terms: { title: 'Terms & Conditions', intro: 'The terms governing access to and use of the Mirwal marketplace and its services.', icon: 'file-contract', legal: true, lastUpdated: termsLastUpdated, notice: termsNotice, sections: termsSections },
  shipping: { title: 'Shipping & Delivery', intro: 'Review delivery information that should be confirmed before placing an order.', icon: 'truck', highlights: [['01', 'Seller and product', 'Delivery availability and estimates can vary by seller, product and destination.'], ['02', 'Checkout review', 'Confirm address, method and charge before submitting an order.'], ['03', 'Delivery support', 'Keep order and tracking references for delivery questions or incidents.']], sections: [['Shipping policy', 'Delivery areas, estimates, failed delivery handling and damage claims must come from the configured seller and logistics policies. No fixed timeline is promised here.'], ['Delivery issues', 'Keep relevant packaging and order details, then use the configured support or reporting route.']] },
  'how-mirwal-works': { title: 'How Mirwal Works', intro: 'A clearer path from a shopping need to a considered purchase.', icon: 'route', highlights: [['01', 'Tell us what you need', 'Search normally or describe your goal in your own words.'], ['02', 'Refine the options', 'Use category, price, rating and other available product details.'], ['03', 'Compare and decide', 'Put options side by side before choosing a product and seller.']], sections: [['Start with a need', 'Mirwal is designed to help when you know the problem you want to solve, even when you do not know the exact product name.'], ['Search or use AI Shopping', 'Normal search and the AI Shopping interface are separate entry points. AI recommendations should be treated as available only when the connected service returns them.'], ['Choose with context', 'Product information, seller details, ratings and comparison tools are presented together to support your decision.']] },
  'buyer-protection': { title: 'Buyer Protection', intro: 'Useful information and support paths for shopping with more confidence.', icon: 'shield-halved', highlights: [['01', 'Clear product information', 'Review visible specifications, price, ratings and availability before ordering.'], ['02', 'Seller context', 'Check the seller identity and marketplace information shown on the product page.'], ['03', 'Support and reporting', 'Keep your order or product reference when you need help or want to report a concern.']], sections: [['What Mirwal provides', 'Mirwal brings discovery, comparison and marketplace context together. Specific returns, refunds, delivery and dispute outcomes depend on the applicable seller and connected services.'], ['Before checkout', 'Check the final order details, delivery information and payment option presented at checkout. Do not rely on an offer or promise that is not displayed in the current marketplace flow.']] },
  'safe-shopping': { title: 'Safe & Secure Shopping', intro: 'Practical habits for protecting your account and making informed marketplace decisions.', icon: 'lock', highlights: [['01', 'Protect your account', 'Use a unique password and never share credentials or one-time codes.'], ['02', 'Keep communication careful', 'Treat unexpected payment requests or links as suspicious.'], ['03', 'Report concerns', 'Use the reporting flow when a listing, seller or message does not look right.']], sections: [['How to stay safe', 'Keep contact and payment information inside the intended checkout and support flows. Verify product and seller details, avoid sharing passwords, and save order references for support.'], ['If something feels wrong', 'Stop the interaction, do not send additional money or credentials, and report the product, seller or activity with the minimum useful details.']] },
  'seller-verification': { title: 'Seller Verification', intro: 'How to read seller information and trust indicators without relying on unsupported claims.', icon: 'store', highlights: [['01', 'Review seller identity', 'Check the seller name, marketplace profile and available catalogue context.'], ['02', 'Read the signals', 'Ratings, reviews and visible store information can help you assess an offer.'], ['03', 'Report concerns', 'Flag suspicious or misleading seller behaviour for review.']], sections: [['Verification information', 'The exact seller onboarding and verification rules are configurable business policy. This page will reflect the final process once it is implemented by the marketplace backend.'], ['What customers should check', 'Consider seller history, product detail quality, ratings, delivery terms and return information together rather than relying on a single badge.']] },
  'seller-protection': { title: 'Seller Protection', intro: 'A practical overview of seller account, order and support considerations.', icon: 'store', highlights: [['01', 'Protect access', 'Keep seller credentials and account recovery details private.'], ['02', 'Keep records', 'Use clear product, order, delivery and return information.'], ['03', 'Ask for support', 'Use the seller support route for issues that need marketplace attention.']], sections: [['Seller responsibilities', 'Sellers should provide accurate catalogue information and follow the marketplace policies configured for their account. Final seller protections and dispute rules require backend policy configuration.'], ['Resolving issues', 'Keep relevant order and customer communication records and use the official support path rather than sharing sensitive information publicly.']] },
  'payment-security': { title: 'Payments & Security', intro: 'Understand the payment step and the information Mirwal can safely present today.', icon: 'credit-card', highlights: [['01', 'Review the total', 'Confirm items, delivery, discounts and the final total before submitting an order.'], ['02', 'Use the shown method', 'Only payment methods returned by the configured checkout service should be offered.'], ['03', 'Never share credentials', 'Mirwal will not ask for passwords, card PINs or one-time codes in page content.']], sections: [['Payment availability', 'Payment methods, gateway responses and refund handling are dynamically configurable. No payment method or security certification is claimed on this page until the relevant integration is active.'], ['Payment support', 'For a payment concern, keep the order or transaction reference and contact the configured support channel. Do not include full card numbers or authentication codes.']] },
  'returns-refunds': { title: 'Returns & Refunds', intro: 'A clear place to review return and refund information without implying rules that are not configured.', icon: 'rotate-left', highlights: [['01', 'Check eligibility', 'Return eligibility and exclusions depend on the applicable product and seller policy.'], ['02', 'Keep the order reference', 'Support needs an order or product reference to investigate a request.'], ['03', 'Wait for confirmation', 'A refund should only be treated as complete after the connected service confirms it.']], sections: [['Return policy', 'Eligibility, condition requirements, timelines and non-returnable products are configurable policy data. They should be populated from the backend before being presented as final rules.'], ['Refund process', 'Refund timing and payment reversals depend on the connected payment service and the outcome of the return review.']] },
  'order-tracking': { title: 'Order Tracking', intro: 'Enter an order reference to check its status when order tracking is connected.', icon: 'truck-fast', tracking: true, sections: [['Tracking status', 'Order statuses must come from the authenticated order service. This interface does not invent a status or order ID.']] },
  cookies: { title: 'Cookie Policy', intro: 'A configurable explanation of cookies used by the Mirwal application.', icon: 'cookie-bite', legal: true, sections: [['What cookies are', 'Cookies are small pieces of data stored by a browser. The final policy should list only cookies actually used by Mirwal.'], ['How they may be used', 'Essential session, preference or analytics cookies should be documented here only after the production stack is finalized.'], ['Managing cookies', 'Browser settings can usually control cookies. Any Mirwal-specific preference control should be connected to the active analytics and consent configuration.']] },
  'trust-safety': { title: 'Shop with Confidence on Mirwal', intro: 'Discover, verify, compare, decide and shop with better context.', icon: 'shield-heart', highlights: [['01', 'Discover', 'Start with a product, category or shopping need.'], ['02', 'Verify', 'Read visible product and seller information.'], ['03', 'Compare', 'Review prices, ratings and useful differences.'], ['04', 'Decide', 'Choose based on the details that matter to you.']], sections: [['A transparent marketplace experience', 'Mirwal is designed to make product discovery and comparison easier. Seller obligations, payment security, delivery, returns and dispute outcomes remain governed by the final connected marketplace policies.'], ['Stay informed', 'Use the information visible on the product and checkout flows, protect your account, and report suspicious listings or activity when needed.']] },
}

const extendedSections = {
  contact: [['Choose the right support path', 'For a product question, include the product link or product reference. For an order question, include the authenticated order reference. For a seller or safety concern, identify the listing or store and describe what you observed. Do not send passwords, one-time codes or full payment details.'], ['Support channels and availability', 'Email, phone, WhatsApp, support hours and ticket response targets are configurable business details. They should be populated from the production support system before being presented as active promises.'], ['What happens next', 'A configured support service should acknowledge the request, associate it with the relevant entity and provide a status or response path. Until that service is connected, the frontend does not claim that a message was delivered or a case was created.']],
  faq: [['General shopping questions', 'Mirwal helps users discover products, browse categories and compare available product information. Seller fulfilment, delivery, returns and payment outcomes depend on the relevant seller and connected services.'], ['AI Shopping questions', 'AI Shopping is designed for needs expressed in plain language. It should ask clarifying questions and return results only through the configured AI and catalogue services; the interface does not claim recommendations are generated when that service is unavailable.'], ['Orders, payments and returns', 'Order success, payment success, tracking and refunds must come from verified backend responses. Return eligibility, delivery estimates and payment methods are configurable policy data and should be reviewed at the point of purchase.']],
  privacy: [['Scope of this policy', 'This page provides a structured location for the approved Mirwal privacy policy. Its final wording should reflect the actual production application, vendors, storage, retention periods, account flows and legal requirements that apply to the service.'], ['Account and marketplace information', 'The production policy should explain what information is collected when people browse, create an account, contact support, use comparison features, place orders or interact with sellers. Only information required for a stated purpose should be requested.'], ['Security and retention', 'The final policy should explain retention, access controls, incident handling and user choices without claiming technical controls that have not been implemented. Payment credentials should remain with the configured payment provider where applicable.'], ['Contact and updates', 'Add the approved privacy contact and effective date here once they are configured. Changes should be dated and communicated through the production policy process.']],
  terms: [['Using the marketplace', 'The final terms should explain how customers, sellers and Mirwal interact, including acceptable use, account responsibilities and the role of product and seller information in a marketplace listing.'], ['Products, sellers and orders', 'The approved terms should define listing accuracy, seller obligations, order creation, fulfilment, payment, delivery, returns and dispute handling. The frontend intentionally does not present placeholder text as a final legal agreement.'], ['User responsibilities', 'Users should provide accurate information, protect account access, avoid misuse, respect other participants and use reporting channels for concerns. Specific prohibited activities and consequences belong in the approved policy.'], ['Effective date and contact', 'Populate the final effective date, governing terms and approved legal contact before publishing this page as binding policy content.']],
  'how-mirwal-works': [['From discovery to decision', 'Start with a product name, a category, a budget or a problem. Mirwal brings the relevant catalogue context into one place so you can move from a broad search to a manageable shortlist. Use the information that is visible on each result, open the product detail page for more context, and compare options when the differences matter.'], ['A marketplace, not a single retailer', 'Mirwal helps you discover products offered through marketplace sellers. Availability, fulfilment, seller terms and final purchase conditions can vary. The seller and checkout information shown for the selected item should be treated as the source of truth for that order.'], ['When AI Shopping is useful', 'AI Shopping is intended for needs that are easier to describe than to name, such as finding a laptop for study and gaming. It should ask or process only through the connected AI service and should never be treated as a substitute for reviewing the underlying product and seller information.']],
  'buyer-protection': [['Make an informed choice', 'Buyer confidence begins with useful information. Before ordering, review the product title, images, specifications, price, rating, seller context, delivery information and return terms that are actually displayed. If important information is missing or unclear, pause and ask support or report the listing rather than assuming a promise.'], ['After placing an order', 'Keep the order reference, the final order summary and relevant seller details. These records help distinguish a product question, delivery issue, return request or payment concern. Order confirmation and status should only be trusted when returned by the authenticated order service.'], ['Concerns and disputes', 'If a listing or seller appears misleading, use the reporting flow with a concise description and the relevant reference. The final review, escalation and dispute process is configurable marketplace policy and must be supplied by the production backend before being described as a guarantee.']],
  'safe-shopping': [['Protect your account', 'Use a unique password, sign out on shared devices, and keep recovery information current. Never share a password, card PIN, one-time code or account token with a person claiming to be a seller or support representative.'], ['Recognise suspicious requests', 'Be careful with urgent requests to move a conversation off the marketplace, pay through an unapproved channel, or open an unexpected link. Check the product and seller page directly rather than using a link sent in a message.'], ['Report and preserve evidence', 'Stop a suspicious interaction, save the relevant product or seller reference, and submit a report with only the details needed to investigate. Do not upload passwords, full payment credentials or unnecessary identity documents.']],
  'seller-verification': [['Why seller information matters', 'A seller profile gives customers context for the offer they are considering. Name, catalogue, ratings, reviews, delivery information and visible store details should be read together. A badge alone should not be treated as proof of product authenticity or a guaranteed outcome.'], ['Configurable verification process', 'Seller onboarding, identity checks, business checks, approval rules and ongoing review are business and backend capabilities. This page is deliberately structured so the approved process can be inserted when those capabilities are implemented.'], ['What customers can do today', 'Review the seller page, compare similar offers, check product information and report suspicious or misleading activity. Include a clear reference so the marketplace team can locate the relevant listing or seller.']],
  'seller-protection': [['Operate from the official account', 'Keep seller access, recovery details and customer information private. Use the seller dashboard and configured support paths for orders, returns, product updates and marketplace questions.'], ['Communicate clearly', 'Accurate product descriptions, images, pricing, delivery information and return terms help customers make informed choices and reduce avoidable disputes. Keep changes consistent across the listing and order flow.'], ['Policy still governs outcomes', 'Seller support, payment settlement, dispute handling, returns and account protections depend on the final marketplace agreement and backend capabilities. This page does not create guarantees that have not been approved or implemented.']],
  'payment-security': [['Before you pay', 'Check the items, quantities, delivery address, delivery method, discounts and final total in the checkout review. Use only payment methods presented by the configured checkout service. If a seller asks for a different payment route, stop and report the request.'], ['Sensitive information', 'Never provide passwords, card PINs, one-time codes or full card details in a support message, product review or report. A transaction reference is usually more useful and exposes less sensitive information.'], ['Payment and refund status', 'A payment is not successful merely because a button was clicked or the browser navigated. The connected payment and order services must confirm the result. Refunds likewise require confirmation from the applicable service.']],
  shipping: [['How delivery information should work', 'Delivery availability and estimates may depend on the seller, item, destination, inventory and logistics service. The final checkout flow should calculate and display the applicable method and charge before an order is submitted.'], ['Preparing for delivery', 'Use an address where the delivery can be received and check the contact details before confirming. Keep the order reference and final summary so a delivery question can be connected to the correct purchase.'], ['Problems with a shipment', 'For a missing, damaged, incorrect or failed delivery, preserve relevant packaging and order details and use the configured support route. The final resolution, timelines and eligibility rules must come from the approved shipping policy.']],
  'returns-refunds': [['Start with the product policy', 'Return eligibility can vary by product, condition, seller and reason for return. Read the return information presented with the item before ordering, and keep the original packaging and accessories when a return may be needed.'], ['Requesting a return', 'Use the authenticated order reference and describe the issue accurately. Include photographs or other evidence only when the configured support process requests them, and remove unrelated personal or payment information.'], ['Refund confirmation', 'A refund should not be considered complete because a request was submitted. The seller, marketplace and payment service must confirm the applicable decision and payment reversal. Final timing and exclusions remain configurable policy data.']],
  'order-tracking': [['Use a real reference', 'Enter the order ID or tracking number returned by the authenticated order service. Mirwal should never generate an order ID in the browser or show a delivery status based only on local storage or navigation.'], ['What a verified timeline may contain', 'When the backend supports it, a timeline can show confirmed, processing, shipped, out for delivery and delivered events. Each event should be returned by the order or logistics service with its own timestamp and meaning.'], ['If a result is unavailable', 'An unavailable result does not mean an order failed or succeeded. Check the reference, then use the configured support channel. The current frontend keeps this state explicit until the tracking API is connected.']],
  cookies: [['Essential storage', 'Some browser storage may be needed for preferences or a temporary shopping session. The final cookie inventory should be generated from the production application and should name each essential item and its purpose.'], ['Analytics and preferences', 'Analytics, experimentation and preference technologies should be listed only after the final tools and consent requirements are known. Mirwal should not imply that a tool is active when it is not configured.'], ['Managing browser data', 'You can manage cookies and site data through browser controls. Any Mirwal consent or preference control should be connected to the actual analytics and privacy configuration before it is presented as a complete choice.']],
  'trust-safety': [['A practical trust framework', 'Discover a relevant option, verify the visible product and seller context, compare meaningful differences, decide using the information that fits your needs, and shop through the intended checkout flow. This framework supports awareness; it is not a promise that every marketplace risk has been eliminated.'], ['Shared responsibility', 'Mirwal can make information easier to find, but customers should still review listings, sellers, delivery terms and payment prompts. Sellers are responsible for accurate marketplace information within the policies that govern their accounts.'], ['Improve the marketplace', 'Clear reports help identify misleading information, suspicious activity and broken experiences. Submit the relevant reference and a concise explanation, and avoid including passwords, full payment details or unnecessary personal information.']],
}

function TrustPage({ pageKey }) {
  const data = pageData[pageKey]
  const [open, setOpen] = useState(0)
  if (!data) return null
  const sections = pageKey === 'terms' ? data.sections : [...(extendedSections[pageKey] || []), ...data.sections]
  return <main className="trust-page"><SEOHead title={`${data.title} | Mirwal`} description={data.intro} canonical={`${window.location.origin}/${pageKey}`} robots={data.legal ? 'noindex,follow' : 'index,follow'} /><div className="trust-container"><nav className="trust-breadcrumb" aria-label="Breadcrumb"><Link to="/">Home</Link><Icon name="chevron-right" /><span aria-current="page">{data.title}</span></nav><header className="trust-hero"><div><span className="trust-kicker"><Icon name={data.icon} /> MIRWAL TRUST &amp; SAFETY</span><h1>{data.title}</h1><p>{data.intro}</p>{data.lastUpdated && <small className="trust-last-updated">Last updated: {data.lastUpdated}</small>}</div><div className="trust-hero-mark" aria-hidden="true"><Icon name={data.icon} /></div></header>{data.highlights && <section className="trust-highlights">{data.highlights.map(([number, title, copy]) => <article key={title}><b>{number}</b><div><h2>{title}</h2><p>{copy}</p></div></article>)}</section>}{data.tracking ? <TrackingState /> : <section className="trust-content">{sections.map(([title, copy], index) => <article key={`${title}-${index}`}><h2>{index + 1}. {title}</h2><p>{copy}</p></article>)}</section>}{data.notice && <aside className="trust-policy-notice"><Icon name="triangle-exclamation" /><p>{data.notice}</p></aside>}<section className="trust-faq"><div className="trust-section-heading"><span className="trust-kicker">COMMON QUESTIONS</span><h2>Helpful answers</h2></div>{commonFaqs.map(([question, answer], index) => <details key={question} open={open === index} onClick={(event) => { event.preventDefault(); setOpen(open === index ? -1 : index) }}><summary>{question}<Icon name="chevron-down" /></summary>{open === index && <p>{answer}</p>}</details>)}</section><TrustLinks /></div></main>
}

/**
 * Public order tracking.
 *
 * There is deliberately no anonymous lookup here. An order number plus nothing else would let
 * anyone who guesses or overhears a reference read a stranger's delivery address — the exact
 * enumeration problem the rest of the API is careful to avoid. Tracking is behind sign-in
 * instead, and this says so and sends you there rather than presenting a search box that
 * cannot honestly work.
 */
function TrackingState() {
  return (
    <section className="tracking-panel">
      <h2>Track an order</h2>
      <p>
        Your deliveries are on your account, so nobody else can see where your parcel is going. Sign in and
        every item you have ordered shows its current stage.
      </p>
      <EmptyState
        type="tracking"
        size="small"
        title="Tracking lives in your account"
        description="An order number on its own is not proof it is your order — anyone who saw it could read your delivery address. Signing in is what keeps that private."
        primaryAction={{ label: 'Sign in to track', href: '/login' }}
        secondaryAction={{ label: 'Visit help center', href: '/help-center' }}
      />
    </section>
  )
}

function TrustLinks() {
  return <nav className="trust-links" aria-label="Trust and support links"><Link to="/buyer-protection">Buyer Protection</Link><Link to="/safe-shopping">Safe Shopping</Link><Link to="/payment-security">Payment Security</Link><Link to="/contact">Contact Support</Link><Link to="/categories">Explore Categories</Link></nav>
}

export function TrustRoute({ pageKey: routePageKey }) {
  const { pageKey } = useParams()
  return <TrustPage pageKey={routePageKey || pageKey} />
}

export function ReportPage() {
  const [sent, setSent] = useState(false)
  return <main className="trust-page"><div className="trust-container"><nav className="trust-breadcrumb" aria-label="Breadcrumb"><Link to="/">Home</Link><Icon name="chevron-right" /><span>Report a problem</span></nav><header className="trust-hero"><div><span className="trust-kicker"><Icon name="flag" /> TRUST &amp; SAFETY</span><h1>Report a problem</h1><p>Tell Mirwal about a product, seller, order, payment or website concern.</p></div><div className="trust-hero-mark"><Icon name="flag" /></div></header>{sent ? <EmptyState type="report" size="small" title="Report form ready for backend delivery" description="The form was validated locally, but no report was sent because the reporting service is not configured." primaryAction={{ label: 'Return to trust & safety', href: '/trust-safety' }} /> : <form className="report-form" onSubmit={(event) => { event.preventDefault(); setSent(true) }}><label>Report type<select required><option value="">Choose a report type</option><option>Product problem</option><option>Seller problem</option><option>Order problem</option><option>Payment problem</option><option>Suspicious activity</option><option>Website problem</option><option>Other</option></select></label><label>Reference (optional)<input placeholder="Product, seller or order reference" /></label><label>Description<textarea required minLength="20" placeholder="Describe only the details needed to investigate." /></label><label>Contact email (optional)<input type="email" placeholder="you@example.com" /></label><button type="submit"><Icon name="paper-plane" /> Submit report</button></form>}</div></main>
}