import { useLocation } from 'react-router-dom'
import { navigateTo } from '../navigation'
import AdminLayout from './AdminLayout'
import Icon from '../components/Icon'
import './tax-commission.css'

const tabs = [['Overview', 'overview'], ['Tax Rules', 'rules'], ['Tax Classes', 'classes'], ['Tax Rates', 'rates'], ['Commission Rules', 'commission'], ['Commission Plans', 'plans'], ['Payout Settings', 'payout'], ['Reports', 'reports'], ['Exemptions', 'exemptions']]
const rules = [['Standard Sales Tax', 'Standard Goods', '1', 'Active', 'All Products'], ['Digital Services Tax', 'Digital Services', '2', 'Active', 'Digital Products'], ['Luxury Tax', 'Luxury Goods', '3', 'Active', 'Luxury Category'], ['Reduced Rate Tax', 'Reduced Rate', '4', 'Active', 'Selected Categories'], ['Import Duty', 'Imported Goods', '5', 'Inactive', 'Imported Products']]
const classes = [['Standard Goods', 'Standard taxable goods', '12%', 'Active'], ['Digital Services', 'Digital products & services', '18%', 'Active'], ['Luxury Goods', 'Luxury goods and premium items', '20%', 'Active'], ['Reduced Rate', 'Tax exempt eligible items', '0%', 'Active'], ['Imported Goods', 'Imported products', '15%', 'Active']]
const rates = [['Sales Tax - PK', 'Standard Goods', '17.00', 'Pakistan', 'Active'], ['Sales Tax - EU', 'Standard Goods', '20.00', 'European Union', 'Active'], ['Service Tax - PK', 'Digital Services', '16.00', 'Pakistan', 'Active'], ['Luxury Tax - PK', 'Luxury Goods', '20.00', 'Pakistan', 'Active'], ['Reduced Rate - PK', 'Reduced Rate', '0.00', 'Pakistan', 'Active']]
const plans = [['Plan for Merchants', 'Customer', 'Government Organizations', 'Dec 31, 2025', 'Active'], ['Premium Plan', 'Vendor', 'Export Products', 'Dec 31, 2025', 'Active'], ['Category Based Plan', 'Customer', 'Registered Customers', 'Dec 31, 2025', 'Active'], ['Volume Based Plan', 'Seller', 'Educational Institutions', 'Dec 31, 2025', 'Active']]
function Panel({ title, children }) { return <section className="tax-panel"><h2>{title}</h2>{children}</section> }
function Status({ value = 'Active' }) { return <span className={`tax-status ${value.toLowerCase()}`}>{value}</span> }
function Kpis({ items }) { return <div className="tax-kpis">{items.map(([label, value, change, icon], index) => <article key={label}><span className={`tone-${index}`}><Icon name={icon} /></span><small>{label}</small><strong>{value}</strong><em><Icon name="arrow-up" /> {change} <i>vs last month</i></em></article>)}</div> }
function Heading({ title, action }) { return <div className="tax-heading"><div><h1>Tax & Commission - {title}</h1><p>Home <Icon name="chevron-right" /> System <Icon name="chevron-right" /> Tax & Commission <Icon name="chevron-right" /> {title}</p></div>{action && <button type="button" className="primary"><Icon name="plus" /> {action}</button>}</div> }
function Table({ headers, rows, statusAt = -1 }) { return <div className="tax-table-wrap"><table className="tax-table"><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}<th>Action</th></tr></thead><tbody>{rows.map((row) => <tr key={row[0]}>{row.map((cell, index) => <td key={`${row[0]}-${index}`}>{index === statusAt ? <Status value={cell} /> : cell}</td>)}<td><button type="button" aria-label={`Edit ${row[0]}`}><Icon name="pen" /></button><button type="button" aria-label={`Delete ${row[0]}`}><Icon name="trash" /></button></td></tr>)}</tbody></table><div className="tax-pagination">Showing 1 to {rows.length} of {rows.length} entries <span>‹ &nbsp; <b>1</b> &nbsp; 2 &nbsp; 3 &nbsp; ›</span></div></div> }
function Overview() { return <><div className="tax-overview"><Panel title="Tax Summary"><p>Total Tax Rules <b>12</b></p><p>Active Tax Rates <b>18</b></p><p>Tax Classes <b>6</b></p><p>Exemptions <b>24</b></p></Panel><Panel title="Tax & Commission Overview"><div className="tax-chart"><svg viewBox="0 0 700 170" preserveAspectRatio="none"><path d="M0 105 C60 120 80 55 140 92 S220 114 280 48 S360 120 420 68 S500 112 560 58 S640 82 700 35" /><path className="commission-line" d="M0 132 C60 145 80 100 140 118 S220 130 280 86 S360 138 420 108 S500 135 560 95 S640 110 700 78" /></svg></div></Panel><Panel title="Quick Actions"><div className="tax-quick">{['Add Tax Rule', 'Add Tax Rate', 'Add Commission Rule', 'Manage Exemptions', 'View Reports'].map((item, index) => <button type="button" key={item} onClick={() => navigateTo(`/admin/tax/${['rules', 'rates', 'commission', 'exemptions', 'reports'][index]}`)}><Icon name={['plus', 'percent', 'scale-balanced', 'file-shield', 'chart-line'][index]} /> {item}</button>)}</div></Panel></div></> }
function List({ tab }) { const data = { rules: ['Tax Rules', rules, ['Rule Name', 'Tax Class', 'Priority', 'Status', 'Applied To'], 3, 'Add Tax Rule'], classes: ['Tax Classes', classes, ['Class Name', 'Description', 'Default Rate', 'Status'], 3, 'Add Tax Class'], rates: ['Tax Rates', rates, ['Rate Name', 'Tax Class', 'Rate %', 'Region', 'Status'], 4, 'Add Tax Rate'], commission: ['Commission Rules', plans, ['Rule Name', 'Applies To', 'Type', 'Rate', 'Status'], 4, 'Add Commission Rule'], plans: ['Commission Plans', plans, ['Plan Name', 'For', 'Applies To', 'Valid Until', 'Status'], 4, 'Add Plan'], exemptions: ['Tax Exemptions', [['Government Organizations', 'Government', 'Tax exempt', 'Active'], ['Educational Institutions', 'Education', 'Tax exempt', 'Active'], ['Registered Non-Profit', 'Non-Profit', 'Tax exempt', 'Active']], ['Exemption Name', 'Type', 'Exemption', 'Status'], 3, 'Add Exemption'] }; const [title, rows, headers, statusAt] = data[tab]; return <><Heading title={title} action={data[tab][4]} /><Panel title={title}><div className="tax-filters"><label><Icon name="magnifying-glass" /><input placeholder={`Search ${title.toLowerCase()}...`} /></label><select><option>All Status</option><option>Active</option><option>Inactive</option></select><button type="button"><Icon name="filter" /> Filters</button></div><Table headers={headers} rows={rows} statusAt={statusAt} /></Panel></> }
function Payout() { return <><Heading title="Payout Settings" action="Save Changes" /><div className="tax-grid two"><Panel title="Payout Configuration"><label className="tax-field">Minimum Payout Amount<input defaultValue="Rs. 1,000" /></label><label className="tax-field">Payout Day<select><option>Monday</option></select></label><label className="tax-field">Payout Method<select><option>Bank Transfer</option></select></label><Toggle label="Auto Payout" checked /><Toggle label="Hold Payment For Review" checked /></Panel><Panel title="Bank Details"><label className="tax-field">Account Title<input defaultValue="Mirwal Marketplace" /></label><label className="tax-field">Bank Name<input defaultValue="Meezan Bank" /></label><label className="tax-field">Account Number<input defaultValue="1234567890123456" /></label><label className="tax-field">IBAN<input defaultValue="PK36MEZN0000123456789012" /></label><div className="tax-note"><Icon name="circle-info" /> Payout settings will be used for processing seller payments.</div></Panel></div></> }
function Toggle({ label, checked = false }) { return <div className="tax-toggle"><span>{label}</span><button type="button" className={checked ? 'on' : ''} aria-label={label}><i /></button></div> }
function Reports() { return <><Heading title="Reports" action="Export Report" /><div className="report-kpis"><Kpis items={ [['Total Tax Collected', 'PKR 128,450', '12.5%', 'percent'], ['Total Commission Earned', 'PKR 95,230', '8.2%', 'money-bill'], ['Pending Payouts', 'PKR 45,780', '5.7%', 'clock'], ['Total Transactions', '2,845', '15.2%', 'receipt']] } /></div><div className="tax-grid two"><Panel title="Report Filters"><label className="tax-field">Report Type<select><option>Tax & Commission Summary</option></select></label><label className="tax-field">Date Range<select><option>May 19, 2025 - May 25, 2025</option></select></label><button type="button" className="tax-primary">Generate Report</button></Panel><Panel title="Report Summary"><Table headers={['Type', 'Description', 'Amount', 'Date']} rows={ [['Tax Collection', 'Order #MW-7145', 'PKR 1,245', 'May 25, 2025'], ['Commission Earned', 'Order #MW-7145', 'PKR 950', 'May 25, 2025'], ['Payout', 'Payout #P-7045', 'PKR 3,000', 'May 24, 2025']]} /></Panel></div></> }
export default function AdminTaxCommission() { const { pathname } = useLocation(); const current = pathname.split('/')[3] || 'overview'; const tab = tabs.find((item) => item[1] === current) || tabs[0]; return <AdminLayout><div className="tax-page"><nav className="tax-tabs" aria-label="Tax and commission sections">{tabs.map(([label, key]) => <button type="button" className={key === tab[1] ? 'active' : ''} onClick={() => navigateTo(`/admin/tax/${key}`)} key={key}><Icon name={key === 'overview' ? 'house' : key === 'rules' ? 'list-check' : key === 'classes' ? 'layer-group' : key === 'rates' ? 'percent' : key === 'commission' ? 'scale-balanced' : key === 'plans' ? 'clipboard-list' : key === 'payout' ? 'money-bill-transfer' : key === 'reports' ? 'chart-line' : 'file-shield'} /> {label}</button>)}</nav>{tab[1] === 'overview' ? <><Heading title="Overview" /><Kpis items={ [['Total Tax Collected', 'PKR 128,450', '12.5%', 'percent'], ['Total Commission Earned', 'PKR 95,230', '8.2%', 'money-bill'], ['Pending Payout (Commission)', 'PKR 45,780', '5.7%', 'clock'], ['Total Transactions', '2,845', '15.2%', 'receipt']] } /><Overview /></> : tab[1] === 'payout' ? <Payout /> : tab[1] === 'reports' ? <Reports /> : <List tab={tab[1]} />}</div></AdminLayout> }