import { useState } from 'react'
import { useLocation } from 'react-router-dom'
import { navigateTo } from '../navigation'
import AdminLayout from './AdminLayout'
import Icon from '../components/Icon'
import './payment-settings.css'

const tabs = [['Overview', 'overview'], ['Payment Gateways', 'gateways'], ['Currency Settings', 'currency'], ['Tax Settings', 'tax'], ['Invoice Settings', 'invoice'], ['Refund Settings', 'refund'], ['Payout Settings', 'payout'], ['Security', 'security'], ['Webhooks', 'webhooks']]
const gateways = [['JazzCash', 'Mobile Wallet', 'Active'], ['EasyPaisa', 'Mobile Wallet', 'Active'], ['Stripe', 'Credit / Debit Card', 'Active'], ['PayPal', 'Global Payments', 'Active'], ['Bank Transfer', 'Manual Payment', 'Active']]
const currencies = [['Pakistani Rupee', 'PKR', 'Default'], ['US Dollar', 'USD', 'Active'], ['Euro', 'EUR', 'Active'], ['British Pound', 'GBP', 'Active'], ['Saudi Riyal', 'SAR', 'Active']]
function Panel({ title, children }) { return <section className="payment-panel"><h2>{title}</h2>{children}</section> }
function Field({ label, value, children }) { return <label className="payment-field"><span>{label}</span>{children || <input defaultValue={value} />}</label> }
function Toggle({ label, description, checked = false, onChange = () => {} }) { return <div className="payment-toggle"><div><b>{label}</b><small>{description}</small></div><button type="button" className={checked ? 'on' : ''} aria-pressed={checked} aria-label={label} onClick={onChange}><i /></button></div> }
function Status({ value = 'Active' }) { return <span className="payment-status">{value}</span> }
function Overview() { return <><div className="payment-overview-grid"><Panel title="Payment Summary"><p className="summary-line"><Icon name="building-columns" />Active Gateways <b>8</b><a href="#gateways">View all</a></p><p className="summary-line"><Icon name="coins" />Default Currency <b>PKR</b><a href="#currency">View all</a></p><p className="summary-line"><Icon name="percent" />Tax Rate <b>Pakistani Rupee</b></p><p className="summary-line"><Icon name="rotate-left" />Pending Refunds <b>12</b><a href="#refund">View all</a></p></Panel><Panel title="System Status"><Toggle label="Payment Processing" description="Process customer payments" checked onChange={() => {}} /><Toggle label="Payouts" description="Enable seller payouts" checked onChange={() => {}} /><Toggle label="Tax Calculation" description="Calculate taxes automatically" checked onChange={() => {}} /><Toggle label="Refund Processing" description="Process customer refunds" checked onChange={() => {}} /></Panel><Panel title="Recent Transactions"><div className="transaction-list">{[['Payment #MW-98765', 'Hamza Ali', 'Rs. 24,560'], ['Payout to Seller', 'Ali Raza', 'Rs. 45,000'], ['Refund #MW-98762', 'Order #MW-98762', 'Rs. 2,350'], ['Order #MW-9785', 'Payment processed', 'Rs. 8,990']].map((row) => <p key={row[0]}><Icon name="receipt" /><span><b>{row[0]}</b><small>{row[1]}</small></span><strong>{row[2]}</strong></p>)}</div></Panel></div><Panel title="Quick Actions"><div className="quick-payment-actions">{['Add Payment Gateway', 'Configure Currency', 'Set Tax Rate', 'Manage Invoices', 'Review Refunds'].map((item, index) => <button type="button" key={item} onClick={() => navigateTo(`/admin/payment-settings/${['gateways', 'currency', 'tax', 'invoice', 'refund'][index]}`)}><Icon name={['plus', 'coins', 'percent', 'file-invoice', 'rotate-left'][index]} /><b>{item}</b><small>Configure payment system</small></button>)}</div></Panel></> }
function Gateways() { const [enabled, setEnabled] = useState(true); return <div className="payment-grid two"><Panel title="Enabled Payment Gateways"><p className="muted">Manage and configure your active payment gateways.</p>{gateways.map(([name, type, status]) => <div className="gateway-row" key={name}><Icon name={name === 'Bank Transfer' ? 'building-columns' : name === 'Stripe' ? 'credit-card' : 'wallet'} /><span><b>{name}</b><small>{type}</small></span><Status value={status} /><button type="button">Configure</button><button type="button" className="mini-toggle" onClick={() => setEnabled(!enabled)}><i className={enabled ? 'on' : ''} /></button></div>)}</Panel><Panel title="Gateway Settings"><Field label="Default Gateway"><select defaultValue="JazzCash"><option>JazzCash</option><option>EasyPaisa</option><option>Stripe</option></select></Field><Field label="Minimum Payment Order"><input defaultValue="Rs. 100" /></Field><Field label="Gateway Timeout"><input defaultValue="30 seconds" /></Field><p className="muted">Drag & drop to reorder gateways.</p></Panel></div> }
function Currency() { return <div className="payment-grid two"><Panel title="Currency Configuration"><Field label="Base Currency"><select defaultValue="PKR"><option>PKR (Rs.) - Pakistani Rupee</option></select></Field><Field label="Currency Position"><select defaultValue="Left (Rs. 1,000)"><option>Left (Rs. 1,000)</option></select></Field><Field label="Decimal Separator"><select defaultValue="."><option>.</option></select></Field><Field label="Thousands Separator"><select defaultValue=","><option>,</option></select></Field><Field label="Number of Decimals"><input defaultValue="2" /></Field><Toggle label="Auto Update Exchange Rates" description="Update exchange rates automatically" checked onChange={() => {}} /></Panel><Panel title="Supported Currencies"><table className="payment-table"><thead><tr><th>Currency</th><th>Code</th><th>Status</th><th>Actions</th></tr></thead><tbody>{currencies.map((row) => <tr key={row[0]}>{row.map((cell, index) => <td key={cell}>{index === 2 ? <Status value={cell} /> : cell}</td>)}<td><button type="button"><Icon name="pen" /></button></td></tr>)}</tbody></table></Panel></div> }
function ConfigTab({ tab }) { const names = { tax: ['Tax Configuration', 'Tax Rules'], invoice: ['Invoice Settings', 'Invoice Templates'], refund: ['Refund Configuration', 'Refund Policy'], payout: ['Payout Configuration', 'Payout Methods'], security: ['Security Settings', 'API Keys & Credentials'], webhooks: ['Webhook Configuration', 'Webhook Events'] }; const [left, right] = names[tab]; return <div className="payment-grid two"><Panel title={left}><Field label="Default Value" value={tab === 'tax' ? '17%' : tab === 'refund' ? 'Full refund allowed' : 'Enabled'} /><Field label="Description"><textarea placeholder={`Configure ${tab} settings...`} /></Field><Toggle label={`Enable ${tab}`} description={`Apply ${tab} configuration`} checked onChange={() => {}} /><Toggle label="Require Admin Approval" description="Require approval before processing" checked={tab !== 'security'} onChange={() => {}} /></Panel><Panel title={right}><Field label="Configuration Name" value={tab === 'invoice' ? 'Mirwal Invoice Template' : 'Default Configuration'} /><Field label="Additional Settings"><textarea placeholder="Enter additional settings..." /></Field><button type="button" className="payment-primary">Save Configuration</button></Panel></div> }
export default function AdminPaymentSettings() { const { pathname } = useLocation(); const current = pathname.split('/')[3] || 'overview'; const tab = tabs.find((item) => item[1] === current) || tabs[0]; return <AdminLayout><div className="payment-page"><div className="payment-heading"><div><h1>Payment Settings - {tab[0]}</h1><p>Home <Icon name="chevron-right" /> System <Icon name="chevron-right" /> Settings <Icon name="chevron-right" /> Payment Settings</p></div><div><button type="button">Back to Overview</button><button type="button" className="primary"><Icon name="floppy-disk" /> Save Changes</button></div></div><nav className="payment-tabs" aria-label="Payment settings sections">{tabs.map(([label, key]) => <button type="button" className={tab[1] === key ? 'active' : ''} onClick={() => navigateTo(`/admin/payment-settings/${key}`)} key={key}><Icon name={key === 'overview' ? 'house' : key === 'gateways' ? 'credit-card' : key === 'currency' ? 'coins' : key === 'tax' ? 'percent' : key === 'invoice' ? 'file-invoice' : key === 'refund' ? 'rotate-left' : key === 'payout' ? 'money-bill-transfer' : key === 'security' ? 'shield-halved' : 'link'} /> {label}</button>)}</nav>{tab[1] === 'overview' ? <Overview /> : tab[1] === 'gateways' ? <Gateways /> : tab[1] === 'currency' ? <Currency /> : <ConfigTab tab={tab[1]} />}</div></AdminLayout> }