import { useLocation } from 'react-router-dom'
import { navigateTo } from '../navigation'
import AdminLayout from './AdminLayout'
import Icon from '../components/Icon'
import './messaging-pages.css'

const tabs = [['Overview', 'overview'], ['Email Settings', 'email'], ['Email Templates', 'templates'], ['SMS Settings', 'sms'], ['SMS Templates', 'sms-templates'], ['Providers', 'providers'], ['Logs & History', 'logs'], ['Preferences', 'preferences']]
const emailTemplates = [['Welcome Email', 'User', 'Welcome to Mirwal Marketplace', 'Active'], ['Order Confirmation', 'Order', 'Your order has been confirmed', 'Active'], ['Order Shipped', 'Order', 'Your order has been shipped', 'Active'], ['Order Delivered', 'Order', 'Your order has been delivered', 'Active'], ['Password Reset', 'User', 'Reset your password', 'Active'], ['Account Verification', 'User', 'Verify your account', 'Active'], ['Low Stock Alert', 'Product', 'Product stock is running low', 'Inactive'], ['Contact Form', 'General', 'We have received your message', 'Active']]
const smsTemplates = [['Order Confirmation', 'Order', 'Hi {customer_name}, your order #{order_number}...', 'Active'], ['Order Shipped', 'Order', 'Your order has been shipped...', 'Active'], ['Order Delivered', 'Order', 'Your order has been delivered...', 'Active'], ['Low Stock Alert', 'Product', 'Alert: {product_name} stock is low...', 'Active'], ['Welcome SMS', 'User', 'Welcome to {store_name}. Thank you...', 'Active'], ['Password Reset', 'User', 'Reset your password using this code...', 'Active'], ['Refund Notification', 'Marketing', 'Congratulation! Your refund...', 'Inactive']]
const providers = [['SendGrid', 'API', 'Active', '1'], ['Mailgun', 'API', 'Inactive', '2'], ['Twilio', 'API', 'Active', '1'], ['Nexmo', 'API', 'Inactive', '2'], ['MSG91', 'API', 'Inactive', '3']]
function Panel({ title, children }) { return <section className="messaging-panel"><h2>{title}</h2>{children}</section> }
function Toggle({ label, description, checked = false, onChange = () => {} }) { return <div className="messaging-toggle"><div><b>{label}</b><small>{description}</small></div><button type="button" className={checked ? 'on' : ''} aria-pressed={checked} aria-label={label} onClick={onChange}><i /></button></div> }
function Kpis({ items }) { return <div className="messaging-kpis">{items.map(([label, value, change, icon], index) => <article key={label}><span className={`tone-${index}`}><Icon name={icon} /></span><small>{label}</small><strong>{value}</strong><em><Icon name="arrow-up" /> {change} <i>vs last month</i></em></article>)}</div> }
function Heading({ title }) { return <div className="messaging-heading"><div><h1>Email & SMS - {title}</h1><p>Home <Icon name="chevron-right" /> System <Icon name="chevron-right" /> Settings <Icon name="chevron-right" /> Email & SMS</p></div><div><button type="button">Test Email</button><button type="button" className="primary"><Icon name="floppy-disk" /> Save Changes</button></div></div> }
function Table({ rows, sms = false }) { return <div className="messaging-table-wrap"><table className="messaging-table"><thead><tr>{(sms ? ['Template Name', 'Category', 'Message', 'Status', 'Action'] : ['Template Name', 'Category', 'Subject', 'Status', 'Action']).map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row[0]}>{row.map((cell, index) => <td key={`${row[0]}-${index}`}>{index === 3 ? <span className={`message-status ${cell.toLowerCase()}`}>{cell}</span> : cell}</td>)}<td><button type="button" aria-label={`Edit ${row[0]}`}><Icon name="pen" /></button><button type="button" aria-label={`Delete ${row[0]}`}><Icon name="trash" /></button></td></tr>)}</tbody></table><div className="messaging-pagination">Showing 1 to {rows.length} of {rows.length + 20} entries <span>‹ &nbsp; <b>1</b> &nbsp; 2 &nbsp; 3 &nbsp; ›</span></div></div> }
function Overview() { return <><Kpis items={ [['Total Emails Sent', '12,458', '14.3%', 'envelope'], ['SMS Sent (This Month)', '4,235', '12.5%', 'comment-sms'], ['Email Delivery Rate', '98.6%', '2.5%', 'paper-plane'], ['SMS Delivery Rate', '97.3%', '1.6%', 'mobile-screen']] } /><div className="messaging-overview"><Panel title="Recent Activity">{['Order confirmation sent to Ali Raza', 'Welcome SMS sent to user #123456', 'Password reset email sent', 'Order Shipped SMS sent', 'Low SMS balance alert'].map((item, i) => <p key={item}><Icon name={i % 2 ? 'comment-sms' : 'envelope'} />{item}<small>{i + 2} mins ago</small></p>)}</Panel><Panel title="Email & SMS Usage (This Month)"><div className="usage-chart">{[55, 72, 48, 82, 63, 88, 69].map((height, i) => <i key={i} style={{ height: `${height}%` }} />)}</div></Panel></div><Panel title="Quick Actions"><div className="messaging-actions">{[['Email Settings', 'email'], ['Add Email Template', 'templates'], ['SMS Settings', 'sms'], ['Add SMS Template', 'sms-templates'], ['Email Logs', 'logs'], ['SMS Logs', 'logs']].map(([label, key]) => <button type="button" key={label} onClick={() => navigateTo(`/admin/messaging/${key}`)}><Icon name="plus" /> {label}</button>)}</div></Panel></> }
function Config({ tab }) { const isEmail = tab === 'email'; return <div className="messaging-grid two"><Panel title={isEmail ? 'Email Configuration' : 'General SMS Settings'}><Field label={isEmail ? 'Mail Driver' : 'Enable SMS'} value={isEmail ? 'SMTP' : ''} /><Field label={isEmail ? 'Host' : 'SMS Sender ID'} value={isEmail ? 'mail.mirwal.com' : 'Mirwal'} /><Field label={isEmail ? 'Port' : 'Default Country Code'} value={isEmail ? '587' : 'Pakistan (+92)'} /><Field label={isEmail ? 'Username' : 'SMS Time Format'} value={isEmail ? 'no-reply@mirwal.com' : '24 Hours'} /><Field label={isEmail ? 'Password' : 'SMS Character Encoding'} value="********" /></Panel><Panel title={isEmail ? 'Mailer Settings' : 'SMS Sending Options'}>{(isEmail ? ['Send a copy to admin', 'Send emails in HTML format', 'Add unsubscribe link', 'Enable email tracking'] : ['Send SMS for new order', 'Send SMS for order status update', 'Send SMS for order shipped', 'Send SMS for user registration', 'Send SMS for password reset', 'Log all SMS']).map((item) => <Toggle label={item} description="Apply this messaging preference" checked onChange={() => {}} />)}</Panel></div> }
function Field({ label, value = '' }) { return <label className="message-field"><span>{label}</span><input defaultValue={value} /></label> }
function Editor({ sms = false }) { return <div className="messaging-grid two"><Panel title={sms ? 'SMS Template Editor' : 'Email Content'}><Field label="Template Name" value={sms ? 'Order Confirmation' : 'Order Confirmation Email'} /><Field label="Subject" value="Your order has been confirmed" /><label className="message-field">Content<textarea defaultValue={sms ? 'Hi {customer_name}, your order #{order_number} has been confirmed.' : 'Hi {customer_name},\n\nThank you for your order! Your order has been confirmed and we are preparing it for delivery.'} /></label><button type="button" className="message-primary">Save Template</button></Panel><Panel title={sms ? 'Available Variables' : 'Email Preview'}><p className="muted">{sms ? '{customer_name}, {order_number}, {order_total}, {tracking_number}' : 'Preview how this message will appear to customers.'}</p><div className="message-preview">{sms ? 'Hi Ahmad, your order #MW-98765 has been confirmed.' : 'Hi Ahmad,\n\nThank you for your order! Your order has been confirmed.'}</div></Panel></div> }
function MessagingTab({ tab }) { if (tab === 'overview') return <Overview />; if (tab === 'email' || tab === 'sms') return <Config tab={tab} />; if (tab === 'templates') return <><Heading title="Email Templates" /><Panel title="Email Templates"><Table rows={emailTemplates} /></Panel></>; if (tab === 'sms-templates') return <><Heading title="SMS Templates" /><Panel title="SMS Templates"><Table rows={smsTemplates} sms /></Panel></>; if (tab === 'providers') return <><Heading title="Providers" /><div className="messaging-grid two"><Panel title="Email Providers"><Table rows={providers} /></Panel><Panel title="SMS Providers"><Table rows={providers.slice(2)} sms /></Panel></div></>; if (tab === 'logs') return <><Panel title="Email & SMS Logs"><Table rows={emailTemplates.slice(0, 6)} /></Panel></>; if (tab === 'preferences') return <Config tab="sms" />; return <Editor sms={tab === 'sms-editor'} /> }
export default function AdminMessagingPages() { const { pathname } = useLocation(); const current = pathname.split('/')[3] || 'overview'; const tab = tabs.find((item) => item[1] === current) || tabs[0]; return <AdminLayout><div className="messaging-page"><Heading title={tab[0]} /><nav className="messaging-tabs" aria-label="Email and SMS sections">{tabs.map(([label, key]) => <button type="button" className={key === tab[1] ? 'active' : ''} onClick={() => navigateTo(`/admin/messaging/${key}`)} key={key}><Icon name={key.includes('sms') ? 'comment-sms' : key === 'overview' ? 'house' : key === 'logs' ? 'clock-rotate-left' : 'envelope'} /> {label}</button>)}</nav><MessagingTab tab={tab[1]} /></div></AdminLayout> }