import { useLocation } from 'react-router-dom'
import { navigateTo } from '../navigation'
import AdminLayout from './AdminLayout'
import Icon from '../components/Icon'
import './notification-settings.css'

const tabs = [['Overview', 'overview'], ['Email Notifications', 'email'], ['SMS Notifications', 'sms'], ['Push Notifications', 'push'], ['In-App Notifications', 'app'], ['Templates', 'templates'], ['Settings', 'settings'], ['Logs', 'logs'], ['Preferences', 'preferences']]
const notices = [['Welcome Email', 'Email', 'User Registration', 'Users', 'Active'], ['Order Confirmation', 'Email', 'Order Placed', 'Customers', 'Active'], ['Order Shipped', 'Email', 'Order Shipped', 'Customers', 'Active'], ['Order Delivered', 'Email', 'Order Delivered', 'Customers', 'Active'], ['Password Reset', 'Email', 'Password Reset Request', 'Users', 'Active'], ['Low Stock Alert', 'Email', 'Product Stock', 'Admins', 'Inactive'], ['New Contact Message', 'Email', 'Contact Form Submission', 'Admins', 'Active']]
const sms = [['Order Confirmation', 'Order Placed', 'Customers'], ['Order Shipped', 'Order Shipped', 'Customers'], ['Order Delivered', 'Order Delivered', 'Customers'], ['Cash on Delivery', 'COD Order Placed', 'Customers'], ['Payment Failed', 'Payment Failed', 'Users'], ['Account Verification', 'Account Verification (OTP)', 'Admins'], ['New Registration Alert', 'New User Registration', 'Admins']]
const logs = [['Email', 'Order Confirmation', 'ahmad@example.com', 'Sent', 'May 24, 2025 10:24 AM'], ['SMS', 'Order Shipped', '+92 300 1234567', 'Sent', 'May 24, 2025 10:20 AM'], ['Push', 'Flash Sale Alert', 'All Users', 'Sent', 'May 24, 2025 10:15 AM'], ['Email', 'Password Reset', 'fatima@example.com', 'Sent', 'May 24, 2025 10:10 AM'], ['SMS', 'Order Shipped', '+92 312 3456789', 'Sent', 'May 24, 2025 10:05 AM']]
function Panel({ title, children }) { return <section className="notification-settings-panel"><h2>{title}</h2>{children}</section> }
function Toggle({ label, description, checked = false, onChange = () => {} }) { return <div className="notification-settings-toggle"><div><b>{label}</b><small>{description}</small></div><button type="button" className={checked ? 'on' : ''} aria-pressed={checked} aria-label={label} onClick={onChange}><i /></button></div> }
function Kpis({ items }) { return <div className="notification-settings-kpis">{items.map(([label, value, change, icon], index) => <article key={label}><span className={`tone-${index}`}><Icon name={icon} /></span><small>{label}</small><strong>{value}</strong><em><Icon name="arrow-up" /> {change} <i>vs last month</i></em></article>)}</div> }
function Heading({ title }) { return <div className="notification-settings-heading"><div><h1>Notifications - {title}</h1><p>Home <Icon name="chevron-right" /> System <Icon name="chevron-right" /> Notifications <Icon name="chevron-right" /> {title}</p></div><button type="button" className="primary"><Icon name="floppy-disk" /> Save Changes</button></div> }
function Table({ rows, type = 'email' }) { const headers = type === 'logs' ? ['Type', 'Notification', 'Recipient', 'Status', 'Sent At', 'Action'] : type === 'sms' ? ['Notification Name', 'Event / Trigger', 'Recipients', 'Status', 'Actions'] : ['Notification Name', 'Event / Trigger', 'Recipients', 'Status', 'Actions']; return <div className="notification-settings-table-wrap"><table className="notification-settings-table"><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row[0] + row[1]}>{row.map((cell, index) => <td key={`${row[0]}-${index}`}>{((type !== 'logs' && index === 3) || (type === 'logs' && index === 3)) ? <span className="notification-status">{cell}</span> : cell}</td>)}<td><button type="button" aria-label={`Edit ${row[0]}`}><Icon name="pen" /></button></td></tr>)}</tbody></table><div className="notification-settings-pagination">Showing 1 to {rows.length} of {rows.length + 20} entries <span>‹ &nbsp; <b>1</b> &nbsp; 2 &nbsp; 3 &nbsp; ›</span></div></div> }
function Overview() { return <><Kpis items={ [['Total Sent This Month', '28,542', '14.3%', 'paper-plane'], ['Email Sent', '15,324', '16.2%', 'envelope'], ['SMS Sent', '8,742', '9.7%', 'comment-sms'], ['Push Sent', '4,476', '12.4%', 'bell']] } /><div className="notification-settings-grid two"><Panel title="Notification Summary">{['Email Notifications|15,324|View all', 'SMS Notifications|8,742|View all', 'Push Notifications|4,476|View all', 'In-App Notifications|4,321|View all', 'Failed Notifications|156|View all'].map((item) => { const [label, value, link] = item.split('|'); return <p key={label}><Icon name="circle-check" /><span>{label}<b>{value}</b></span><a href="#details">{link}</a></p> })}</Panel><Panel title="Notification Sent (This Month)"><div className="notification-chart">{[45, 62, 42, 70, 53, 78, 60].map((height, i) => <i key={i} style={{ height: `${height}%` }} />)}</div></Panel></div><Panel title="Quick Actions"><div className="notification-settings-actions">{['Email Settings', 'SMS Settings', 'Push Settings', 'Add Email Template', 'View Logs', 'SMS Logs'].map((label) => <button type="button" key={label} onClick={() => navigateTo(`/admin/notifications/${label.toLowerCase().replaceAll(' ', '-')}`)}><Icon name="plus" /> {label}</button>)}</div></Panel></> }
function Config({ tab }) { const isSms = tab === 'sms'; return <div className="notification-settings-grid two"><Panel title={isSms ? 'General SMS Settings' : 'General Email Settings'}><Field label={isSms ? 'Enable SMS' : 'Enable Notifications'} value={isSms ? '' : ''} /><Field label={isSms ? 'SMS Sender ID' : 'Mail Driver'} value={isSms ? 'Mirwal' : 'SMTP'} /><Field label={isSms ? 'Default Country Code' : 'From Email'} value={isSms ? 'Pakistan (+92)' : 'no-reply@mirwal.com'} /><Field label={isSms ? 'SMS Time Format' : 'Reply To Email'} value={isSms ? '24 Hours' : 'support@mirwal.com'} /><Field label={isSms ? 'SMS Character Encoding' : 'Password'} value="********" /></Panel><Panel title={isSms ? 'SMS Sending Options' : 'Email Notification Options'}>{(isSms ? ['Send SMS for new order', 'Send SMS for order status update', 'Send SMS for order shipped', 'Send SMS for user registration', 'Send SMS for password reset', 'Log all SMS'] : ['Enable New Order Notification', 'Order Status Updated', 'New User Registration', 'New Seller Application', 'Low Stock Alert']).map((label) => <Toggle label={label} description="Apply notification preference" checked onChange={() => {}} />)}</Panel></div> }
function Field({ label, value = '' }) { return <label className="notification-field"><span>{label}</span><input defaultValue={value} /></label> }
function Preferences() { return <div className="notification-settings-grid two"><Panel title="User Notification Preferences">{['Enable user notifications', 'Email Notifications', 'SMS Notifications', 'Push Notifications', 'In-App Notifications'].map((label) => <Toggle label={label} description="Allow this notification channel" checked onChange={() => {}} />)}</Panel><Panel title="Categories">{['Orders & Shipping', 'Marketing & Promotions', 'Account & Security', 'Product Updates', 'System Alerts'].map((label) => <Toggle label={label} description="Send category alerts" checked onChange={() => {}} />)}</Panel></div> }
export default function AdminNotificationSettings() { const { pathname } = useLocation(); const current = pathname.split('/')[3] || 'overview'; const tab = tabs.find((item) => item[1] === current) || tabs[0]; return <AdminLayout><div className="notification-settings-page"><Heading title={tab[0]} /><nav className="notification-settings-tabs" aria-label="Notification settings sections">{tabs.map(([label, key]) => <button type="button" className={key === tab[1] ? 'active' : ''} onClick={() => navigateTo(`/admin/notifications/${key}`)} key={key}><Icon name={key === 'sms' || key === 'sms-templates' ? 'comment-sms' : key === 'push' ? 'bell' : key === 'logs' ? 'clock-rotate-left' : 'envelope'} /> {label}</button>)}</nav>{tab[1] === 'overview' ? <Overview /> : tab[1] === 'email' || tab[1] === 'sms' ? <Config tab={tab[1]} /> : tab[1] === 'templates' ? <Panel title="Email Notification Templates"><Table rows={notices} /></Panel> : tab[1] === 'sms-templates' ? <Panel title="SMS Notification Templates"><Table rows={sms} type="sms" /></Panel> : tab[1] === 'logs' ? <Panel title="Notification Logs"><Table rows={logs} type="logs" /></Panel> : tab[1] === 'preferences' ? <Preferences /> : <Config tab="email" />}</div></AdminLayout> }