import { useLocation } from 'react-router-dom'
import { navigateTo } from '../navigation'
import AdminLayout from './AdminLayout'
import Icon from '../components/Icon'
import './ai-configuration.css'

const tabs = [['Overview', 'overview'], ['Model Providers', 'providers'], ['Models', 'models'], ['Chat Settings', 'chat'], ['Image Settings', 'image'], ['Embeddings', 'embeddings'], ['Prompts', 'prompts'], ['Logs', 'logs']]
const providers = [['OpenAI', 'Active', '4', '••••••••••••', '60 / min'], ['Anthropic', 'Active', '2', '••••••••••••', '50 / min'], ['Google Gemini', 'Active', '3', '••••••••••••', '60 / min'], ['Meta (Llama)', 'Active', '3', '••••••••••••', '120 / min'], ['Mirwal AI', 'Inactive', '1', '••••••••••••', '30 / min']]
const models = [['GPT-4o', 'OpenAI', 'Chat', 'Active', '128K', '1M'], ['GPT-4 Turbo', 'OpenAI', 'Chat', 'Active', '128K', '1K'], ['GPT-3.5 Turbo', 'OpenAI', 'Chat', 'Active', '16K', '8K'], ['Claude 3.5 Sonnet', 'Anthropic', 'Chat', 'Active', '200K', '8K'], ['Claude 3 Haiku', 'Anthropic', 'Chat', 'Active', '200K', '2K'], ['Gemini 1.5 Pro', 'Google Gemini', 'Chat', 'Active', '1M', '1K'], ['Gemini 1.5 Flash', 'Google Gemini', 'Chat', 'Active', '1M', '2K'], ['Llama 3 70B', 'Meta (Llama)', 'Chat', 'Active', '8K', '2K']]
const prompts = [['Product Description Generator', 'Marketing', 'System', 'Active', 'May 25, 2025 10:00 AM'], ['Blog Content Writer', 'Content', 'System', 'Active', 'May 25, 2025 09:15 AM'], ['SEO Meta Generator', 'SEO', 'System', 'Active', 'May 24, 2025 05:45 PM'], ['Customer Support Assistant', 'Support', 'System', 'Active', 'May 24, 2025 03:30 PM'], ['Email Reply Generator', 'Email', 'System', 'Inactive', 'May 23, 2025 11:05 AM']]
function Panel({ title, children }) { return <section className="ai-config-panel"><h2>{title}</h2>{children}</section> }
function Toggle({ label, description, checked = false }) { return <div className="ai-config-toggle"><div><b>{label}</b><small>{description}</small></div><button type="button" className={checked ? 'on' : ''} aria-pressed={checked} aria-label={label}><i /></button></div> }
function Kpis({ items }) { return <div className="ai-config-kpis">{items.map(([label, value, change, icon], index) => <article key={label}><span className={`tone-${index}`}><Icon name={icon} /></span><small>{label}</small><strong>{value}</strong><em><Icon name="arrow-up" /> {change} <i>vs last month</i></em></article>)}</div> }
function Heading({ title, action }) { return <div className="ai-config-heading"><div><h1>AI Configuration - {title}</h1><p>Home <Icon name="chevron-right" /> System <Icon name="chevron-right" /> AI Configuration <Icon name="chevron-right" /> {title}</p></div>{action && <button type="button" className="primary"><Icon name="plus" /> {action}</button>}</div> }
function Table({ headers, rows, statusAt = 1 }) { return <div className="ai-config-table-wrap"><table className="ai-config-table"><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}<th>Actions</th></tr></thead><tbody>{rows.map((row) => <tr key={row[0]}>{row.map((cell, index) => <td key={`${row[0]}-${index}`}>{index === statusAt ? <span className={`ai-config-status ${cell.toLowerCase()}`}>{cell}</span> : cell}</td>)}<td><button type="button" aria-label={`Edit ${row[0]}`}><Icon name="pen" /></button><button type="button" aria-label={`Delete ${row[0]}`}><Icon name="trash" /></button></td></tr>)}</tbody></table><div className="ai-config-pagination">Showing 1 to {rows.length} of {rows.length + 8} entries <span>‹ &nbsp; <b>1</b> &nbsp; 2 &nbsp; 3 &nbsp; ›</span></div></div> }
function Overview() { return <><Kpis items={ [['Total AI Requests (This Month)', '45,231', '18.6%', 'robot'], ['Successful Requests', '43,124', '20.1%', 'circle-check'], ['Tokens Used', '12.45M', '15.6%', 'coins'], ['Average Response Time', '2.45s', '7.8%', 'bolt'], ['Active Models', '8', '12.5%', 'brain']] } /><div className="ai-config-grid three"><Panel title="AI Requests (Last 30 Days)"><div className="ai-config-chart">{[52, 70, 48, 75, 58, 84, 64, 78].map((height, index) => <i key={index} style={{ height: `${height}%` }} />)}</div></Panel><Panel title="Quick Stats">{['Requests Today|1,245', 'Successful Requests|98.7%', 'Failed Requests|1.3%', 'Average Tokens|2,450'].map((item) => { const [label, value] = item.split('|'); return <p key={label}><span>{label}</span><b>{value}</b></p> })}</Panel><Panel title="Quick Actions"><div className="ai-config-actions">{['Add New Configuration', 'Manage API Keys', 'Chat Settings', 'Image Settings', 'View Logs'].map((item, index) => <button type="button" key={item} onClick={() => navigateTo(`/admin/ai/configuration/${['providers', 'providers', 'chat', 'image', 'logs'][index]}`)}><Icon name={['plus', 'key', 'comments', 'image', 'list'][index]} /> {item}</button>)}</div></Panel></div></> }
function Settings({ tab }) { const labels = { chat: ['Enable AI Chat', 'Default Model', 'Temperature', 'Max Tokens', 'Top P'], image: ['Enable Image Generation', 'Default Provider', 'Image Size', 'Image Quality', 'Number of Images'], embeddings: ['Enable Embeddings', 'Default Provider', 'Batch Size', 'Embedding Model', 'Similarity Metric'] }; return <div className="ai-config-grid two"><Panel title={`${tab === 'chat' ? 'Chat' : tab === 'image' ? 'Image' : 'Embedding'} Settings`}>{(labels[tab] || labels.chat).map((label, index) => index === 0 ? <Toggle label={label} description="Enable this AI feature" checked /> : <label className="ai-config-field" key={label}>{label}<input defaultValue={index === 1 ? 'OpenAI' : index === 2 ? '0.7' : index === 3 ? '2048' : 'Standard'} /></label>)}</Panel><Panel title="Advanced Settings"><Toggle label="Enable Content Moderation" description="Filter inappropriate content" checked /><Toggle label="Block Prompt Injection" description="Prevent malicious prompts" checked /><Toggle label="Log AI Conversations" description="Store conversations for analytics" checked /><label className="ai-config-field">Blocked Words<textarea placeholder="Enter words to block..." /></label></Panel></div> }
function ConfigPage({ tab }) { if (tab === 'overview') return <Overview />; if (tab === 'providers') return <><Heading title="Model Providers" action="Add Provider" /><Panel title="Model Providers"><Table headers={['Provider', 'Status', 'Models', 'API Key', 'Rate Limit']} rows={providers} /></Panel></>; if (tab === 'models') return <><Heading title="Models" action="Add Model" /><Panel title="AI Models"><Table headers={['Model Name', 'Provider', 'Type', 'Status', 'Context Window', 'Max Output']} rows={models} statusAt={3} /></Panel></>; if (tab === 'prompts') return <><Heading title="Prompts" action="Add Prompt" /><Panel title="Prompt Templates"><Table headers={['Prompt Name', 'Category', 'Type', 'Status', 'Last Updated']} rows={prompts} statusAt={3} /></Panel></>; if (tab === 'logs') return <><Heading title="Logs" action="Export" /><Panel title="AI Request Logs"><Table headers={['Date & Time', 'Provider', 'Model', 'Type', 'Tokens', 'Status', 'Response Time']} rows={models.slice(0, 6).map((row, index) => [`May 25, 2025 10:${20 - index} AM`, row[1], row[0], row[2], `${1245 - index * 86}`, index === 4 ? 'Failed' : 'Success', `${2.1 + index / 10}s`])} statusAt={5} /></Panel></>; if (tab === 'settings') return <><Heading title="Chat Settings" /><Settings tab="chat" /></>; return <><Heading title={tab[0].toUpperCase() + tab.slice(1)} /><Settings tab={tab === 'image' || tab === 'embeddings' ? tab : 'chat'} /></> }
export default function AdminAIConfiguration() { const { pathname } = useLocation(); const current = pathname.split('/')[3] || 'overview'; const tab = tabs.find((item) => item[1] === current) || tabs[0]; return <AdminLayout><div className="ai-config-page"><nav className="ai-config-tabs" aria-label="AI configuration sections">{tabs.map(([label, key]) => <button type="button" className={key === tab[1] ? 'active' : ''} onClick={() => navigateTo(`/admin/ai/configuration/${key}`)} key={key}><Icon name={key === 'overview' ? 'house' : key === 'providers' ? 'plug' : key === 'models' ? 'brain' : key === 'logs' ? 'list' : 'gear'} /> {label}</button>)}</nav><ConfigPage tab={tab[1]} /></div></AdminLayout> }