import { useState } from 'react'
import AdminLayout from './AdminLayout'
import Icon from '../components/Icon'
import './ai-pages.css'

const queries = [['best smartphones under 50k', 'Mobiles', 'Ahmad Raza', '12', '2 min ago', 'Completed'], ['gaming laptops with i7 processor', 'Electronics', 'Fatima Noor', '11', '5 min ago', 'Completed'], ['best 4k tv for home use', 'Home Appliances', 'Ayesha Malik', '10', '12 min ago', 'Completed'], ['compare iphone 15 and samsung s24', 'Mobiles', 'Usman Khalid', '18', '15 min ago', 'Completed'], ['winter jackets for men', 'Fashion', 'Sana Fatima', '16', '18 min ago', 'Completed'], ['best face serum for acne', 'Beauty', 'Hira Khan', '8', '22 min ago', 'Completed'], ['best printer for home office', 'Electronics', 'Taha Javed', '11', '25 min ago', 'Completed']]
const recommendations = [['Best smartphones under 50k', 'Samsung Galaxy A55', 'Mobiles', 'AI Recommendation 1', 'Ahmad Raza', '21.4%', 'Active'], ['Gaming laptops with i7 processor', 'HP Victus 15', 'Electronics', 'AI Recommendation 2', 'Fatima Noor', '19.7%', 'Active'], ['Best 4k tv for home use', 'Sony Bravia X90L', 'Electronics', 'AI Recommendation 1', 'Usman Khalid', '18.2%', 'Active'], ['Winter jackets for men', 'North Face Jacket', 'Fashion', 'AI Recommendation 2', 'Sana Fatima', '16.5%', 'Active'], ['Best face serum for acne', 'The Ordinary Niacinamide', 'Beauty', 'AI Recommendation 1', 'Hira Khan', '14.8%', 'Active']]
const comparisons = [['iPhone 15 vs Samsung S24 vs Pixel 8', 'Mobiles', '3', 'Usman Khalid', '10 min ago', 'Completed'], ['MacBook Air M4 vs Dell XPS 13', 'Electronics', '2', 'Ahmad Raza', '35 min ago', 'Completed'], ['Sony WH-1000XM5 vs Bose QC45', 'Audio', '2', 'Bilal Ahmed', '55 min ago', 'Completed'], ['Nike Air Jordan 1 vs Adidas Forum', 'Fashion', '2', 'Sana Fatima', '1 hour ago', 'Completed'], ['iPad 10 vs Samsung Tab S9', 'Electronics', '2', 'Hira Javed', '2 hours ago', 'Completed']]
const metrics = { overview: [['Total AI Queries', '24,568', '15.6%', 'magnifying-glass'], ['Successful Recommendations', '8,152', '12.4%', 'wand-magic-sparkles'], ['Recommendations Given', '15,986', '18.2%', 'lightbulb'], ['Comparisons Created', '6,842', '10.8%', 'code-compare'], ['Avg. Satisfaction Score', '4.6 / 5', '5.5%', 'face-smile']], queries: [['Total Queries', '24,568', '15.6%', 'magnifying-glass'], ['Unique Users', '8,152', '12.4%', 'users'], ['Queries Today', '3,024', '8.7%', 'calendar'], ['Avg. Response Time', '2.4s', '6.2%', 'bolt']], recommendations: [['Total Recommendations', '15,986', '18.2%', 'wand-magic-sparkles'], ['Click-Through Rate', '18.7%', '12.4%', 'arrow-pointer'], ['Conversions', '3,854', '15.6%', 'cart-shopping'], ['Conversion Rate', '13.4%', '8.2%', 'chart-line']], comparisons: [['Total Comparisons', '6,842', '10.8%', 'code-compare'], ['Unique Users', '3,214', '11.4%', 'users'], ['Avg. Items Compared', '3.2', '8.2%', 'box'], ['Purchase After Compare', '1,245', '12.7%', 'cart-shopping']] }
function Status({ value }) { return <span className="ai-status">{value}</span> }
function Kpis({ items }) { return <div className="ai-kpis">{items.map(([label, value, change, icon], index) => <article key={label}><span className={`tone-${index}`}><Icon name={icon} /></span><small>{label}</small><strong>{value}</strong><em><Icon name="arrow-up" /> {change} <i>vs last 7 days</i></em></article>)}</div> }
function Heading({ title, action = 'Export' }) { return <div className="ai-heading"><div><h1>{title}</h1><p>Home <Icon name="chevron-right" /> Mirwal AI <Icon name="chevron-right" /> {title}</p></div><button type="button"><Icon name="file-export" /> {action}</button></div> }
function Filters({ placeholder, onSearch }) { return <div className="ai-filters"><label><Icon name="magnifying-glass" /><input placeholder={placeholder} aria-label={placeholder} onChange={(event) => onSearch?.(event.target.value)} /></label><select aria-label="Categories"><option>All Categories</option><option>Mobiles</option><option>Electronics</option><option>Fashion</option></select><select aria-label="Status"><option>All Status</option><option>Completed</option><option>Active</option></select><select aria-label="Date"><option>May 18 - May 24, 2025</option></select><button type="button" aria-label="Filters"><Icon name="filter" /> Filters</button></div> }
function Table({ headers, rows, statusIndex = [] }) { return <div className="ai-table-wrap"><table className="ai-table"><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row[0]}>{row.map((cell, index) => <td key={`${row[0]}-${index}`}>{statusIndex.includes(index) ? <Status value={cell} /> : cell}</td>)}<td><button type="button" aria-label={`Actions for ${row[0]}`}><Icon name="ellipsis" /></button></td></tr>)}</tbody></table><div className="ai-pagination">Showing 1 to {rows.length} of 24,568 results <span>‹ &nbsp; <b>1</b> &nbsp; 2 &nbsp; 3 &nbsp; 4 &nbsp; ›</span><select aria-label="Rows per page"><option>10 / page</option></select></div></div> }
function Chart({ donut = false }) { return donut ? <div className="ai-donut"><b>24,568</b><small>Total</small></div> : <div className="ai-line-chart"><svg viewBox="0 0 700 170" preserveAspectRatio="none" aria-label="AI activity trend"><path d="M0 120 C70 135 95 70 150 105 S225 125 275 55 S355 120 405 72 S480 125 530 50 S620 108 700 68" /></svg><div><span>May 18</span><span>May 19</span><span>May 20</span><span>May 21</span><span>May 22</span><span>May 23</span><span>May 24</span></div></div> }
function Overview() { return <><div className="ai-grid two"><section className="ai-panel wide"><h2>Query Activity</h2><Chart /></section><section className="ai-panel"><h2>Top Query Categories</h2><Chart donut /><div className="ai-legend">Electronics <b>8,642 (35.2%)</b><br />Mobiles <b>5,043 (20.5%)</b><br />Fashion <b>4,215 (17.1%)</b><br />Beauty <b>3,284 (13.4%)</b></div></section></div><div className="ai-grid two"><section className="ai-panel"><h2>AI Usage Funnel <small>Last 7 Days</small></h2><div className="funnel"><i>24,568</i><i>18,392</i><i>6,842</i><i>3,521</i></div></section><section className="ai-panel"><h2>Recent AI Queries</h2><Table headers={['Query', 'Category', 'User', 'Time', 'Status']} rows={queries.slice(0, 4)} statusIndex={[5]} /></section></div></> }
function AiPage({ type }) { const [search, setSearch] = useState(''); const title = type === 'overview' ? 'AI Overview' : type === 'queries' ? 'Shopping Queries' : type === 'recommendations' ? 'Recommendations' : type === 'comparisons' ? 'Comparisons' : 'AI Analytics'; const rows = type === 'queries' ? queries.filter((row) => row.join(' ').toLowerCase().includes(search.toLowerCase())) : type === 'recommendations' ? recommendations : comparisons; const isTable = type !== 'overview' && type !== 'analytics'; return <AdminLayout><div className="ai-page"><Heading title={title} />{type !== 'analytics' && <Kpis items={metrics[type]} />}{type === 'overview' ? <Overview /> : type === 'analytics' ? <Analytics /> : <section className="ai-panel"><Filters placeholder={type === 'queries' ? 'Search query, user or keyword...' : type === 'recommendations' ? 'Search product or query...' : 'Search comparison or user...'} onSearch={setSearch} />{isTable && <Table headers={type === 'queries' ? ['Query', 'Category', 'User', 'Result Shown', 'Time', 'Status', 'Action'] : type === 'recommendations' ? ['Query', 'Recommended Product', 'Category', 'Algorithm', 'User', 'Shown %', 'Status', 'Action'] : ['Comparison', 'Category', 'Items', 'User', 'Time', 'Status', 'Action']} rows={rows} statusIndex={[rows[0]?.length - 1]} />}</section>}</div></AdminLayout> }
function Analytics() { return <><Kpis items={metrics.overview.slice(0, 4)} /><div className="ai-grid three"><section className="ai-panel"><h2>Queries Over Time</h2><Chart /></section><section className="ai-panel"><h2>Queries by Category</h2><Chart donut /></section><section className="ai-panel"><h2>Top Performing Algorithms</h2><div className="algorithm-bars">{['Recommendation 1', 'Recommendation 2', 'Query Understanding', 'Product Matching'].map((item, i) => <p key={item}><span>{item}</span><i style={{ width: `${88 - i * 12}%` }} /></p>)}</div></section></div><div className="ai-grid two"><section className="ai-panel"><h2>User Engagement Funnel</h2><div className="funnel"><i>24,568 Queries</i><i>18,392 Recommendations</i><i>6,842 Comparisons</i><i>3,521 Purchases</i></div></section><section className="ai-panel"><h2>Satisfaction Trend</h2><Chart /></section></div></> }
export default function AdminAIPages({ type = 'overview' }) { return <AiPage type={type} /> }