import { useLocation } from 'react-router-dom'
import { navigateTo } from '../navigation'
import AdminLayout from './AdminLayout'
import Icon from '../components/Icon'
import './search-configuration.css'

const tabs = [['Overview', 'overview'], ['Search Engines', 'engines'], ['Search Sources', 'sources'], ['Filters & Facets', 'facets'], ['Autocomplete', 'autocomplete'], ['Synonyms', 'synonyms'], ['Ranking', 'ranking'], ['Settings', 'settings'], ['Logs', 'logs']]
const engines = [['Laravel Scout (Meilisearch)', 'Meilisearch', 'Active', '1', '256,780', 'May 25, 2025 10:30 AM'], ['Database (MySQL)', 'Database', 'Active', '2', '126,450', 'May 25, 2025 09:45 AM'], ['Elasticsearch', 'Elasticsearch', 'Inactive', '3', '0', '-', '']]
const sources = [['Products', 'Product', 'Title, Description, SKU, Tags, Attributes', 'Active', '112,450', 'May 25, 2025 10:15 AM'], ['Orders', 'Order', 'Order ID, Customer, Status, Items', 'Active', '45,320', 'May 25, 2025 09:45 AM'], ['Customers', 'Customer', 'Name, Email, Phone', 'Active', '30,540', 'May 25, 2025 09:40 AM'], ['Categories', 'Category', 'Name, Description', 'Active', '8,450', 'May 25, 2025 09:00 AM'], ['Blog Posts', 'Content', 'Title, Content, Tags', 'Inactive', '0', '-'], ['Pages', 'Content', 'Title, Content, Slug', 'Inactive', '0', '-']]
const facets = [['Category', 'Category', 'Categories', '1', 'Active'], ['Brand', 'Brand', 'Brand', '2', 'Active'], ['Price Range', 'Price', 'Price Range', '3', 'Active'], ['Rating', 'Rating', 'Rating', '4', 'Active'], ['Stock Status', 'Stock', 'Stock Status', '5', 'Active'], ['Color', 'Color', 'Color', '6', 'Active'], ['Size', 'Size', 'Size', '7', 'Active']]
const synonyms = [['tv', 'television, smart tv', 'television', 'Active'], ['laptop', 'notebook, computer', 'laptop', 'Active'], ['earbuds', 'earphones, earbuds, in-ear', 'earbuds', 'Active'], ['watch', 'wristwatch, smart watch', 'watch', 'Active'], ['mobile', 'smartphone, phone', 'mobile', 'Active']]
function Panel({ title, children }) { return <section className="search-panel"><h2>{title}</h2>{children}</section> }
function Status({ value = 'Active' }) { return <span className={`search-status ${value.toLowerCase()}`}>{value}</span> }
function Kpis({ items }) { return <div className="search-kpis">{items.map(([label, value, change, icon], index) => <article key={label}><span className={`tone-${index}`}><Icon name={icon} /></span><small>{label}</small><strong>{value}</strong><em><Icon name="arrow-up" /> {change} <i>vs last month</i></em></article>)}</div> }
function Heading({ title, action }) { return <div className="search-heading"><div><h1>Search Configuration - {title}</h1><p>Home <Icon name="chevron-right" /> System <Icon name="chevron-right" /> Search Configuration <Icon name="chevron-right" /> {title}</p></div>{action && <button type="button" className="primary"><Icon name="plus" /> {action}</button>}</div> }
function Table({ headers, rows, statusAt = 2 }) { return <div className="search-table-wrap"><table className="search-table"><thead><tr>{headers.map((h) => <th key={h}>{h}</th>)}<th>Actions</th></tr></thead><tbody>{rows.map((row) => <tr key={row[0]}>{row.map((cell, index) => <td key={`${row[0]}-${index}`}>{index === statusAt ? <Status value={cell} /> : cell}</td>)}<td><button type="button" aria-label={`Edit ${row[0]}`}><Icon name="pen" /></button><button type="button" aria-label={`Delete ${row[0]}`}><Icon name="trash" /></button></td></tr>)}</tbody></table><div className="search-pagination">Showing 1 to {rows.length} of {rows.length + 4} entries <span>‹ &nbsp; <b>1</b> &nbsp; 2 &nbsp; 3 &nbsp; ›</span></div></div> }
function Overview() { return <><Kpis items={ [['Total Searches (This Month)', '128,450', '16.4%', 'magnifying-glass'], ['Successful Searches', '122,350', '17.2%', 'circle-check'], ['No Result Searches', '6,100', '7.2%', 'circle-xmark'], ['Average Response Time', '0.24s', '8.4%', 'bolt'], ['Active Search Engines', '2', '0%', 'server'], ['Indexed Items', '256,780', '12.7%', 'database']] } /><div className="search-grid three"><Panel title="Search Performance (Last 30 Days)"><div className="search-chart">{[55, 70, 48, 74, 60, 82, 65, 76].map((height, index) => <i key={index} style={{ height: `${height}%` }} />)}</div></Panel><Panel title="Top Search Terms">{['iphone 15 pro', 'macbook air', 'nike shoes', 'wireless earbuds', 'smart watch'].map((item, index) => <p key={item}><span>{item}</span><b>{[3240, 2120, 1840, 1520, 1185][index].toLocaleString()}</b></p>)}</Panel><Panel title="Quick Actions"><div className="search-actions">{['Add Search Engine', 'Manage Synonyms', 'Rebuild Search Index', 'View Search Logs', 'Clear Search Cache'].map((item, index) => <button type="button" key={item} onClick={() => navigateTo(`/admin/search/${['engines', 'synonyms', 'settings', 'logs', 'settings'][index]}`)}><Icon name={['server', 'arrow-right-arrow-left', 'database', 'list', 'broom'][index]} /> {item}</button>)}</div></Panel></div></> }
function Settings({ tab }) { const names = { autocomplete: ['Autocomplete Settings', 'Popular Suggestions'], ranking: ['Ranking Signals', 'Weights'], settings: ['Index Settings', 'Cache Settings'] }; const [left, right] = names[tab] || names.settings; return <div className="search-grid two"><Panel title={left}><label>Enable feature<input defaultValue="Enabled" /></label><label>Minimum characters<input defaultValue="2" /></label><label>Delay (ms)<input defaultValue="300" /></label><button type="button" className="search-primary">Save Changes</button></Panel><Panel title={right}><label>Default setting<select><option>Relevance</option><option>Popularity</option></select></label><label>Maximum results<input defaultValue="20" /></label><label>Configuration<textarea placeholder="Enter configuration..." /></label><button type="button" className="search-primary">Save Changes</button></Panel></div> }
function SearchPage({ tab }) { if (tab === 'overview') return <Overview />; if (tab === 'engines') return <><Heading title="Search Engines" action="Add Engine" /><Panel title="Search Engines"><Table headers={['Engine Name', 'Type', 'Status', 'Priority', 'Indexed Items', 'Last Indexed']} rows={engines} statusAt={2} /></Panel></>; if (tab === 'sources') return <><Heading title="Search Sources" action="Add Source" /><Panel title="Search Sources"><Table headers={['Source Name', 'Source Type', 'Content', 'Status', 'Indexed Items', 'Last Indexed']} rows={sources} statusAt={3} /></Panel></>; if (tab === 'facets') return <><Heading title="Filters & Facets" action="Add Filter" /><div className="search-grid two"><Panel title="Available Filters"><Table headers={['Filter', 'Category', 'Display Type', 'Sort Order']} rows={facets.map((row) => row.slice(0, 4))} statusAt={-1} /></Panel><Panel title="Active Facets"><Table headers={['Facet Name', 'Display Name', 'Type', 'Sort Order', 'Status']} rows={facets} statusAt={4} /></Panel></div></>; if (tab === 'synonyms') return <><Heading title="Synonyms" action="Add Synonym" /><Panel title="Synonym Groups"><Table headers={['Synonym Group', 'Synonyms', 'Replacement Term', 'Status']} rows={synonyms} statusAt={3} /></Panel></>; if (tab === 'logs') return <><Heading title="Logs" action="Export" /><Panel title="Search Logs"><Table headers={['Date & Time', 'Search Term', 'Results', 'Status', 'User']} rows={synonyms.map((row, i) => [`May 25, 2025 10:2${i} AM`, row[0], `${1245 - i * 90}`, i === 3 ? 'No Results' : 'Success', `user${i + 1}`])} statusAt={3} /></Panel></>; return <><Heading title={tab[0].toUpperCase() + tab.slice(1)} action="Save Changes" /><Settings tab={tab} /></> }
export default function AdminSearchConfiguration() { const { pathname } = useLocation(); const current = pathname.split('/')[3] || 'overview'; const tab = tabs.find((item) => item[1] === current) || tabs[0]; return <AdminLayout><div className="search-page"><nav className="search-tabs" aria-label="Search configuration sections">{tabs.map(([label, key]) => <button type="button" className={key === tab[1] ? 'active' : ''} onClick={() => navigateTo(`/admin/search/${key}`)} key={key}><Icon name={key === 'overview' ? 'house' : key === 'logs' ? 'list' : 'magnifying-glass'} /> {label}</button>)}</nav><SearchPage tab={tab[1]} /></div></AdminLayout> }