/* eslint-disable no-unused-vars */
import { useLocation } from 'react-router-dom'
import { navigateTo } from '../navigation'
import AdminLayout from './AdminLayout'
import Icon from '../components/Icon'
import './shipping-pages.css'

const tabs = [['Overview', 'overview'], ['Shipping Zones', 'zones'], ['Shipping Methods', 'methods'], ['Delivery Partners', 'partners'], ['Shipping Rates', 'rates'], ['Warehouses', 'warehouses'], ['Tracking & Notifications', 'tracking'], ['Returns & Reverse Logistics', 'returns']]
const zones = [['Local Zone', '1', '4', '25', 'Active'], ['National Zone', '1', '34', '200+', 'Active'], ['GCC Countries', '6', '-', '500+', 'Active'], ['Europe Zone', '29', '-', '80+', 'Active'], ['North America', '2', '-', '40+', 'Active'], ['Asia Pacific', '8', '-', '60+', 'Active']]
const methods = [['Standard Shipping', 'Fixed Rate', '3 - 5 business days', 'Active'], ['Express Shipping', 'Fixed Rate', '1 - 2 business days', 'Active'], ['Same Day Delivery', 'Fixed Rate', 'Same day', 'Active'], ['Store Pickup', 'Free', 'Same day', 'Active'], ['Cash on Delivery', 'COD', '3 - 5 business days', 'Active'], ['Freight / Bulk', 'Freight', '5 - 7 business days', 'Active']]
const rates = [['Local Zone', 'Standard Shipping', 'Flat Rate', 'PKR 150', 'PKR 1,500', 'Active'], ['Local Zone', 'Express Shipping', 'Flat Rate', 'PKR 300', 'PKR 3,000', 'Active'], ['National Zone', 'Standard Shipping', 'Flat Rate', 'PKR 250', 'PKR 3,500', 'Active'], ['National Zone', 'Express Shipping', 'Flat Rate', 'PKR 450', 'PKR 5,000', 'Active'], ['GCC Countries', 'Express Shipping', 'Flat Rate', 'PKR 1,200', 'PKR 10,000', 'Active']]
const partners = [['Leopards Courier', 'Domestic', 'All Our Partners', 'Active'], ['TCS', 'Domestic', 'All Our Partners', 'Active'], ['DHL', 'International', 'Worldwide', 'Active'], ['FedEx', 'International', 'Worldwide', 'Active'], ['BlueEX', 'Domestic', 'Major Cities', 'Active']]
const warehouses = [['Main Warehouse', 'Lahore, Pakistan', 'Active', 'Default'], ['Karachi Warehouse', 'Karachi, Pakistan', 'Active', ''], ['Islamabad Warehouse', 'Islamabad, Pakistan', 'Active', ''], ['Peshawar Warehouse', 'Peshawar, Pakistan', 'Inactive', ''], ['Faisalabad Warehouse', 'Faisalabad, Pakistan', 'Active', '']]
function Panel({ title, children }) { return <section className="shipping-panel"><h2>{title}</h2>{children}</section> }
function Status({ value = 'Active' }) { return <span className={`shipping-status ${value.toLowerCase()}`}>{value}</span> }
function Kpis({ items }) { return <div className="shipping-kpis">{items.map(([label, value, icon], index) => <article key={label}><span className={`tone-${index}`}><Icon name={icon} /></span><small>{label}</small><strong>{value}</strong><em>+{[12.4, 8.2, 16.7, 6.4][index] || 7.1}% <i>vs last 7 days</i></em></article>)}</div> }
function Heading({ title, action }) { return <div className="shipping-heading"><div><h1>Shipping & Delivery - {title}</h1><p>Home <Icon name="chevron-right" /> System <Icon name="chevron-right" /> Shipping & Delivery <Icon name="chevron-right" /> {title}</p></div>{action && <button type="button" className="primary"><Icon name="plus" /> {action}</button>}</div> }
function Table({ headers, rows, statusAt }) { return <div className="shipping-table-wrap"><table className="shipping-table"><thead><tr>{headers.map((h) => <th key={h}>{h}</th>)}<th>Action</th></tr></thead><tbody>{rows.map((row) => <tr key={row[0]}>{row.map((cell, index) => <td key={`${row[0]}-${index}`}>{index === statusAt ? <Status value={cell} /> : cell}</td>)}<td><button type="button" aria-label={`Edit ${row[0]}`}><Icon name="pen" /></button></td></tr>)}</tbody></table><div className="shipping-pagination">Showing 1 to {rows.length} records <span>‹ &nbsp; <b>1</b> &nbsp; 2 &nbsp; 3 &nbsp; ›</span></div></div> }
function Overview() { return <><div className="shipping-overview"><Panel title="Shipping Summary"><p>Total Orders Shipped <b>12,456</b></p><p>Pending Shipments <b>342</b></p><p>Delivered Orders <b>11,234</b></p><p>Returned Orders <b>156</b></p></Panel><Panel title="Active Shipping Methods">{methods.slice(0, 4).map((row) => <p key={row[0]}><Icon name="truck" />{row[0]}<Status /></p>)}</Panel><Panel title="Shipping Performance"><div className="shipping-ring">98.2%<small>On-time Delivery</small></div><div className="legend">On-time Delivery <b>96.2%</b><br />Delayed <b>1.2%</b><br />Failed <b>0.5%</b></div></Panel></div><Panel title="Quick Actions"><div className="shipping-actions">{[['Add Shipping Zone', 'plus', 'zones'], ['Add Shipping Method', 'truck', 'methods'], ['Configure Delivery Partners', 'link', 'partners'], ['Manage Warehouses', 'warehouse', 'warehouses']].map(([label, icon, key]) => <button type="button" key={label} onClick={() => navigateTo(`/admin/shipping/${key}`)}><Icon name={icon} /> {label}</button>)}</div></Panel></> }
function FormSettings({ tab }) { const labels = { delivery: ['General Delivery Settings', 'Delivery Time Display'], tracking: ['Tracking Settings', 'Notification Settings'], returns: ['Return Settings', 'Reverse Logistics'], package: ['Package Settings', 'Packaging Rules'] }; return <div className="shipping-grid two">{(labels[tab] || labels.delivery).map((title) => <Panel title={title} key={title}><div className="shipping-fields"><label>Default Setting<input defaultValue={tab === 'delivery' ? 'Enable Shipping' : 'Standard Shipping'} /></label><label>Configuration<select><option>All Zones</option><option>Pakistan</option></select></label><label>Description<textarea placeholder="Enter configuration details..." /></label><button type="button" className="primary">Save Changes</button></div></Panel>)}</div> }
function ListPage({ tab }) { const configs = { zones: ['Shipping Zones', zones, ['Zone Name', 'Countries', 'States / Regions', 'Cities', 'Status'], 4, 'Add Zone'], methods: ['Shipping Methods', methods, ['Method Name', 'Type', 'Estimated Delivery', 'Status'], 3, 'Add Method'], partners: ['Delivery Partners', partners, ['Partner Name', 'Service Type', 'Coverage Area', 'Status'], 3, 'Add Partner'], rates: ['Shipping Rates', rates, ['Zone', 'Method', 'Rate Type', 'Flat Rate', 'Free Shipping Min.', 'Status'], 5, 'Add Rate'], warehouses: ['Warehouses', warehouses, ['Warehouse', 'Location', 'Status', 'Default'], 2, 'Add Warehouse'] }; const [title, rows, headers, statusAt, action] = configs[tab]; return <><Kpis items={tab === 'zones' ? [['Total Zones', '8', 'globe'], ['Countries Covered', '12', 'earth-americas'], ['States / Regions', '45', 'map'], ['Cities Covered', '320+', 'city']] : [['Total Methods', '8', 'truck'], ['Active Methods', '6', 'circle-check'], ['Coverage Areas', '24', 'globe'], ['Service Partners', '5', 'handshake']]} /><Panel title={title}><Table headers={headers} rows={rows} statusAt={statusAt} /></Panel>{tab === 'methods' && <Panel title="Method Priority"><div className="shipping-actions"><button type="button">1 &nbsp; Standard Shipping</button><button type="button">2 &nbsp; Express Shipping</button><button type="button">3 &nbsp; Same Day Delivery</button></div></Panel>}</> }
export default function AdminShippingPages() { const { pathname } = useLocation(); const current = pathname.split('/')[3] || 'overview'; const tab = tabs.find((item) => item[1] === current) || tabs[0]; return <AdminLayout><div className="shipping-page"><Heading title={tab[0]} action={tab[1] !== 'overview' && tab[1] !== 'delivery' && `Add ${tab[0].replace('Shipping ', '').replace('Delivery ', '')}`} /><nav className="shipping-tabs" aria-label="Shipping settings sections">{tabs.map(([label, key]) => <button type="button" className={key === tab[1] ? 'active' : ''} onClick={() => navigateTo(`/admin/shipping/${key}`)} key={key}><Icon name={key === 'overview' ? 'house' : key === 'zones' ? 'map' : key === 'methods' ? 'truck' : key === 'partners' ? 'handshake' : key === 'rates' ? 'tags' : key === 'warehouses' ? 'warehouse' : key === 'tracking' ? 'bell' : 'rotate-left'} /> {label}</button>)}</nav>{tab[1] === 'overview' ? <Overview /> : ['zones', 'methods', 'partners', 'rates', 'warehouses'].includes(tab[1]) ? <ListPage tab={tab[1]} /> : <FormSettings tab={tab[1]} />}</div></AdminLayout> }