import { useLocation } from 'react-router-dom'
import { navigateTo } from '../navigation'
import AdminLayout from './AdminLayout'
import Icon from '../components/Icon'
import './integrations-pages.css'

const tabs = [['Overview', 'overview'], ['Payment Gateways', 'gateways'], ['Shipping Providers', 'shipping'], ['Marketing & CRM', 'marketing'], ['Analytics', 'analytics'], ['Third Party', 'third-party'], ['Webhooks', 'webhooks'], ['API', 'api'], ['Logs', 'logs']]
const gateway = [['Stripe', 'Active', 'Live', '2,458', 'May 25, 2025 10:24 AM'], ['PayPal', 'Active', 'Live', '1,125', 'May 25, 2025 10:10 AM'], ['Razorpay', 'Active', 'Live', '850', 'May 24, 2025 11:00 PM'], ['JazzCash', 'Active', 'Live', '642', 'May 24, 2025 06:45 PM'], ['EasyPaisa', 'Active', 'Live', '580', 'May 24, 2025 05:12 PM'], ['Bank Transfer', 'Active', 'Manual', '320', 'May 24, 2025 05:10 PM'], ['Cash on Delivery', 'Active', 'Manual', '210', 'May 24, 2025 05:10 PM'], ['PayFast', 'Inactive', 'Test', '0', '-']]
const shipping = [['DHL Express', 'Active', '3', 'May 25, 2025 09:45 AM'], ['FedEx', 'Active', '4', 'May 25, 2025 09:30 AM'], ['TCS', 'Active', '2', 'May 25, 2025 08:45 AM'], ['Leopards Courier', 'Active', '2', 'May 24, 2025 07:30 PM'], ['UPS', 'Inactive', '3', 'May 23, 2025 02:30 PM'], ['Aramex', 'Inactive', '2', 'May 22, 2025 11:05 AM']]
const services = [['Google reCAPTCHA', 'Security', 'Active', 'Forms spam protection'], ['Google Analytics', 'Analytics', 'Active', 'Track user behavior and traffic'], ['AWS S3', 'Storage', 'Active', 'Store and serve media files'], ['Firebase', 'Backend', 'Inactive', 'Authentication & realtime database'], ['Twilio', 'Communication', 'Active', 'SMS, voice & WhatsApp API'], ['Pushwoosh', 'Realtime', 'Inactive', 'Real-time notifications']]
function Panel({ title, children }) { return <section className="integration-panel"><h2>{title}</h2>{children}</section> }
function Status({ value = 'Active' }) { return <span className={`integration-status ${value.toLowerCase()}`}>{value}</span> }
function Kpis({ items }) { return <div className="integration-kpis">{items.map(([label, value, change, icon], index) => <article key={label}><span className={`tone-${index}`}><Icon name={icon} /></span><small>{label}</small><strong>{value}</strong><em><Icon name="arrow-up" /> {change} <i>vs last 7 days</i></em></article>)}</div> }
function Heading({ title, action = 'Add Integration' }) { return <div className="integration-heading"><div><h1>Integrations - {title}</h1><p>Home <Icon name="chevron-right" /> System <Icon name="chevron-right" /> Integrations <Icon name="chevron-right" /> {title}</p></div>{action && <button type="button" className="primary"><Icon name="plus" /> {action}</button>}</div> }
function Table({ headers, rows, statusAt = 1 }) { return <div className="integration-table-wrap"><table className="integration-table"><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row[0]}>{row.map((cell, index) => <td key={`${row[0]}-${index}`}>{index === statusAt ? <Status value={cell} /> : cell}</td>)}<td><button type="button" aria-label={`Configure ${row[0]}`}><Icon name="gear" /></button><button type="button" aria-label={`More actions for ${row[0]}`}><Icon name="ellipsis" /></button></td></tr>)}</tbody></table><div className="integration-pagination">Showing 1 to {rows.length} of {rows.length + 16} entries <span>‹ &nbsp; <b>1</b> &nbsp; 2 &nbsp; 3 &nbsp; ›</span></div></div> }
function Overview() { return <><Kpis items={ [['Total Integrations', '24', '13.5%', 'plug'], ['Active Integrations', '18', '18.7%', 'circle-check'], ['Inactive Integrations', '6', '2.5%', 'circle-xmark'], ['Connected Services', '32', '16.2%', 'link']] } /><div className="integration-grid three"><Panel title="Integration Status"><div className="integration-ring">75%<small>Active</small></div><p>Active <b>18 (75%)</b></p><p>Inactive <b>6 (25%)</b></p><p>Error <b>2 (8%)</b></p></Panel><Panel title="Recent Activity">{['Stripe Payment Gateway connected', 'Mailchimp integration synced', 'New webhook configured', 'PayPal integration failed', 'Google Analytics connected'].map((item, i) => <p key={item}><Icon name={i === 3 ? 'circle-xmark' : 'circle-check'} />{item}<small>{i + 2} mins ago</small></p>)}</Panel><Panel title="Quick Actions"><div className="integration-actions">{['Add New Integration', 'Manage Integrations', 'API Settings', 'View Logs'].map((item, i) => <button type="button" key={item} onClick={() => navigateTo(`/admin/integrations/${['overview', 'overview', 'api', 'logs'][i]}`)}><Icon name={['plus', 'plug', 'code', 'list'][i]} /> {item}</button>)}</div></Panel></div></> }
function ListPage({ tab }) { const configs = { gateways: ['Payment Gateways', gateway, ['Gateway', 'Status', 'Mode', 'Transactions', 'Last Transaction']], shipping: ['Shipping Providers', shipping, ['Provider', 'Status', 'Services', 'Last Sync']], marketing: ['Marketing & CRM', services.slice(0, 5), ['Integration', 'Category', 'Status', 'Contacts', 'Last Sync']], analytics: ['Analytics', services.slice(1, 5), ['Integration', 'Type', 'Status', 'Tracking ID / Property ID', 'Last Data Received']], 'third-party': ['Third Party Services', services, ['Service', 'Category', 'Status', 'Description']], webhooks: ['Webhooks', gateway.slice(0, 5), ['Webhook Name', 'Endpoint URL', 'Events', 'Status', 'Last Triggered']], logs: ['Logs', gateway.slice(0, 6), ['Date & Time', 'Service', 'Event', 'Status', 'Message']] }; const [title, rows, headers] = configs[tab]; return <><Heading title={title} action={tab === 'logs' ? 'Export' : `Add ${title.replace('Payment ', '').replace('Shipping ', '').replace('Third Party ', '')}`} /><Panel title={title}><div className="integration-filters"><label><Icon name="magnifying-glass" /><input placeholder={`Search ${title.toLowerCase()}...`} /></label><select><option>All Status</option><option>Active</option><option>Inactive</option></select><button type="button"><Icon name="filter" /> Filters</button></div><Table headers={headers.concat('Actions')} rows={rows} statusAt={tab === 'logs' ? 3 : tab === 'webhooks' ? 3 : tab === 'analytics' || tab === 'marketing' ? 2 : 1} /></Panel></> }
function Api() { return <><Heading title="API Settings" action="Generate New Key" /><div className="integration-grid two"><Panel title="API Configuration"><label className="integration-field">API Base URL<input defaultValue="https://api.mirwal.com/v1" /></label><label className="integration-field">API Version<select><option>v1</option></select></label><label className="integration-field">Rate Limit<select><option>1000 requests per hour</option></select></label><label className="integration-field">Authentication<input defaultValue="Bearer Token (JWT)" /></label></Panel><Panel title="API Keys"><Table headers={['Key Name', 'Key', 'Status', 'Created', 'Actions']} rows={ [['Default Key', '••••••••••••', 'Active', 'May 20, 2025'], ['Mobile App Key', '••••••••••••', 'Active', 'May 22, 2025'], ['Partner Key', '••••••••••••', 'Inactive', 'May 18, 2025']]} statusAt={2} /></Panel></div></> }
export default function AdminIntegrations() { const { pathname } = useLocation(); const current = pathname.split('/')[3] || 'overview'; const tab = tabs.find((item) => item[1] === current) || tabs[0]; return <AdminLayout><div className="integration-page"><nav className="integration-tabs" aria-label="Integration sections">{tabs.map(([label, key]) => <button type="button" className={key === tab[1] ? 'active' : ''} onClick={() => navigateTo(`/admin/integrations/${key}`)} key={key}><Icon name={key === 'overview' ? 'house' : key === 'logs' ? 'list' : key === 'api' ? 'code' : 'plug'} /> {label}</button>)}</nav>{tab[1] === 'overview' ? <><Heading title="Overview" /><Overview /></> : tab[1] === 'api' ? <Api /> : <ListPage tab={tab[1]} />}</div></AdminLayout> }