import AdminLayout from './AdminLayout'
import Icon from '../components/Icon'
import './finance-pages.css'

const data = { finance: { title: 'Finances Overview', metrics: [['Total Revenue', 'Rs. 24,568,750', '14.3%', 'coins'], ['Total Payouts', 'Rs. 15,245,890', '12.8%', 'wallet'], ['Marketplace Commission', 'Rs. 4,235,640', '16.5%', 'money-bill'], ['Net Profit', 'Rs. 5,087,220', '18.9%', 'circle-check'], ['Transactions', '128,456', '10.5%', 'right-left']], left: 'Revenue Overview', right: 'Revenue by Source' }, business: { title: 'Business Analytics', metrics: [['Total Revenue', 'Rs. 24,568,750', '14.3%', 'coins'], ['Total Expenses', 'Rs. 14,235,640', '11.5%', 'money-bill'], ['Gross Profit', 'Rs. 10,333,110', '16.2%', 'chart-line'], ['Operating Profit', 'Rs. 6,098,680', '17.9%', 'circle-check'], ['Net Profit', 'Rs. 5,087,220', '16.9%', 'wallet']], left: 'Profit & Loss Trend', right: 'Expense Breakdown' }, marketplace: { title: 'Marketplace Analytics', metrics: [['GMV', 'Rs. 64,542,310', '14.2%', 'cart-shopping'], ['Marketplace Revenue', 'Rs. 2,648,750', '11.8%', 'money-bill'], ['Total Orders', '12,846', '12.1%', 'bag-shopping'], ['Avg. Order Value', 'Rs. 5,332', '7.4%', 'chart-line']], left: 'GMV Trend', right: 'GMV by Category' }, seller: { title: 'Seller Analytics', metrics: [['Total Seller Sales', 'Rs. 15,245,000', '12.5%', 'store'], ['Active Sellers', '1,256', '8.4%', 'users'], ['Top Seller Revenue', 'Rs. 1,245,600', '16.3%', 'trophy'], ['Commission Earned', 'Rs. 4,235,640', '11.8%', 'money-bill']], left: 'Payout Trend', right: 'Payout by Payment Method' }, customer: { title: 'Customer Analytics', metrics: [['Total Customers', '24,568', '14.2%', 'users'], ['Returning Customers', '8,152', '12.4%', 'user-check'], ['Customer LTV', 'Rs. 12,548', '9.7%', 'heart'], ['Refunds Issued', 'Rs. 1,245,600', '7.2%', 'rotate-left']], left: 'New vs Returning Customers', right: 'Customers by Location' }, ai: { title: 'AI Analytics', metrics: [['Total AI Queries', '24,568', '15.6%', 'robot'], ['AI Recommendations', '15,986', '18.2%', 'wand-magic-sparkles'], ['AI Comparisons', '6,842', '10.8%', 'code-compare'], ['AI Conversions', '3,854', '13.4%', 'cart-shopping'], ['AI Revenue Impact', 'Rs. 8,245,600', '16.2%', 'money-bill']], left: 'AI Queries Trend', right: 'Queries by Intent' } }
function Kpis({ items }) { return <div className="finance-kpis">{items.map(([label, value, change, icon], index) => <article key={label}><span className={`tone-${index}`}><Icon name={icon} /></span><small>{label}</small><strong>{value}</strong><em><Icon name="arrow-up" /> {change} <i>vs last 7 days</i></em></article>)}</div> }
function LineChart() { return <div className="finance-line"><svg viewBox="0 0 700 170" preserveAspectRatio="none" aria-label="Finance trend"><path d="M0 125 C70 142 95 70 150 108 S230 125 280 55 S355 115 410 68 S480 125 530 48 S620 110 700 64" /></svg><div><span>May 18</span><span>May 19</span><span>May 20</span><span>May 21</span><span>May 22</span><span>May 23</span><span>May 24</span></div></div> }
function Donut() { return <div className="finance-donut"><b>Rs. 24,568,750</b><small>Total</small></div> }
function Panel({ title, children }) { return <section className="finance-panel"><h2>{title}</h2>{children}</section> }
function Summary({ title }) { return <Panel title={title}><div className="finance-summary">{['Total Revenue', 'Total Payouts', 'Marketplace Commission', 'Net Profit', 'Total Transactions'].map((item, index) => <p key={item}><span>{item}</span><b>{['Rs. 24,568,750', 'Rs. 15,245,890', 'Rs. 4,235,640', 'Rs. 5,087,220', '128,456'][index]}</b><em>+{[14.3, 12.8, 16.5, 18.9, 10.5][index]}%</em></p>)}</div></Panel> }
export default function AdminFinancePages({ type = 'finance' }) { const config = data[type] || data.finance; return <AdminLayout><div className="finance-page"><div className="finance-heading"><div><h1>{config.title}</h1><p>Home <Icon name="chevron-right" /> Finances <Icon name="chevron-right" /> {config.title}</p></div><button type="button"><Icon name="calendar" /> May 18 - May 24, 2025 <Icon name="chevron-down" /></button></div><Kpis items={config.metrics} /><div className="finance-grid top"><Panel title={config.left}><LineChart /></Panel><Panel title={config.right}><Donut /><div className="finance-legend">Electronics <b>35.2%</b><br />Mobiles <b>20.5%</b><br />Fashion <b>17.1%</b><br />Home & Kitchen <b>14.1%</b><br />Other <b>13.1%</b></div></Panel></div><div className="finance-grid bottom"><Summary title={type === 'business' ? 'Income Statement Summary' : type === 'ai' ? 'AI Performance' : 'Financial Summary'} /><Summary title={type === 'seller' ? 'Top Sellers by Payout' : type === 'customer' ? 'Customer Financial Health' : 'Top Revenue Categories'} /><Summary title={type === 'marketplace' ? 'Marketplace Performance' : 'Platform Summary'} /></div></div></AdminLayout> }