import { useState } from 'react'
import AdminLayout from './AdminLayout'
import Icon from '../components/Icon'
import './dashboard.css'

const kpis = [['GMV', 'Rs. 12.84M', '12.4%', 'bag-shopping', 'orange'], ['Total Orders', '8,421', '8.2%', 'cart-shopping', 'violet'], ['Total Customers', '52,421', '14.8%', 'users', 'blue'], ['Total Sellers', '1,284', '6.4%', 'store', 'green'], ['Total Products', '84,291', '11.2%', 'cube', 'amber'], ['Revenue (Platform)', 'Rs. 1.28M', '13.3%', 'money-bill', 'pink']]
const activities = [['Seller "TechZone" approved', '2 minutes ago', 'user-check'], ['Product "MacBook Air M4" flagged', '8 minutes ago', 'flag'], ['Refund #MW-28421 processed', '14 minutes ago', 'bag-shopping'], ['New seller "GadgetHub" registered', '21 minutes ago', 'user-plus'], ['Admin changed seller permissions', '32 minutes ago', 'gear'], ['Order #MW-98421 delivered', '45 minutes ago', 'box']]
const categories = [['Mobile Phones', '1,842', 'Rs. 3.42M'], ['Laptops', '1,234', 'Rs. 2.84M'], ['Home Appliances', '982', 'Rs. 1.92M'], ['Fashion', '875', 'Rs. 1.42M'], ['Accessories', '756', 'Rs. 1.24M']]
const orders = [['#MW-98421', 'Ali Khan', 'TechZone Store', 'Rs. 45,990', 'Delivered', 'Paid'], ['#MW-98420', 'Sara Malik', 'Mobile World', 'Rs. 29,999', 'Shipped', 'Paid'], ['#MW-98419', 'Usman Rauf', 'Laptop House', 'Rs. 120,000', 'Processing', 'Paid'], ['#MW-98418', 'Hina Fatima', 'GadgetHub', 'Rs. 8,499', 'Pending', 'COD'], ['#MW-98417', 'Zain Abbas', 'Fashion Fiesta', 'Rs. 3,299', 'Cancelled', 'Refunded']]
const sellers = [['TechZone Store', '2,842', 'Rs. 45,82,000', 'Rs. 4,58,200', '4.8'], ['Mobile World', '2,231', 'Rs. 38,91,000', 'Rs. 3,89,100', '4.7'], ['Laptop House', '1,982', 'Rs. 32,44,000', 'Rs. 3,24,400', '4.6'], ['GadgetHub', '1,742', 'Rs. 28,31,000', 'Rs. 2,83,100', '4.5'], ['Audio Hub', '1,321', 'Rs. 18,93,000', 'Rs. 1,89,300', '4.4']]
const queries = ['best gaming laptop under 50000', 'iphone 15 pro in pakistan', 'best shoes for running', '4k tv 55 inch under 80000', 'best mobile under 30000']

function Panel({ title, action = 'View All', children, className = '' }) { return <section className={`admin-panel ${className}`}><div className="panel-title"><h2>{title}</h2><button type="button">{action}</button></div>{children}</section> }
function Status({ children }) { return <span className={`status status-${children.toLowerCase()}`}>{children}</span> }

export default function AdminDashboard() {
  const [range, setRange] = useState('7 Days')
  const [orderTab, setOrderTab] = useState('All')
  return <AdminLayout><div className="admin-dashboard"><div className="dashboard-heading"><div><h1>Good morning, Super Admin! <span aria-hidden="true">👋</span></h1><p>Here's what's happening across Mirwal today.</p></div><button type="button" className="admin-date"><Icon name="calendar" /> May 24, 2025 <Icon name="chevron-down" /></button></div>
    <div className="kpi-grid">{kpis.map(([label, value, change, icon, tone]) => <article className={`kpi-card ${tone}`} key={label}><div><small>{label}</small><strong>{value}</strong></div><span><Icon name={icon} /></span><em><Icon name="arrow-up" /> {change} <i>vs last 7 days</i></em></article>)}</div>
    <div className="dashboard-grid top-grid"><Panel title="Revenue Overview" className="revenue-panel"><div className="chart-toolbar"><span><b /> Revenue (Rs.) <b className="gray" /> Orders</span><div>{['7 Days', '30 Days', '3 Months', '12 Months'].map((item) => <button type="button" className={range === item ? 'selected' : ''} key={item} onClick={() => setRange(item)}>{item}</button>)}</div></div><div className="line-chart"><div className="y-axis">14M<br />12M<br />10M<br />8M<br />6M<br />4M<br />2M<br />0</div><svg viewBox="0 0 700 170" preserveAspectRatio="none" aria-label="Revenue and order trend"><path className="chart-fill" d="M0 135 C80 115 100 125 170 82 S260 125 350 100 S430 58 520 60 S630 55 700 68 L700 170 L0 170Z" /><path className="chart-line" d="M0 135 C80 115 100 125 170 82 S260 125 350 100 S430 58 520 60 S630 55 700 68" /><path className="order-line" d="M0 115 C75 105 105 112 170 65 S260 110 350 75 S430 45 520 55 S630 45 700 88" /></svg><div className="x-axis">{['18 May', '19 May', '20 May', '21 May', '22 May', '23 May', '24 May'].map((day) => <span key={day}>{day}</span>)}</div></div></Panel><Panel title="Marketplace Health"><div className="health-list">{[['Products', '94%', 'green'], ['Sellers', '98%', 'green'], ['Orders', '91%', 'orange'], ['Customer Satisfaction', '96%', 'green'], ['Payments', '97%', 'green'], ['System Uptime', '99.9%', 'green']].map(([label, value, tone]) => <div key={label}><span>{label}</span><b>{value}</b><i className={tone}><u /></i></div>)}</div></Panel><Panel title="Action Required"><div className="action-list">{[['42', 'Seller applications awaiting review', 'user-plus'], ['18', 'Products awaiting approval', 'box'], ['7', 'Seller verification issues', 'user-shield'], ['12', 'Customer disputes', 'circle-exclamation'], ['5', 'Payment issues', 'money-bill'], ['3', 'Suspicious activities', 'triangle-exclamation']].map(([count, text, icon]) => <button type="button" key={text}><i><Icon name={icon} /></i><b>{count}</b><span>{text}</span><Icon name="chevron-right" /></button>)}</div></Panel></div>
    <div className="dashboard-grid middle-grid"><Panel title="AI Overview" action="View Details" className="ai-panel"><div className="ai-stats">{[['Total AI Queries', '24,842', '15.6%', 'robot'], ['Successful Recommendations', '18,392', '12.3%', 'wand-magic-sparkles'], ['Success Rate', '74.0%', '6.2%', 'circle-check'], ['Comparisons Made', '9,842', '10.8%', 'code-compare'], ['AI -> Product Clicks', '16,421', '13.1%', 'arrow-pointer'], ['AI -> Purchases', '3,842', '18.7%', 'cart-shopping']].map(([label, value, change, icon]) => <div key={label}><Icon name={icon} /><small>{label}</small><strong>{value}</strong><em><Icon name="arrow-up" /> {change}</em></div>)}</div></Panel><Panel title="Recent Activity"><div className="activity-list">{activities.map(([text, time, icon]) => <div key={text}><i><Icon name={icon} /></i><span>{text}</span><small>{time}</small></div>)}</div></Panel><Panel title="Top Performing Categories"><div className="category-table"><div><b>Category</b><b>Orders</b><b>Revenue</b></div>{categories.map(([name, count, revenue], index) => <div key={name}><span><i style={{ width: `${72 - index * 10}%` }} />{name}</span><span>{count}</span><span>{revenue}</span></div>)}</div></Panel></div>
    <div className="dashboard-grid lower-grid"><Panel title="Pending Approvals" action="View All"><div className="tabs">{['All (60)', 'Products (18)', 'Sellers (42)'].map((tab) => <button type="button" className={tab.startsWith('All') ? 'selected' : ''} key={tab}>{tab}</button>)}</div><div className="approval-table"><div><b>Type</b><b>Item</b><b>Submitted By</b><b>Submitted On</b><b>Action</b></div>{[['Product', 'iPhone 15 Pro Max 256GB', 'Mobile World', 'May 24, 2025'], ['Product', 'Dell XPS 13 Laptop', 'Laptop House', 'May 24, 2025'], ['Seller', 'TechZone Store', 'Ali Raza', 'May 24, 2025'], ['Product', 'Sony WH-1000XM5', 'Audio Hub', 'May 24, 2025']].map((row) => <div key={row[1]}>{row.map((cell) => <span key={cell}>{cell}</span>)}<span><button type="button" aria-label="Approve"><Icon name="check" /></button><button type="button" aria-label="Reject"><Icon name="xmark" /></button></span></div>)}</div></Panel><Panel title="Top AI Shopping Queries"><div className="queries">{queries.map((query, index) => <div key={query}><b>{index + 1}</b><span>{query}</span><strong>{[1248, 1032, 876, 754, 689][index].toLocaleString()}</strong></div>)}</div></Panel></div>
    <div className="dashboard-grid summary-grid"><Panel title="Platform Summary"><div className="summary-list">{[['Total Commission (Today)', 'Rs. 12,84,500', '12.4%', 'money-bill'], ['Pending Payouts', 'Rs. 1,28,40,000', '6.2%', 'wallet'], ['Completed Payouts (This Month)', 'Rs. 8,45,20,000', '15.5%', 'users'], ['Refunds (This Month)', 'Rs. 42,84,000', '7.1%', 'cart-shopping']].map(([label, value, change, icon]) => <div key={label}><Icon name={icon} /><span>{label}</span><b>{value}</b><em><Icon name="arrow-up" /> {change}</em></div>)}</div></Panel><Panel title="System Status" action="View Details"><div className="system-list">{['Server Status', 'Payment Gateway', 'AI Service', 'Email Service', 'Search Service', 'File Storage'].map((item) => <div key={item}><Icon name="circle-check" /><span>{item}</span><b>Operational</b></div>)}</div></Panel><Panel title="Sales Summary" action="This Week"><div className="bar-chart">{[62, 84, 48, 73, 92, 56].map((height, index) => <span key={index} style={{ height: `${height}%` }}><i>{['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri'][index]}</i></span>)}</div><strong className="chart-total">Total: Rs. 24,84,000 <em><Icon name="arrow-up" /> 10.8%</em></strong></Panel></div>
    <Panel title="Latest Orders" className="wide-panel"><div className="tabs order-tabs">{['All', 'Pending', 'Processing', 'Shipped', 'Delivered', 'Cancelled'].map((tab) => <button type="button" className={orderTab === tab ? 'selected' : ''} onClick={() => setOrderTab(tab)} key={tab}>{tab}</button>)}</div><div className="orders-table"><div className="orders-row orders-head"><b>Order ID</b><b>Customer</b><b>Seller</b><b>Amount</b><b>Status</b><b>Payment</b><b>Date</b><b>Action</b></div>{orders.filter((row) => orderTab === 'All' || row[4] === orderTab).map((row) => <div className="orders-row" key={row[0]}>{row.map((cell, index) => <span key={cell}>{index === 4 ? <Status>{cell}</Status> : cell}</span>)}<button type="button" aria-label={`View ${row[0]}`}><Icon name="eye" /></button></div>)}</div></Panel><Panel title="Top Sellers Performance" className="wide-panel"><div className="orders-table seller-table"><div className="orders-row orders-head"><b>Seller</b><b>Total Orders</b><b>Total Sales (Rs.)</b><b>Commission (Rs.)</b><b>Rating</b><b>Status</b><b>Action</b></div>{sellers.map((row) => <div className="orders-row" key={row[0]}><span>{row[0]}</span><span>{row[1]}</span><span>{row[2]}</span><span>{row[3]}</span><span>{row[4]}</span><span className="active-text">Active</span><button type="button" aria-label={`More actions for ${row[0]}`}><Icon name="ellipsis" /></button></div>)}</div></Panel></div></AdminLayout>
}
