import { useLocation } from 'react-router-dom'
import { navigateTo } from '../navigation'
import AdminLayout from './AdminLayout'
import Icon from '../components/Icon'
import './api-webhooks.css'

const tabs = [['Overview', 'overview'], ['API Providers', 'providers'], ['API Keys', 'keys'], ['API Endpoints', 'endpoints'], ['Rate Limits', 'limits'], ['Settings', 'settings'], ['Webhooks', 'webhooks'], ['Logs', 'logs']]
const keys = [['Mobile App', 'mk_live_1a2b3c4d5e6f...', 'Active', 'Read, Write', 'May 15, 2025', 'May 25, 2025 10:30 AM'], ['Website', 'mk_live_7f8g9h0i1j2k...', 'Active', 'Read, Write', 'May 10, 2025', 'May 25, 09:15 AM'], ['Partner Integration', 'mk_live_2m3n4o5p6q7r...', 'Active', 'Read', 'May 05, 2025', 'May 24, 05:45 PM'], ['Analytics Service', 'mk_live_8s9t0u1v2w3x...', 'Inactive', 'Read', 'Apr 20, 2025', 'May 10, 02:20 PM'], ['Test Application', 'mk_test_7y8z9a0b1c2d...', 'Active', 'Read, Write', 'Apr 18, 2025', 'May 22, 11:05 AM']]
const webhooks = [['Order Webhook', 'https://example.com/webhooks/order', '8 Events', 'Active', 'May 25, 2025 10:24 AM'], ['Payment Webhook', 'https://example.com/webhooks/payment', '6 Events', 'Active', 'May 25, 09:40 AM'], ['User Webhook', 'https://example.com/webhooks/user', '4 Events', 'Active', 'May 24, 08:15 PM'], ['Inventory Webhook', 'https://example.com/webhooks/inventory', '7 Events', 'Inactive', 'May 24, 03:30 PM'], ['Product Webhook', 'https://example.com/webhooks/product', '5 Events', 'Active', 'May 23, 09:18 AM']]
const gateway = [['SendGrid', 'Active', 'Live', '2,458', 'May 25, 2025 10:24 AM'], ['Razorpay', 'Active', 'Live', '1,125', 'May 25, 2025 09:45 AM'], ['Google Maps', 'Active', 'Live', '850', 'May 25, 2025 08:30 AM'], ['Cloudinary', 'Active', 'Live', '320', 'May 25, 2025 07:10 AM'], ['Sentry', 'Inactive', 'Test', '0', '-'], ['Twilio', 'Active', 'Live', '642', 'May 25, 2025 06:45 AM']]
function Panel({ title, children }) { return <section className="api-panel"><h2>{title}</h2>{children}</section> }
function Status({ value = 'Active' }) { return <span className={`api-status ${value.toLowerCase()}`}>{value}</span> }
function Kpis({ items }) { return <div className="api-kpis">{items.map(([label, value, change, icon], index) => <article key={label}><span className={`tone-${index}`}><Icon name={icon} /></span><small>{label}</small><strong>{value}</strong><em><Icon name="arrow-up" /> {change} <i>vs last month</i></em></article>)}</div> }
function Heading({ title, action }) { return <div className="api-heading"><div><h1>API Configurations - {title}</h1><p>Home <Icon name="chevron-right" /> System <Icon name="chevron-right" /> API Configurations <Icon name="chevron-right" /> {title}</p></div>{action && <button type="button" className="primary"><Icon name="plus" /> {action}</button>}</div> }
function Field({ label, value = '' }) { return <label className="api-field"><span>{label}</span><input defaultValue={value} /></label> }
function Table({ rows, webhook = false, logs = false }) { const headers = logs ? ['ID', 'Webhook', 'Event', 'Status', 'Response Code', 'Duration', 'Triggered At'] : webhook ? ['Name', 'Endpoint URL', 'Events', 'Status', 'Secret', 'Last Triggered'] : ['Name', 'API Key', 'Status', 'Permissions', 'Created At', 'Last Used']; return <div className="api-table-wrap"><table className="api-table"><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}<th>Actions</th></tr></thead><tbody>{rows.map((row) => <tr key={row[0]}>{row.map((cell, index) => <td key={`${row[0]}-${index}`}>{(cell === 'Active' || cell === 'Inactive' || cell === 'Success' || cell === 'Failed') ? <Status value={cell === 'Success' ? 'Active' : cell} /> : cell}</td>)}<td><button type="button" aria-label={`Edit ${row[0]}`}><Icon name="pen" /></button><button type="button" aria-label={`Delete ${row[0]}`}><Icon name="trash" /></button></td></tr>)}</tbody></table><div className="api-pagination">Showing 1 to {rows.length} of {rows.length + 5} entries <span>‹ &nbsp; <b>1</b> &nbsp; 2 &nbsp; 3 &nbsp; ›</span></div></div> }
function Overview() { return <><Kpis items={ [['Total API Requests (This Month)', '125,430', '16.2%', 'arrow-right-arrow-left'], ['Active API Keys', '12', '8.3%', 'key'], ['Webhook Endpoints', '8', '14.8%', 'link'], ['Successful Requests', '98.7%', '1.2%', 'circle-check'], ['Failed Requests', '1.3%', '4.5%', 'triangle-exclamation']] } /><div className="api-grid three"><Panel title="Request Activity (This Month)"><div className="api-chart">{[65, 78, 58, 72, 62, 84, 55, 70].map((height, index) => <i key={index} style={{ height: `${height}%` }} />)}</div></Panel><Panel title="Top API Endpoints">{['/api/v1/orders', '/api/v1/products', '/api/v1/users', '/api/v1/auth/login', '/api/v1/categories'].map((endpoint, index) => <p key={endpoint}><span>{endpoint}</span><b>{[24560, 21230, 18740, 12450, 8930][index].toLocaleString()}</b><em>98.1%</em></p>)}</Panel><Panel title="Quick Actions"><div className="api-actions">{['Create API Key', 'Add Webhook', 'View API Docs', 'View Webhook Logs'].map((item, index) => <button type="button" key={item} onClick={() => navigateTo(`/admin/api/${['keys', 'webhooks', 'docs', 'logs'][index]}`)}><Icon name={['key', 'link', 'book', 'list'][index]} /> {item}</button>)}</div></Panel></div></> }
function Create({ webhook = false }) { return <><Heading title={`Create ${webhook ? 'Webhook' : 'API Key'}`} /><div className="api-grid three"><Panel title={webhook ? 'Webhook Details' : 'API Key Details'}><label>Name<input placeholder={webhook ? 'e.g. Order Webhook' : 'e.g. Mobile App'} /></label><label>{webhook ? 'Endpoint URL' : 'Permissions'}<input placeholder={webhook ? 'https://your-domain.com/webhook' : 'Select permissions'} /></label><label>Description<textarea placeholder="Enter description (optional)" /></label></Panel><Panel title={webhook ? 'Select Events' : 'Rate Limit'}>{(webhook ? ['Order Placed', 'Order Cancelled', 'Payment Received', 'Payment Failed'] : ['Requests Per Minute', 'Requests Per Hour', 'Requests Per Day']).map((item) => <label className="check-field" key={item}><input type={webhook ? 'checkbox' : 'text'} defaultValue={webhook ? undefined : item === 'Requests Per Minute' ? '60' : item === 'Requests Per Hour' ? '1000' : '10000'} /> {item}</label>)}<button type="button" className="primary">Create {webhook ? 'Webhook' : 'API Key'}</button></Panel><Panel title="Security"><label>Secret Key<input defaultValue="whsec_••••••••••••" /></label><Status /></Panel></div></> }
function Content({ tab }) { if (tab === 'overview') return <Overview />; if (tab === 'providers') return <><Heading title="Providers" action="Add Provider" /><Panel title="API Providers"><Table rows={gateway.map((row) => [row[0], row[1] === 'Active' ? 'Payment Gateway' : 'Payment Service', row[1], row[2], row[3], row[4]])} /></Panel></>; if (tab === 'keys') return <><Heading title="API Keys" action="Add API Key" /><Panel title="API Keys"><Table rows={keys} /></Panel></>; if (tab === 'endpoints') return <><Heading title="Endpoints" action="Add Endpoint" /><Panel title="API Endpoints"><Table rows={webhooks.map((row, i) => [`${row[0]} Endpoint`, row[0].split(' ')[0], row[1], i % 2 ? 'POST' : 'GET', 'Active', 'May 25, 2025 10:30 AM'])} /></Panel></>; if (tab === 'webhooks') return <><Heading title="Webhooks" action="Add Webhook" /><Panel title="Webhook Endpoints"><Table rows={webhooks} webhook /></Panel></>; if (tab === 'logs') return <><Heading title="Logs" action="Export" /><Panel title="API Logs"><Table rows={webhooks.map((row, i) => [`#LOG${1240 - i}`, row[0], 'request.completed', i === 3 ? 'Failed' : 'Success', i === 3 ? '500' : '200', `${200 + i * 20}ms`, row[4]])} logs /></Panel></>; if (tab === 'limits') return <><Heading title="Rate Limits" action="Edit Limits" /><div className="api-grid three"><Panel title="Current Usage (This Month)"><p>Requests <b>125,430 / 1,000,000</b></p><p>Remaining <b>874,570</b></p></Panel><Panel title="Rate Limit Rules">{['Requests Per Minute', 'Requests Per Hour', 'Requests Per Day', 'Requests Per Month'].map((item, i) => <p key={item}><span>{item}</span><b>{[60, 1000, 10000, 1000000][i].toLocaleString()}</b></p>)}</Panel><Panel title="System Health"><div className="health">●<b>All Systems Normal</b></div></Panel></div></>; if (tab === 'settings') return <><Heading title="Settings" action="Save Changes" /><div className="api-grid three"><Panel title="General Settings"><Field label="Enable API" /><Field label="API Version" /></Panel><Panel title="Security Settings"><Field label="Require Authentication" /><Field label="Max Failed Requests" /></Panel><Panel title="Cache Settings"><Field label="Enable Response Caching" /><Field label="Cache Duration" /></Panel></div></>; return <Create webhook={tab === 'create-webhook'} /> }
export default function AdminAPIWebhooks() { const { pathname } = useLocation(); const current = pathname.split('/')[3] || 'overview'; const tab = current === 'docs' ? 'docs' : current === 'create-webhook' ? 'create-webhook' : tabs.some((item) => item[1] === current) ? current : 'overview'; return <AdminLayout><div className="api-page"><nav className="api-tabs" aria-label="API settings sections">{tabs.map(([label, key]) => <button type="button" className={key === tab ? 'active' : ''} onClick={() => navigateTo(`/admin/api/${key}`)} key={key}><Icon name={key === 'overview' ? 'house' : key === 'keys' ? 'key' : key === 'webhooks' ? 'link' : key === 'logs' ? 'list' : key === 'limits' ? 'gauge' : 'gear'} /> {label}</button>)}</nav><Content tab={tab} /></div></AdminLayout> }