/* eslint-disable no-unused-vars */
import { useMemo, useState } from 'react'
import { navigateTo } from '../navigation'
import AdminLayout from './AdminLayout'
import Icon from '../components/Icon'
import './marketing-pages.css'

const configs = {
  flash: { title: 'Flash Sales', singular: 'Flash Sale', icon: 'bolt', action: 'Create Flash Sale', stats: [['Total Flash Sales', '24', '18.2%', 'bolt'], ['Active Flash Sales', '6', '20.0%', 'circle-check'], ['Upcoming Flash Sales', '5', '11.1%', 'calendar'], ['Completed Flash Sales', '13', '16.4%', 'flag-checkered']], columns: ['Flash Sale Name', 'Type', 'Channel', 'Start Date', 'End Date', 'Status', 'Products', 'Sold', 'Progress'], rows: [['Mega Electronics Sale', 'Category', 'All Channels', 'May 18, 2025', 'May 19, 2025', 'Live', '125', '1,245', '78%'], ['Fashion Frenzy', 'Category', 'All Channels', 'May 16, 2025', 'May 17, 2025', 'Completed', '98', '2,340', '100%'], ['Mobile Mania', 'Product', 'App Only', 'May 20, 2025', 'May 20, 2025', 'Scheduled', '45', '0', '0%'], ['Home Essentials Deal', 'Category', 'All Channels', 'May 21, 2025', 'May 22, 2025', 'Scheduled', '76', '0', '0%'], ['Weekend Super Saver', 'Product', 'App Only', 'May 12, 2025', 'May 13, 2025', 'Completed', '110', '1,980', '100%'], ['Beauty Bonanza', 'Product', 'Website Only', 'May 14, 2025', 'May 14, 2025', 'Completed', '34', '870', '100%']] },
  banners: { title: 'Banners', singular: 'Banner', icon: 'images', action: 'Create Banner', stats: [['Total Banners', '56', '14.7%', 'images'], ['Active Banners', '28', '9.8%', 'circle-check'], ['Scheduled Banners', '12', '8.2%', 'calendar'], ['Expired Banners', '16', '4.7%', 'circle-xmark']], columns: ['Banner Name', 'Banner Type', 'Position', 'Start Date', 'End Date', 'Status', 'Views'], rows: [['Summer Sale 2025', 'Image', 'Homepage - Carousel', 'May 18, 2025', 'May 25, 2025', 'Active', '2,450'], ['Electronics Mega Deal', 'Image', 'Homepage - Top', 'May 15, 2025', 'May 24, 2025', 'Active', '1,980'], ['Fashion Collection', 'Image', 'Category Page - Top', 'May 14, 2025', 'May 22, 2025', 'Active', '1,320'], ['App Exclusive Offer', 'Image', 'App - Home Banner', 'May 12, 2025', 'May 20, 2025', 'Active', '930'], ['Weekend Special', 'Image', 'Homepage - Bottom', 'May 10, 2025', 'May 17, 2025', 'Expired', '850']] },
  financial: { title: 'Financial Sections', singular: 'Financial Section', icon: 'chart-pie', action: 'Create Section', stats: [['Total Sections', '18', '12.8%', 'chart-pie'], ['Active Sections', '11', '8.5%', 'circle-check'], ['Scheduled Sections', '4', '6.2%', 'calendar'], ['Inactive Sections', '3', '4.4%', 'circle-xmark']], columns: ['Section Name', 'Section Type', 'Position', 'Channel', 'Start Date', 'End Date', 'Status'], rows: [['Bank Offers', 'Bank Offer', 'Checkout Page', 'All Channels', 'May 18, 2025', 'May 31, 2025', 'Active'], ['FDIC Offers', 'Discount', 'Product Page', 'All Channels', 'May 15, 2025', 'May 30, 2025', 'Active'], ['No Cost EMI Section', 'EMI', 'Product Page', 'All Channels', 'May 10, 2025', 'May 25, 2025', 'Active'], ['COD Information', 'COD Info', 'Payment Page', 'All Channels', 'May 1, 2025', 'May 31, 2025', 'Active'], ['Secure Payment Info', 'Payment Info', 'Checkout Page', 'All Channels', 'Apr 20, 2025', 'May 20, 2025', 'Expired']] },
  campaigns: { title: 'Campaigns', singular: 'Campaign', icon: 'rectangle-ad', action: 'Create Campaign', stats: [['Total Campaigns', '28', '13.6%', 'rectangle-ad'], ['Active Campaigns', '12', '20.3%', 'circle-check'], ['Completed Campaigns', '10', '14.4%', 'flag-checkered'], ['Scheduled Campaigns', '6', '4.3%', 'calendar']], columns: ['Campaign Name', 'Type', 'Channel', 'Start Date', 'End Date', 'Budget', 'Spent', 'ROI'], rows: [['Summer Sale 2025', 'Seasonal', 'All Channels', 'May 18, 2025', 'May 31, 2025', 'Rs. 250,000', 'Rs. 152,450', '4.5x'], ['Eid Mega Sale', 'Seasonal', 'All Channels', 'Apr 15, 2025', 'Apr 30, 2025', 'Rs. 180,000', 'Rs. 178,420', '3.8x'], ['New Year Blast', 'Seasonal', 'All Channels', 'Jan 1, 2025', 'Jan 15, 2025', 'Rs. 120,000', 'Rs. 118,230', '2.9x'], ['Ramadan Deals', 'Category', 'All Channels', 'Mar 1, 2025', 'Mar 25, 2025', 'Rs. 200,000', 'Rs. 196,200', '4.1x'], ['Electronics Week', 'Category', 'Email', 'May 10, 2025', 'May 17, 2025', 'Rs. 60,000', 'Rs. 52,310', '3.2x']] },
  coupons: { title: 'Coupons', singular: 'Coupon', icon: 'ticket', action: '', stats: [['Total Coupons', '156', '16.2%', 'ticket'], ['Active Coupons', '78', '22.2%', 'circle-check'], ['Used Coupons', '1,243', '19.4%', 'ticket-simple'], ['Expired Coupons', '45', '4.1%', 'circle-xmark']], columns: ['Coupon Code', 'Discount', 'Usage', 'Limit', 'Status', 'Created By'], rows: [['SUMMER20', '20% OFF', '224 / 1000', '1000', 'Active', 'Super Admin'], ['SALE15', '15% OFF', '76 / 500', '500', 'Active', 'Super Admin'], ['FLASH10', '10% OFF', '423 / 1000', '1000', 'Active', 'Marketing Team'], ['WELCOME25', '25% OFF', '520 / 500', '500', 'Expired', 'Super Admin']] }
}
const getConfig = (type) => type === 'promotions' ? { ...configs.campaigns, title: 'Promotions', singular: 'Promotion', action: 'Create Promotion' } : configs[type]
configs.promotions = getConfig('promotions')
function Status({ value }) { return <span className={`marketing-status ${value.toLowerCase().replaceAll(' ', '-')}`}>{value}</span> }
function Heading({ title, action }) { const target = { Promotions: '/admin/promotions/new', Campaigns: '/admin/campaigns/new', 'Flash Sales': '/admin/flash-sales/new', Banners: '/admin/banners/new', 'Financial Sections': '/admin/financial-sections/new' }[title]; return <div className="marketing-heading"><div><h1>{title}</h1><p>Home <Icon name="chevron-right" /> Marketing <Icon name="chevron-right" /> {title}</p></div>{action && <button type="button" className="primary" onClick={() => target && navigateTo(target)}><Icon name="plus" /> {action}</button>}</div> }
function Kpis({ items }) { return <div className="marketing-kpis">{items.map(([label, value, change, icon], index) => <article key={label}><span className={`tone-${index}`}><Icon name={icon} /></span><small>{label}</small><strong>{value}</strong><em><Icon name="arrow-up" /> {change} <i>vs last 7 days</i></em></article>)}</div> }
function Filters({ placeholder }) { return <div className="marketing-filters"><label><Icon name="magnifying-glass" /><input placeholder={placeholder} aria-label={placeholder} /></label><select aria-label="Status"><option>All Status</option><option>Active</option><option>Completed</option><option>Scheduled</option><option>Expired</option></select><select aria-label="Type"><option>All Types</option><option>Category</option><option>Product</option></select><select aria-label="Channel"><option>All Channels</option><option>Website Only</option><option>App Only</option></select><button type="button"><Icon name="filter" /> Filters</button></div> }
function Table({ config, rows }) { return <div className="marketing-table-wrap"><table className="marketing-table"><thead><tr>{config.columns.map((header) => <th key={header}>{header}</th>)}<th>Action</th></tr></thead><tbody>{rows.map((row) => <tr key={row[0]}>{row.map((cell, index) => <td key={`${row[0]}-${index}`}>{['Live', 'Active', 'Completed', 'Scheduled', 'Expired'].includes(cell) ? <Status value={cell} /> : cell}</td>)}<td><button type="button" aria-label={`Actions for ${row[0]}`}><Icon name="ellipsis" /></button></td></tr>)}</tbody></table><div className="marketing-pagination">Showing 1 to {rows.length} of 28 records <span>‹ &nbsp; <b>1</b> &nbsp; 2 &nbsp; 3 &nbsp; 4 &nbsp; ›</span><select aria-label="Rows per page"><option>10 / page</option></select></div></div> }
function ListPage({ type }) { const config = configs[type]; const [search, setSearch] = useState(''); const rows = useMemo(() => config.rows.filter((row) => row.join(' ').toLowerCase().includes(search.toLowerCase())), [config.rows, search]); return <AdminLayout><div className="marketing-page"><Heading title={config.title} action={config.action} /><Kpis items={config.stats} /><section className="marketing-panel"><Filters placeholder={`Search by ${config.singular.toLowerCase()} name...`} /><Table config={config} rows={rows} /></section></div></AdminLayout> }
function CreatePage({ type }) { const config = configs[type]; return <AdminLayout><div className="marketing-page"><Heading title={`Create ${config.singular}`} /><section className="marketing-form"><div className="form-steps"><b>1 Details</b><span>2 ${type === 'campaigns' ? 'Audience' : 'Products'}</span><span>3 Schedule</span><span>4 Review</span></div><label>{config.singular} Name<input placeholder={`Enter ${config.singular.toLowerCase()} name...`} /></label><label>Type<select><option>Select Type</option><option>Seasonal</option><option>Category</option><option>Product</option></select></label><label>Channel<select><option>Select Channel</option><option>All Channels</option><option>Website Only</option></select></label><label>Description<textarea placeholder={`Enter ${config.singular.toLowerCase()} description...`} /></label><label>Banner Image<div className="upload"><Icon name="cloud-arrow-up" /><span>Drag & drop image here or click to upload</span><small>Recommended size: 1200x400px</small></div></label><div className="form-actions"><button type="button">Cancel</button><button type="button" className="primary">Next: {type === 'campaigns' ? 'Audience' : 'Products'} <Icon name="arrow-right" /></button></div></section></div></AdminLayout> }
function DetailPage() { return <AdminLayout><div className="marketing-page"><Heading title="Coupon Details" action="Actions" /><section className="coupon-detail"><div className="coupon-banner"><b>SUMMER20</b><strong>20% OFF</strong><small>Summer Sale Coupon</small><Status value="Active" /></div><Kpis items={ [['Total Uses', '224 / 1000', '12.4%', 'ticket'], ['Total Orders', '198', '15.7%', 'bag-shopping'], ['Total Revenue', 'Rs. 368,450', '18.4%', 'money-bill'], ['Avg. Order Value', 'Rs. 1,861', '12.8%', 'chart-line']] } /><div className="detail-two"><section className="marketing-panel"><h2>Usage Over Time</h2><div className="marketing-chart"><i /><i /><i /><i /><i /></div></section><section className="marketing-panel"><h2>Top Users</h2>{['Ahmad Raza', 'Fatima Noor', 'Usman Khan', 'Bilal Ahmed'].map((name) => <p className="top-user" key={name}><b>{name}</b><span>12 uses</span></p>)}</section></div><section className="marketing-panel"><h2>Coupon Information</h2><div className="info-grid"><p>Minimum Order Value <b>Rs. 5,000</b></p><p>Usage Limit <b>1000</b></p><p>Per User Limit <b>1</b></p><p>Applicable On <b>All Products</b></p></div></section></section></div></AdminLayout> }
function MarketingForm({ type }) {
  const config = configs[type]
  const nextLabel = type === 'campaigns' ? 'Audience' : type === 'coupons' ? 'Products' : 'Products'
  return <AdminLayout><div className="marketing-page"><Heading title={`Create ${config.singular}`} /><form className="marketing-form" onSubmit={(event) => event.preventDefault()}><div className="form-steps"><b>1 Details</b><span>2 {nextLabel}</span><span>3 Schedule</span><span>4 Review</span></div><label>{config.singular} Name<input required name="name" placeholder={`Enter ${config.singular.toLowerCase()} name...`} /></label><label>Type<select required name="type" defaultValue=""><option value="" disabled>Select Type</option><option>Seasonal</option><option>Category</option><option>Product</option></select></label><label>Channel<select required name="channel" defaultValue=""><option value="" disabled>Select Channel</option><option>All Channels</option><option>Website Only</option><option>App Only</option></select></label>{type === 'coupons' && <div className="form-row"><label>Discount Type<select><option>Percentage</option><option>Fixed Amount</option></select></label><label>Discount Value<input type="number" min="1" placeholder="20" /></label></div>}<label>Description<textarea required placeholder={`Enter ${config.singular.toLowerCase()} description...`} /></label><label>Banner Image<div className="upload"><Icon name="cloud-arrow-up" /><span>Drag & drop image here or click to upload</span><small>Recommended size: 1200x400px (PNG, JPG)</small></div></label><div className="form-actions"><button type="button">Cancel</button><button type="submit" className="primary">Next: {nextLabel} <Icon name="arrow-right" /></button></div></form></div></AdminLayout>
}
export default function AdminMarketingPages({ type = 'flash', create = false, detail = false }) { if (create) return <MarketingForm type={type} />; if (detail) return <DetailPage />; return <ListPage type={type} /> }