import { useLocation } from 'react-router-dom'
import { navigateTo } from '../navigation'
import AdminLayout from './AdminLayout'
import Icon from '../components/Icon'
import './security-pages.css'

const tabs = [['Overview', 'overview'], ['Users & Roles', 'users'], ['2FA Settings', '2fa'], ['Login Policies', 'policies'], ['Rate Limits', 'limits'], ['IP Whitelist', 'whitelist'], ['Security Activity Log', 'activity'], ['Security Headers', 'headers']]
const users = [['Super Admin', 'admin@mirwal.com', 'Super Admin', 'Active', 'Enabled', 'May 25, 2025 10:30 AM'], ['Sarah Khan', 'sarah.khan@mirwal.com', 'Administrator', 'Active', 'Enabled', 'May 25, 2025 09:10 AM'], ['John Doe', 'john.doe@mirwal.com', 'Manager', 'Active', 'Disabled', 'May 25, 2025 08:45 AM'], ['Ali Raza', 'ali.raza@mirwal.com', 'Editor', 'Active', 'Enabled', 'May 24, 2025 11:20 PM'], ['Fatima Noor', 'fatima.noor@mirwal.com', 'Support', 'Inactive', 'Disabled', 'May 22, 2025 03:40 PM']]
const activity = [['May 25, 2025 10:30 AM', 'admin', 'Login Success', '192.168.1.10', 'Success', 'Chrome on Windows'], ['May 25, 2025 09:15 AM', 'john.doe', 'Failed Login', '103.0.113.45', 'Failed', 'Invalid password'], ['May 25, 2025 08:45 AM', 'sarah.k', '2FA Enabled', '192.168.1.10', 'Success', 'Google Authenticator'], ['May 24, 2025 11:20 PM', 'admin', 'Password Changed', '192.168.1.10', 'Success', ''], ['May 24, 2025 10:05 PM', 'system', 'IP Blocked', '198.168.1.10', 'Success', 'Multiple failed attempts']]
function Panel({ title, children }) { return <section className="security-panel"><h2>{title}</h2>{children}</section> }
function Toggle({ label, description, checked = false }) { return <div className="security-toggle"><div><b>{label}</b><small>{description}</small></div><button type="button" className={checked ? 'on' : ''} aria-pressed={checked} aria-label={label}><i /></button></div> }
function Kpis({ items }) { return <div className="security-kpis">{items.map(([label, value, change, icon], index) => <article key={label}><span className={`tone-${index}`}><Icon name={icon} /></span><small>{label}</small><strong>{value}</strong><em><Icon name="arrow-up" /> {change} <i>vs last 7 days</i></em></article>)}</div> }
function Heading({ title, action }) { return <div className="security-heading"><div><h1>Security - {title}</h1><p>Home <Icon name="chevron-right" /> System <Icon name="chevron-right" /> Security <Icon name="chevron-right" /> {title}</p></div>{action && <button type="button" className="primary"><Icon name="plus" /> {action}</button>}</div> }
function Table({ headers, rows, status = -1 }) { return <div className="security-table-wrap"><table className="security-table"><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}<th>Actions</th></tr></thead><tbody>{rows.map((row) => <tr key={row[0]}>{row.map((cell, index) => <td key={`${row[0]}-${index}`}>{index === status ? <span className={`security-status ${cell.toLowerCase()}`}>{cell}</span> : cell}</td>)}<td><button type="button" aria-label={`Edit ${row[0]}`}><Icon name="pen" /></button><button type="button" aria-label={`Delete ${row[0]}`}><Icon name="trash" /></button></td></tr>)}</tbody></table><div className="security-pagination">Showing 1 to {rows.length} entries <span>‹ &nbsp; <b>1</b> &nbsp; 2 &nbsp; 3 &nbsp; ›</span></div></div> }
function Overview() { return <><Kpis items={ [['Total Logins', '1,245', '14.3%', 'right-to-bracket'], ['Failed Logins', '42', '8.3%', 'circle-xmark'], ['Blocked IPs', '18', '5.2%', 'ban'], ['2FA Enabled Users', '156', '18.7%', 'shield-halved']] } /><div className="security-grid two"><Panel title="Login Attempts (Last 7 Days)"><div className="security-chart">{[48, 67, 56, 78, 52, 64, 44, 58].map((height, index) => <i key={index} style={{ height: `${height}%` }} />)}</div></Panel><Panel title="Recent Security Events">{['Successful login - admin', 'Failed login attempt - john.doe', '2FA enabled - sarah.k', 'Password changed - admin', 'IP blocked - 192.168.1.10'].map((item, index) => <p key={item}><Icon name={index === 1 ? 'circle-xmark' : 'circle-check'} />{item}<small>May 25, 2025 10:30 AM</small></p>)}</Panel></div><Panel title="Quick Actions"><div className="security-actions">{['Manage Users', '2FA Settings', 'Login Security', 'IP Whitelist', 'API Security'].map((item, index) => <button type="button" key={item} onClick={() => navigateTo(`/admin/security/${['users', '2fa', 'policies', 'whitelist', 'headers'][index]}`)}><Icon name={['users', 'shield-halved', 'lock', 'list', 'key'][index]} /> {item}</button>)}</div></Panel></> }
function Settings({ tab }) { const names = { '2fa': ['2FA Settings', 'Security Methods'], policies: ['Login Policies', 'Session Management'], limits: ['Rate Limit Settings', 'Rate Limit Overview'], whitelist: ['IP Whitelist Settings', 'Whitelisted IPs'], headers: ['HTTP Security Headers', 'Security Header Values'] }; const [left, right] = names[tab] || names.policies; return <div className="security-grid two"><Panel title={left}><Toggle label="Enable Feature" description="Enable this security protection" checked /><Toggle label="Require for Admins" description="Require this setting for administrators" checked /><Toggle label="Allow Remember Device" description="Allow trusted devices for 30 days" checked /><label>Configuration<input defaultValue={tab === 'limits' ? '1000 requests per minute' : 'Default setting'} /></label></Panel><Panel title={right}>{['Default Policy', 'Max Attempts', 'Lockout Time (minutes)', 'Allowed Values'].map((field) => <label key={field}>{field}<input defaultValue={field === 'Max Attempts' ? '5' : field === 'Lockout Time (minutes)' ? '30' : 'Enabled'} /></label>)}<button type="button" className="security-primary">Save Changes</button></Panel></div> }
function SecurityPage({ tab }) { if (tab === 'overview') return <Overview />; if (tab === 'users') return <><Heading title="Users & Roles" action="Add User" /><div className="security-tabs-inner"><button type="button" className="active">Users</button><button type="button">Roles & Permissions</button></div><Panel title="Security Users"><Table headers={['User', 'Role', 'Status', '2FA Status', 'Last Login']} rows={users.map((row) => [row[0], row[2], row[3], row[4], row[5]])} status={2} /></Panel></>; if (tab === 'activity') return <><Heading title="Security Activity Log" action="Export" /><Panel title="Security Activity Log"><Table headers={['Date & Time', 'User', 'Action', 'IP Address', 'Status', 'Details']} rows={activity} status={4} /></Panel></>; if (tab === 'policies' || tab === '2fa' || tab === 'limits' || tab === 'whitelist' || tab === 'headers') return <><Heading title={tabs.find((item) => item[1] === tab)[0]} action="Save Changes" /><Settings tab={tab} /></>; return <><Heading title="Overview" /><Overview /></> }
export default function AdminSecurityPages() { const { pathname } = useLocation(); const current = pathname.split('/')[3] || 'overview'; const tab = tabs.find((item) => item[1] === current) || tabs[0]; return <AdminLayout><div className="security-page"><nav className="security-tabs" aria-label="Security sections">{tabs.map(([label, key]) => <button type="button" className={key === tab[1] ? 'active' : ''} onClick={() => navigateTo(`/admin/security/${key}`)} key={key}><Icon name={key === 'overview' ? 'house' : key === 'activity' ? 'list' : key === 'limits' ? 'gauge' : 'shield-halved'} /> {label}</button>)}</nav><SecurityPage tab={tab[1]} /></div></AdminLayout> }