import { useState } from 'react'
import Header from './components/Header'
import { products } from './data/mockData'
import './ai-assistant.css'
import { navigateTo } from './navigation'

const FaIcon = ({ name }) => <i className={`fa-solid fa-${name}`} aria-hidden="true" />
const configs = {
  '/track-orders': ['truck', 'Track Your Order', 'Enter your order ID or tracking number to see the latest delivery status.'],
  '/compare': ['scale-balanced', 'Compare Products', 'Compare products side by side and choose with confidence.'],
  '/addresses': ['location-dot', 'My Addresses', 'Manage your saved delivery addresses.'],
  '/payment-methods': ['credit-card', 'My Payment Methods', 'Manage your saved cards and payment options.'],
  '/notifications': ['bell', 'Notifications', 'Stay up to date with your orders and smart shopping alerts.'],
  '/security': ['shield-halved', 'Security Settings', 'Keep your Mirwal account protected.'],
  '/logout': ['right-from-bracket', 'Logout', ''],
}

function navigate(path) { navigateTo(path) }

export function AccountSidebar({ active }) {
  const links = [['user', 'Profile', '/profile'], ['box', 'Orders', '/orders'], ['truck', 'Track Orders', '/track-orders'], ['heart', 'Wishlist', '/wishlist'], ['scale-balanced', 'Compare', '/compare'], ['location-dot', 'Addresses', '/addresses'], ['credit-card', 'Payment Methods', '/payment-methods'], ['bell', 'Notifications', '/notifications'], ['shield-halved', 'Security', '/security']]
  return <aside className="profile-sidebar"><b className="profile-sidebar-title">MY ACCOUNT</b>{links.map(([icon, label, path]) => <button className={label === active ? 'active' : ''} type="button" key={label} onClick={() => navigate(path)}><FaIcon name={icon} /> {label}{label === 'Wishlist' && <i className="profile-count">4</i>}{label === 'Compare' && <i className="profile-count">0</i>}{label === 'Notifications' && <i className="profile-count">3</i>}</button>)}<button className="profile-logout" type="button" onClick={() => navigate('/logout')}><FaIcon name="right-from-bracket" /> Logout</button></aside>
}

function TrackingDetail({ delivered, onBack }) { const steps = delivered ? ['Order Placed', 'Confirmed', 'Shipped', 'Out for Delivery', 'Delivered'] : ['Order Placed', 'Confirmed', 'Shipped', 'In Transit', 'Out for Delivery', 'Delivered']; const activeStep = delivered ? 4 : 3; return <div className="tracking-detail"><button className="tracking-back" type="button" onClick={onBack}><FaIcon name="arrow-left" /> Back to Track Orders</button><section className="utility-card tracking-summary"><div><small>Order ID</small><b>{delivered ? 'MW-10461' : 'MW-10482'} <FaIcon name="copy" /></b></div><div><small>Order Placed</small><b>{delivered ? 'Aug 20, 2026' : 'Aug 24, 2026'}</b></div><div><small>{delivered ? 'Delivered On' : 'Estimated Delivery'}</small><b>{delivered ? 'Aug 22, 2026 02:45 PM' : 'Aug 28, 2026 by 8:00 PM'}</b></div><em className={delivered ? 'delivered' : 'transit'}>{delivered ? 'Delivered' : 'In Transit'}</em></section><section className="utility-card tracking-progress"><h2>Tracking Status</h2><div className="tracking-line">{steps.map((step, index) => <div className={index <= activeStep ? 'complete' : index === activeStep + 1 ? 'current' : ''} key={step}><span><FaIcon name={index === activeStep ? 'truck' : index <= activeStep ? 'check' : 'circle'} /></span><b>{step}</b><small>{index <= activeStep ? (delivered ? 'Aug 22, 02:45 PM' : `Aug ${24 + index}, 10:30 AM`) : 'Pending'}</small></div>)}</div></section><div className="tracking-lower"><section className="utility-card tracking-events"><h2>Tracking Details</h2>{['Your order is in transit', 'Your order has been shipped', 'Your order has been confirmed', 'Your order has been placed'].map((event, index) => <p key={event}><span />{event}<small>{index === 0 && !delivered ? 'Aug 26, 11:20 AM' : `Aug ${24 - index}, 10:30 AM`}</small></p>)}</section><section className="utility-card tracking-address"><h2>Delivery Address</h2><b>Muhammad Umar</b><p>House # 725, Street 45, Phase 2<br />DHA, Lahore, Punjab 54000<br />Pakistan</p><hr /><small>Courier Partner</small><strong><FaIcon name="truck" /> Leopard Courier</strong><button type="button">Contact Courier</button></section></div>{delivered && <div className="tracking-delivered"><FaIcon name="circle-check" /><span><b>Your order has been delivered</b><small>We hope you love your purchase.</small></span><button type="button">View Order Details</button></div>}</div> }
function TrackOrders() { const [query, setQuery] = useState(''); const [trackingState, setTrackingState] = useState(() => new URLSearchParams(window.location.search).get('empty') === '1' ? 'empty' : 'input'); const submit = (event) => { event.preventDefault(); const value = query.trim().toLowerCase(); setTrackingState(!value || !value.includes('10482') && !value.includes('10461') ? 'not-found' : value.includes('10461') ? 'delivered' : 'transit') }; if (trackingState === 'empty') return <section className="utility-card tracking-empty"><div><FaIcon name="clipboard-question" /></div><h2>No order to track</h2><p>You don't have any orders yet.<br />Place an order and track it here.</p><button type="button" onClick={() => navigate('/explore')}>Start Shopping</button></section>; if (trackingState === 'not-found') return <section className="utility-card tracking-empty tracking-not-found"><div><FaIcon name="magnifying-glass" /></div><h2>No tracking or product available to track</h2><p>Enter a valid order ID or tracking number to see your delivery status.</p><button type="button" onClick={() => setTrackingState('input')}>Try Again</button></section>; if (trackingState === 'transit' || trackingState === 'delivered') return <TrackingDetail delivered={trackingState === 'delivered'} onBack={() => setTrackingState('input')} />; return <div className="utility-stack"><form className="utility-card track-form" onSubmit={submit}><h2>Track Your Order</h2><p>Enter your order ID or tracking number to check the status of your order.</p><div><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Enter your Order ID or Tracking Number" aria-label="Order ID or tracking number" /><button type="submit">Track Order</button></div></form><section className="utility-card"><h2>How it works?</h2>{[['1', 'Enter your Order ID', 'You can find your Order ID in your order confirmation email.'], ['2', 'Track and view order status', 'Get real-time updates on your order status.'], ['3', 'Stay updated', 'We’ll notify you when your order is out for delivery.']].map(([number, title, copy]) => <div className="track-step" key={number}><b>{number}</b><span><strong>{title}</strong><small>{copy}</small></span></div>)}</section><section className="utility-card"><h2>Recent Tracking</h2>{products.slice(0, 4).map((product, index) => <div className="tracking-row" key={product.id}><span><b>#MW-{10482 - index * 21}</b><small>Ordered on Aug {24 - index * 4}, 2026</small></span><em className={index === 2 ? 'processing' : 'delivered'}>{index === 2 ? 'Processing' : 'Delivered'}</em><button type="button" onClick={() => { setQuery(`MW-${10482 - index * 21}`); setTrackingState(index === 0 ? 'transit' : 'delivered') }}>View</button></div>)}</section></div> }
function Compare() { return <section className="utility-card compare-utility"><div className="utility-card-heading"><h2>Compare Products (3)</h2><button type="button">Clear All</button></div><div className="compare-products">{products.slice(0, 3).map((product) => <article key={product.id}><button type="button" aria-label={`Remove ${product.name}`}><FaIcon name="xmark" /></button><img src={product.image} alt={product.name} /><b>{product.name}</b><strong>{product.price}</strong><em>In Stock</em></article>)}</div><div className="compare-table">{[['Display', '6.7” Super Retina', '6.7” Dynamic AMOLED', '6.7” FHD+ OLED'], ['Processor', 'A17 Pro Chip', 'Snapdragon 8 Gen 3', 'Tensor G4'], ['RAM', '8GB', '12GB', '12GB'], ['Storage', '256GB', '256GB', '256GB'], ['Battery', '3349mAh', '5000mAh', '5050mAh'], ['Camera', '48MP Triple Camera', '200MP Quad Camera', '50MP Triple Camera']].map(([label, ...values]) => <div key={label}><b>{label}</b>{values.map((value) => <span key={value}>{value}</span>)}</div>)}</div><div className="compare-actions"><button type="button">View Product</button><button type="button">View Product</button><button type="button">View Product</button></div></section> }
function Addresses() { return <section className="utility-card address-utility"><div className="utility-card-heading"><h2>My Addresses</h2><button type="button"><FaIcon name="plus" /> Add New Address</button></div>{['Muhammad Umar|+92 300 1234567|House # 123, Street 45, Phase 2|DHA, Lahore, Punjab 54000|Pakistan', 'Muhammad Umar|+92 300 1234567|Mirwal Office, 2nd Floor, Alpha Software Technology Park|Lahore, Punjab 54000'].map((address, index) => { const lines = address.split('|'); return <article className="address-item" key={`${lines[0]}-${index}`}><div><b>{index ? 'Work Address' : 'Default Address'}</b><strong>{lines[0]}</strong>{lines.slice(1).map((line) => <small key={line}>{line}</small>)}</div><span><button type="button"><FaIcon name="pen" /> Edit</button><button type="button"><FaIcon name="trash" /> Delete</button></span></article> })}</section> }
function Payments() { return <section className="utility-card payment-utility"><div className="utility-card-heading"><h2>My Payment Methods</h2><button type="button"><FaIcon name="plus" /> Add New Card</button></div>{[['cc-visa', 'Visa ending in 4242', 'Expires 12/28', 'Default'], ['cc-mastercard', 'Mastercard ending in 8888', 'Expires 09/27', ''], ['money-bill-transfer', 'EasyPaisa', '0333 1234567', ''], ['wallet', 'JazzCash', '0312 7654321', '']].map(([icon, name, detail, badge]) => <div className="payment-row" key={name}><span><FaIcon name={icon} /></span><div><b>{name}</b><small>{detail}</small></div>{badge && <em>{badge}</em>}<button type="button"><FaIcon name="ellipsis-vertical" /></button></div>)}<p><FaIcon name="shield-halved" /> Your payment information is secure and encrypted.</p></section> }
function Notifications() { return <section className="utility-card notification-utility"><div className="utility-card-heading"><h2>Notifications</h2><button type="button">Mark all as read</button></div>{[['box', 'Order Shipped', 'Your order #MW-10482 has been shipped.', '2h ago'], ['bell', 'Flash Sale Alert', 'Up to 50% off on Electronics. Shop now!', '1d ago'], ['tag', 'Price Drop', 'iPhone 15 Pro Max price dropped!', '2d ago'], ['bag-shopping', 'New Arrival', 'New products in your wishlist category.', '3d ago'], ['box', 'Order Delivered', 'Your order #MW-10461 has been delivered.', '5d ago']].map(([icon, title, copy, time]) => <article key={title}><span><FaIcon name={icon} /></span><div><b>{title}</b><p>{copy}</p></div><small>{time}</small></article>)}<button className="utility-outline-action" type="button">View All Notifications</button></section> }
function Security() { const [saved, setSaved] = useState(false); return <section className="utility-card security-utility"><h2>Security Settings</h2>{[['key', 'Change Password', 'Update your password regularly to keep your account secure.', 'Change Password'], ['shield-halved', 'Two-Factor Authentication', 'Add an extra layer of security to your account.', 'Enabled'], ['clock-rotate-left', 'Login Activity', 'View your recent login activity and devices.', 'View Activity'], ['laptop', 'Manage Devices', 'Manage devices that have access to your account.', 'Manage']].map(([icon, title, copy, action]) => <div className="security-row" key={title}><span><FaIcon name={icon} /></span><div><b>{title}</b><small>{copy}</small></div><button type="button" onClick={() => setSaved(true)}>{action}</button></div>)}<div className="delete-account"><span><b>Delete Account</b><small>Permanently delete your account and all data.</small></span><button type="button">Delete Account</button></div>{saved && <p className="utility-saved">Your security preference was updated.</p>}</section> }
function Logout() { return <section className="utility-card logout-utility"><div><FaIcon name="lock" /></div><h2>Are you sure you want to logout?</h2><p>You will be logged out of your account on this device.</p><button type="button" onClick={() => navigate('/login')}>Logout</button><button type="button" onClick={() => navigate('/profile')}>Cancel</button></section> }

export function AccountUtilityContent({ path }) { const config = configs[path] || configs['/track-orders']; return <div className="utility-content"><section className="utility-heading"><span><FaIcon name={config[0]} /></span><div><h1>{config[1]}</h1><p>{config[2]}</p></div></section>{path === '/track-orders' && <TrackOrders />}{path === '/compare' && <Compare />}{path === '/addresses' && <Addresses />}{path === '/payment-methods' && <Payments />}{path === '/notifications' && <Notifications />}{path === '/security' && <Security />}{path === '/logout' && <Logout />}</div> }
export default function AccountUtilityPage({ path, cartCount }) { const config = configs[path] || configs['/track-orders']; const active = config[1].replace('Your ', '').replace('My ', ''); return <div className="assistant-page"><Header cartCount={cartCount} /><main className="account-utility-page container"><div className="profile-breadcrumb"><button type="button" onClick={() => navigate('/')}>Home</button><FaIcon name="chevron-right" /><button type="button" onClick={() => navigate('/profile')}>My Account</button><FaIcon name="chevron-right" /><b>{config[1]}</b></div><div className="profile-layout"><AccountSidebar active={active} /><AccountUtilityContent path={path} /></div></main></div> }