import Header from './components/Header'
import { products } from './data/mockData'
import './ai-assistant.css'
import { navigateTo } from './navigation'

const FaIcon = ({ name }) => <i className={`fa-solid fa-${name}`} aria-hidden="true" />
const accountLinks = [['user', 'Profile', '/profile'], ['box', 'Orders', '/orders'], ['truck', 'Track Orders', '/track-orders'], ['heart', 'Wishlist', '/wishlist'], ['scale-balanced', 'Compare', '/compare'], ['location-dot', 'Addresses', '/addresses'], ['credit-card', 'Payment Methods', '/payment-methods'], ['bell', 'Notifications', '/notifications'], ['shield-halved', 'Security', '/security']]
const orders = [
  { id: '#MW-10482', date: 'Aug 24, 2026, 10:30 AM', items: [products[3], products[1], products[5]], count: '4 Items', store: 'Mirwal Official Store', total: 'Rs. 24,990', status: 'Shipped', statusClass: 'shipped' },
  { id: '#MW-10461', date: 'Aug 20, 2026, 02:15 PM', items: [products[3], products[2], products[5]], count: '3 Items', store: 'MegaMart', total: 'Rs. 12,490', status: 'Delivered', statusClass: 'delivered' },
  { id: '#MW-10423', date: 'Aug 15, 2026, 11:05 AM', items: [products[2], products[4]], count: '2 Items', store: 'Home Essentials', total: 'Rs. 8,990', status: 'Processing', statusClass: 'processing' },
  { id: '#MW-10398', date: 'Aug 10, 2026, 09:40 PM', items: [products[0]], count: '1 Item', store: 'Mirwal Official Store', total: 'Rs. 56,990', status: 'Delivered', statusClass: 'delivered' },
  { id: '#MW-10345', date: 'Aug 5, 2026, 06:25 PM', items: [products[6], products[4]], count: '4 Items', store: 'Fashion Hub', total: 'Rs. 7,450', status: 'Cancelled', statusClass: 'cancelled' },
]

function navigate(path) { navigateTo(path) }

function AccountSidebar() {
  return <aside className="profile-sidebar"><b className="profile-sidebar-title">MY ACCOUNT</b>{accountLinks.map(([icon, label, path]) => <button className={label === 'Orders' ? 'active' : ''} type="button" key={label} onClick={() => navigate(path)}><FaIcon name={icon} /> {label}{label === 'Wishlist' && <i className="profile-count">4</i>}{label === 'Compare' && <i className="profile-count">0</i>}{label === 'Notifications' && <i className="profile-count">3</i>}</button>)}<button className="profile-logout" type="button" onClick={() => navigate('/login')}><FaIcon name="right-from-bracket" /> Logout</button><section className="profile-help"><FaIcon name="headset" /><b>Need Help?</b><p>We're here to help you with your orders.</p><button type="button" onClick={() => window.location.href = 'mailto:support@mirwal.com'}>Contact Support <FaIcon name="arrow-right" /></button></section></aside>
}

export default function ProfileOrdersPage({ cartCount }) {
  return <div className="assistant-page"><Header cartCount={cartCount} /><main className="orders-page container"><div className="profile-breadcrumb"><button type="button" onClick={() => navigate('/')}>Home</button><FaIcon name="chevron-right" /><button type="button" onClick={() => navigate('/profile')}>My Account</button><FaIcon name="chevron-right" /><b>Orders</b></div><div className="profile-layout"><AccountSidebar /><div className="orders-content"><header className="orders-heading"><div><h1>My Orders</h1><p>View and manage all your orders in one place.</p></div><div className="orders-tools"><label><FaIcon name="magnifying-glass" /><input placeholder="Search orders..." aria-label="Search orders" /></label><button type="button"><FaIcon name="filter" /> Filter</button></div></header><section className="orders-panel"><nav className="orders-tabs" aria-label="Order status"><button className="active" type="button">All Orders (12)</button><button type="button">Processing (2)</button><button type="button">Shipped (3)</button><button type="button">Delivered (6)</button><button type="button">Cancelled (1)</button><button type="button">Returned (0)</button></nav>{orders.map((order) => <article className="order-row" key={order.id}><div className="order-id"><small>Order ID</small><b>{order.id}</b><small>Placed on</small><span>{order.date}</span></div><div className="order-items">{order.items.map((product) => <img key={product.id} src={product.image} alt={product.name} />)}{order.count === '4 Items' && <em>+1</em>}</div><div className="order-summary"><b>{order.count}</b><small>Sold by {order.store}</small></div><div className="order-total"><small>Total Amount</small><b>{order.total}</b></div><div className="order-status"><small>Status</small><em className={order.statusClass}>{order.status}</em></div><div className="order-actions"><button type="button">View Details <FaIcon name="arrow-right" /></button>{order.status !== 'Cancelled' && <button type="button">Track Order</button>}</div></article>)}<footer className="orders-footer"><span>Showing 1 to 5 of 12 orders</span><div><button type="button" aria-label="Previous page"><FaIcon name="chevron-left" /></button><button className="active" type="button">1</button><button type="button">2</button><button type="button">3</button><button type="button" aria-label="Next page"><FaIcon name="chevron-right" /></button></div></footer></section></div></div></main></div>
}