import { test, before, after } from 'node:test'
import assert from 'node:assert/strict'
import { startTestServer, apiFetch, registerTestUser, loginAs } from './setup.js'
import { queryOne, closePool } from '../src/db/pool.js'

/**
 * In-app notifications (server/src/modules/notifications), generated by real events in
 * orders.service.js — this file didn't exist when notifications shipped, which is the gap
 * it closes.
 *
 * Uses Dev Store Alpha's "USB-C hub 7-in-1" (DEV-A-015, seeded with 120 units) — distinct from
 * orders.test.js (car phone holder/GaN charger) and returns.test.js (Lightning cable), so this
 * file can't race either on shared inventory.
 */

let server
let buyer
let sellerAToken

const HUB_QUERY = "SELECT public_id FROM products WHERE name = 'USB-C hub 7-in-1' LIMIT 1"

before(async () => {
  server = await startTestServer()
  buyer = await registerTestUser(server.baseUrl, { label: 'notif-buyer' })
  sellerAToken = await loginAs(server.baseUrl, 'seller.a@mirwal.test', 'MirwalDev123!')
})

after(async () => {
  try {
    // Left in place, not deleted — same reasoning as orders.test.js: this buyer placed real
    // orders, which fk_orders_buyer (ON DELETE RESTRICT) correctly refuses to orphan.
  } finally {
    await server.close()
    await closePool()
  }
})

async function placeHubOrder() {
  const product = await queryOne(HUB_QUERY)
  const result = await apiFetch(server.baseUrl, '/orders', {
    method: 'POST',
    token: buyer.accessToken,
    body: {
      items: [{ productId: product.public_id, quantity: 1 }],
      shippingAddress: { fullName: 'Test Buyer', phone: '03001112222', line1: 'House 1', city: 'Lahore' },
    },
  })
  assert.equal(result.status, 201)
  return result.body.data
}

test('placing an order notifies both the buyer and the owning seller, atomically', async () => {
  const order = await placeHubOrder()
  const orderItemId = order.items[0].id

  const buyerNotifs = await apiFetch(server.baseUrl, '/notifications', { token: buyer.accessToken })
  const placedNotif = buyerNotifs.body.data.find((n) => n.type === 'order_placed' && n.title.includes(order.orderNumber))
  assert.ok(placedNotif, 'buyer should have an order_placed notification')
  assert.equal(placedNotif.read, false)
  assert.equal(placedNotif.link, `/order-success/${order.id}`)

  const sellerNotifs = await apiFetch(server.baseUrl, '/notifications', { token: sellerAToken })
  const newOrderNotif = sellerNotifs.body.data.find((n) => n.type === 'new_order' && n.title.includes(order.orderNumber))
  assert.ok(newOrderNotif, 'seller should have a new_order notification')

  // A status change notifies the buyer with the specific new status.
  const confirmed = await apiFetch(server.baseUrl, `/seller/me/orders/${orderItemId}/status`, {
    method: 'PATCH', token: sellerAToken, body: { status: 'confirmed' },
  })
  assert.equal(confirmed.status, 200)

  const buyerNotifsAfter = await apiFetch(server.baseUrl, '/notifications', { token: buyer.accessToken })
  const statusNotif = buyerNotifsAfter.body.data.find((n) => n.type === 'order_status_changed' && n.title.includes(order.orderNumber))
  assert.ok(statusNotif, 'buyer should have an order_status_changed notification')
  assert.ok(statusNotif.title.includes('confirmed'))

  // Cleanup: cancel restocks the inventory this test decremented.
  const cancelled = await apiFetch(server.baseUrl, `/orders/items/${orderItemId}/cancel`, { method: 'PATCH', token: buyer.accessToken })
  assert.equal(cancelled.status, 200)

  const sellerNotifsAfterCancel = await apiFetch(server.baseUrl, '/notifications', { token: sellerAToken })
  const cancelNotif = sellerNotifsAfterCancel.body.data.find((n) => n.type === 'item_cancelled' && n.title.includes(order.orderNumber))
  assert.ok(cancelNotif, 'seller should have an item_cancelled notification')
})

test('marking a notification read is ownership-checked, and mark-all-read clears every unread one', async () => {
  const order = await placeHubOrder()

  const buyerNotifs = await apiFetch(server.baseUrl, '/notifications', { token: buyer.accessToken })
  const notif = buyerNotifs.body.data.find((n) => n.title.includes(order.orderNumber))
  assert.ok(notif)

  const intrusion = await apiFetch(server.baseUrl, `/notifications/${notif.id}/read`, { method: 'PATCH', token: sellerAToken })
  assert.equal(intrusion.status, 403)

  const markedRead = await apiFetch(server.baseUrl, `/notifications/${notif.id}/read`, { method: 'PATCH', token: buyer.accessToken })
  assert.equal(markedRead.status, 200)

  const allRead = await apiFetch(server.baseUrl, '/notifications/read-all', { method: 'PATCH', token: buyer.accessToken })
  assert.equal(allRead.status, 200)

  const afterMarkAll = await apiFetch(server.baseUrl, '/notifications', { token: buyer.accessToken })
  assert.ok(afterMarkAll.body.data.every((n) => n.read), 'every notification should be read after mark-all-read')

  // Cleanup: cancel restocks the inventory this test decremented.
  const cancelled = await apiFetch(server.baseUrl, `/orders/items/${order.items[0].id}/cancel`, { method: 'PATCH', token: buyer.accessToken })
  assert.equal(cancelled.status, 200)
})

test('a real return request and its resolution both notify the right party', async () => {
  const order = await placeHubOrder()
  const orderItemId = order.items[0].id

  for (const status of ['confirmed', 'processing', 'shipped', 'delivered']) {
    const result = await apiFetch(server.baseUrl, `/seller/me/orders/${orderItemId}/status`, {
      method: 'PATCH', token: sellerAToken, body: { status },
    })
    assert.equal(result.status, 200, `advancing to ${status} failed`)
  }

  const returnRequest = await apiFetch(server.baseUrl, `/orders/items/${orderItemId}/return-request`, {
    method: 'POST', token: buyer.accessToken, body: { reason: 'Wrong item received' },
  })
  assert.equal(returnRequest.status, 201)

  const sellerNotifs = await apiFetch(server.baseUrl, '/notifications', { token: sellerAToken })
  const returnRequestedNotif = sellerNotifs.body.data.find((n) => n.type === 'return_requested' && n.title.includes(order.orderNumber))
  assert.ok(returnRequestedNotif, 'seller should have a return_requested notification')

  const returnRequestId = returnRequest.body.data.returnRequest.id
  const resolved = await apiFetch(server.baseUrl, `/seller/me/returns/${returnRequestId}/status`, {
    method: 'PATCH', token: sellerAToken, body: { status: 'approved', resolutionNote: 'Refunded in cash.' },
  })
  assert.equal(resolved.status, 200)

  const buyerNotifs = await apiFetch(server.baseUrl, '/notifications', { token: buyer.accessToken })
  const resolvedNotif = buyerNotifs.body.data.find((n) => n.type === 'return_resolved' && n.title.includes(order.orderNumber))
  assert.ok(resolvedNotif, 'buyer should have a return_resolved notification')
  assert.ok(resolvedNotif.body.includes('Refunded in cash.'))
  // No cleanup needed: approving the return already restocked the inventory this test used.
})
